### ISSUE TITLE
nn.MapTable not available

### ISSUE THREAD

**Issue by fanyangxyz** [torch/nn#1003]
Is this container still available? Cause when I try to use it, the error message says it's a nil value.

**Comment by fmassa** [comment]
This is not a module from standard `nn`.
Maybe `dpnn`?

**Comment by fanyangxyz** [comment]
I tried `dpnn`, it didn't work either. 
How can you tell whether `nn.MapTable` is a module of `nn`? 
I assume it's part of `nn` because I found its source code under the `nn` folder. 
https://github.com/torch/nn/blob/master/MapTable.lua

**Comment by fmassa** [comment]
Sorry about the false alarm. It's being a log day :-)
This is a somewhat new module, did you try updating `nn` ? (And if you have compilation issues, you also need to update torch, and cutorch)

**Comment by fanyangxyz** [comment]
No problem. 
Btw, do you know how to use luarocks to update the `nn` package? 
There doesn't seem to be a update command...

**Comment by fmassa** [comment]
`luarocks install nn` pulls the latest version and install/update your installation

**Comment by fanyangxyz** [comment]
In the process of updating the `nn` package, I accidentally broke my entire `torch`. Se ended up re-installing the whole thing. But it worked! I can use nn.MapTable() now. Thanks!
