### ISSUE TITLE
THNN.lua:109: wrong number of arguments for function call

### ISSUE THREAD

**Issue by xjwang-cs** [torch/nn#1014]
Hi, 
I have updated my torch, nn, cutorch, and cunn package through  luarocks install. However, I still comes with the following issue:

/home/wangxiaojuan/torch/install/share/lua/5.1/nn/THNN.lua:109: wrong number of arguments for function call
stack traceback:
        [C]: in function 'v'
        /home/wangxiaojuan/torch/install/share/lua/5.1/nn/THNN.lua:109: in function 'Threshold_updateGradInput'
        ...angxiaojuan/torch/install/share/lua/5.1/nn/Threshold.lua:32: in function <...angxiaojuan/torch/install/share/lua/5.1/nn/Threshold.lua:30>
        [C]: in function 'xpcall'

**Comment by soumith** [comment]
I just tried nn.Threshold and did not reproduce this error. If you can give a small 10 line script to reproduce the issue, I can look further.
