### ISSUE TITLE
Sequential does not update outputs before using them to update the gradient.

### ISSUE THREAD

**Issue by csbrown** [torch/nn#1015]
Sequential needs the outputs for the input we are considering to compute the appropriate gradient.  It currently assumes that the last :forward call was for the same input as the current :backward call.

e.g. 
a = nn.Sequential()
a:add(nn.Cosine(4,4))
a:add(nn.Cosine(4,4))
ones = torch.Tensor(4):fill(1)
zeroes = torch.Tensor(4):fill(0)

a:forward(ones)
a:backward(ones, ones)
-0.1534
 0.2071
 0.2041
-0.2578
[torch.DoubleTensor of size 4]

a:forward(zeroes)
a:backward(ones, ones)
-3.3018e+23
 7.7537e+23
 1.1926e+24
 1.7514e+23
[torch.DoubleTensor of size 4]

Sequential should run a :forward call to get the appropriate outputs first.  This raises an issue of recursive Sequentials repeatedly calling :forwards.  Viz. we call :backward on a sequential... this runs a :forward call.  There is a Sequential in that Sequential, so when the :backward call hits that sub-Sequential, it also makes a :forward call.

Not sure how to solve this, but it seems like a problem...

**Comment by fmassa** [comment]
Hum, I didn't understand your problem, could you make it more clear where the issue is?
But in your second run you didn't pass the right input to the backward function.

**Comment by csbrown** [comment]
So :backward always operates under the assumption that there has been an immediately preceeding :forward call?  I was under the assumption that :backward was supposed to be deterministic on (input, gradOutput).

**Comment by fmassa** [comment]
No, the input needs to be the same during forwad and backward, see https://github.com/torch/nn/blob/master/doc/module.md#gradinput-backwardinput-gradoutput

**Comment by csbrown** [comment]
k my bad.  :)
