### ISSUE TITLE
SpatialSoftMax outputs 1's when evaluated on 3D tensor

### ISSUE THREAD

**Issue by vadimkantorov** [torch/nn#1016]
```lua
nn.SpatialSoftMax():forward(torch.Tensor(1, 2000, 20):uniform()):eq(1):all() --evaluates to true
```

Maybe it's wrong to evaluate it on a 3D-tensor, but producing an output equal to 1 is very strange. What's the reasoning behind it?

**Comment by soumith** [comment]
it's a single element distribution.

x_i / sum(x_i)

if i = 1
then you get 1

**Comment by soumith** [comment]
SpatialSoftMax does softmax over channels.

**Comment by vadimkantorov** [comment]
I see, 1 in this case is the number of channels. Thanks!
