### ISSUE TITLE
Add support for empty tensor in nn.Sum()

### ISSUE THREAD

**Issue by gheaeckkseqrz** [torch/nn#1017]
Hi,

OK, this may seems stupid, no one would try to compute the sum of an empty tensor.
But I ran into this situation where I'm creating a bunch of tensors automatically and Sum their elements, and of course I ended up with a few [torch.DoubleTensor with no dimension].

Some modules are OK with processing an empty tensor, would be nice to make the Sum one compatible as well. Making it return zero if the tensor is empty. 

At the moment, passing a [torch.DoubleTensor with no dimension] triggers the 
`assert(input:dim() >= dimension, "dimension exceeds input dimensions")`
Line 18 in [https://github.com/torch/nn/blob/master/Sum.lua](url)

Returning 0 on empty tensor is a pretty easy fix, I'm just not sure how to deal with the updateGradInput()

Best regards,
Pierre

**Comment by soumith** [comment]
i'm not sure if we want to implement this, because the implicit contract is a bit more dangerous than the explicit, and the user might not even be aware of a user-error / bug.
