### ISSUE TITLE
copy model to new type without overwriting original instance or cloning?

### ISSUE THREAD

**Issue by lebedov** [torch/nn#1021]
Is there a way to directly copy a model (e.g., `model = nn.Sequential()` with various layers subsequently added) with a specific type (e.g., `torch.CudaTensor`) to a new type (e.g., `torch.FloatTensor`) without overwriting the original model instance (which the `model:type()` method does) or cloning it before the type conversion (which can max out memory if the original model instance's tensors are in GPU memory and there isn't enough free memory for a clone)? In the latter scenario, it is cumbersome to have to convert the model to a non-GPU tensor type, clone it in host memory, and then convert it back to GPU memory if one wishes to keep a copy in GPU memory.

**Comment by fmassa** [comment]
I think [this line](https://github.com/facebook/fb.resnet.torch/blob/master/checkpoints.lua#L51) address your question, with the `deepCopy` function defined [just above](https://github.com/facebook/fb.resnet.torch/blob/master/checkpoints.lua#L11-L25)

**Comment by lebedov** [comment]
Yes - that's what I need. I posted a modified version that performs the desired type conversion during the copy [here](https://gist.github.com/lebedov/85fb05bec33b8ee7d1b2daa4a3e747e3) for anyone else who might need it. Thanks!
