### ISSUE TITLE
The THNN is cant not include to another project?

### ISSUE THREAD

**Issue by amazingyyc** [torch/nn#1023]
I see the document say: THNN is based on the same code, but is written in pure C, so it can be easily included in other code. SO it means the THNN can be include to any project that support c. I can not include it in my c project. I found that the THNN include some special head files like: THGenerateFloatTypes.h et. So if i want to use the THNN should i include another file in Torch?
And what should i do?

**Comment by soumith** [comment]
THNN depends on TH

Both are pure C libraries.

THNN: https://github.com/torch/nn/tree/master/lib/THNN
TH: https://github.com/torch/torch7/tree/master/lib/TH

**Comment by amazingyyc** [comment]
Thank u so much, I will try this

**Comment by amazingyyc** [comment]
I got a question: i include the TH file, But it seems got some problems.
Did i should #define the TH_GENERIC_FILE? if yes, what should i #define it?
I don't good at the Cmake so i can not make it work well. So can u give me some advice?
Thank u so much!

**Comment by soumith** [comment]
you can look at this repo for an example of building TH and THNN together and using them in C program: https://github.com/lantiga/scorch
