### ISSUE TITLE
Recent change broke the build on OSX

### ISSUE THREAD

**Issue by nicolasvasilache** [torch/nn#1026]
Did not track it down yet, should be easy to fix

/tmp/luarocks_nn-scm-1-5518/nn/lib/THNN/generic/Abs.c:20:3: error: use of undeclared identifier 'ptrdiff_t'
  THNN_CHECK_NELEMENT(input, gradOutput);

**Comment by soumith** [comment]
this happens if your torch is out of date.
luarocks install torch
luarocks install nn

that will fix it.
