### ISSUE TITLE
Misleading doc for TemporalConvolution.weight

### ISSUE THREAD

**Issue by weihuang0908** [torch/nn#1036]
According to the implementation, the documentation in TemporalConvolution.md
> The parameters of the convolution can be found in self.weight (Tensor of size outputFrameSize x **(inputFrameSize x kW)**) 

should be **(kW * inputFrameSize)**. 

>For a 2D input, the output value of the layer can be precisely described as:
>output[t][i] = bias[i]
>  \+ sum_j sum_{k=1}^kW **weight[i][j][k]**
>                                \* input[dW*(t-1)+k)][j]

should be **weight[i][k][j]**

**Comment by soumith** [comment]
If you send a pull request to fix it, I'll happily merge
