### ISSUE TITLE
Are there some methods equal to determined resize?

### ISSUE THREAD

**Issue by jimie208** [torch/nn#1067]
I notice that there is a important note under "resize" ,that resize is undetermined.
Does it mean that if a = torch.Tensor(2,3,4,5) then b = a:clone():resize(120) and then c = b:clone():resize(2,3,4,5), a[i][j][k][l] may not equal to c[i][j][k][l]?
And are there some methods make a determined resize?
Thank you vary much.

**Comment by jimie208** [comment]
How about 2 dim to 1 dim every time?
Such as (2,3,4,5,10)->(6,4,5,10)->(24,5,10)->(120,10)
and(120,10)->(24,5,10)->(6,4,5,10)->(2,3,4,5,10)?

**Comment by fmassa** [comment]
For those use cases, it's better to use `:view` or `:reshape`
