### ISSUE TITLE
Container:share does not return self

### ISSUE THREAD

**Issue by DavidGrangier** [torch/nn#1086]
Module:share returns self this is the expected behavior.
See 
https://github.com/torch/nn/blob/master/Container.lua#L99
https://github.com/torch/nn/blob/master/Module.lua#L102

**Comment by soumith** [comment]
thanks, this is fixed in https://github.com/torch/nn/commit/6f614794d0b6243183b199f89087115aac86aeec

I've checked the other functions for consistency as well, this seems to be the only anomaly.

**Comment by DavidGrangier** [comment]
super Soumith
thanks

-- David (from phone)

On Dec 30, 2016, at 3:47 PM, Soumith Chintala <notifications@github.com<mailto:notifications@github.com>> wrote:


thanks, this is fixed in 6f61479<https://github.com/torch/nn/commit/6f614794d0b6243183b199f89087115aac86aeec>

I've checked the other functions for consistency as well, this seems to be the only anomaly.

-
