### ISSUE TITLE
ParallelCriterion is increasing 

### ISSUE THREAD

**Issue by mhjabreel** [torch/nn#1088]
I have used ParallelCriterion with 2 Criteria but i noticed that it is always increasing.
the values under the red arrow in the attached image are the values of the first criterion where the values under the blue arrow are the vlues of the second. The values in the highlighted column are the values of the parallelcriterion.

![image](https://cloud.githubusercontent.com/assets/9088025/21576067/b9f136c0-cf23-11e6-8656-c5d33fb42438.png)

Thanks

**Comment by soumith** [comment]
without a way to reproduce this (a small script < 100 lines), we cannot really look into this further.
