### ISSUE TITLE
Sharing parameters breaks compatibility of the saved model with other Lua versions

### ISSUE THREAD

**Issue by guillaumekln** [torch/nn#1091]
Hi,

This was first reported at OpenNMT (see [this issue](https://github.com/OpenNMT/OpenNMT/issues/38)) where a user reported the same error as [this Torch issue](https://github.com/torch/torch7/issues/641). It turns out calling `share(mlp, ...)` stores a function as a new field, thus exposing it to serialization (see https://github.com/torch/nn/blob/master/Module.lua#L98-L99).

The following example is enough to reproduce the error:

1.

```lua
require('nn')

local a = nn.Linear(10, 100)
local b = nn.Linear(10, 100)

a:share(b, 'weight', 'bias', 'gradWeight', 'gradBias')

torch.save('test.t7', {a, b})
```

2. Change the Lua version (for example LuaJIT 2.1 to Lua 5.2 or the inverse)

3.

```lua
require('nn')

local model = torch.load('test.t7')
```

The code throws the error: `Failed to load function from bytecode`.

---

I think this could easily be avoided by setting a flag in `share(mlp, ...)` (for example `self.shared = true`) and make a dynamic dispatch in `accUpdateGradParameters`:

```lua
if self.shared then
   self:sharedAccUpdateGradParameters(input, gradOutput, lr)
else
   [...]
end
```

(I can make a PR if this approach is reasonable.)

**Comment by soumith** [comment]
that approach is reasonable, please do make a PR, thanks.
