### ISSUE TITLE
How does ResNet-18 convolution kernel move ?

### ISSUE THREAD

**Issue by xiestone1992** [torch/nn#1093]
Currently, I am studying the ResNet-18. I wonder how does Resnet-18 convolution kernel move?
First of all, the input size is 224x224. Then I found that the first layer of ResNet-18 is designed as:
`cudnn.SpatialConvolution(3 -> 64,  7x7,  2,2  3,3)`

so that the input will be  " 3+224+3 = 230 ", because the convolution kernel is 7x7 and the step is 2, then there will be 112convolutions ( (230 - 7) / 2 = 111 then ,111 + 1 = 112).

But there are still ' 1 ' column(   (230-7)/2=111 ... 1 ) !??

I use the following code to show the output size of layer 1, 
`print( model.modules[1].output:size() )`

Then the result is : 1x64x112x112

Then I tested what will happen if the input is 225?
(225 - 7)/2 = 112, then 112+1 = 113.
Then the output of first layer is 1x64x113x113

Here comes a odd issues.

I generate an input using the following codes:
`raw_input = torch.rand(1,3,225,225)`

Then I crop the left-top part of it:
`raw_input_lt = raw_input[{   {1},{},{1,224},{1,224}   }]`

Then I forward the "raw_input" and "raw_input_lt" to ResNet-18 and show the output of layer 1.
From  column 1 to 111 , result of "raw_input" and "raw_input_lt" are the same. But the column 112 in "raw_input_lt" is totally different from "raw_input", and there is one column 113 in "raw_input".
   
Now it confuses me. 

Why column 112 in "raw_input" and "raw_input_lt" are different? 
Why there is one more column 113 in "raw_input"  ?

Can anyone help me to solve this problem?

**Comment by xiestone1992** [comment]
@soumith maybe you can help me ? please?

**Comment by ClementPinard** [comment]
the difference between the tow column 112 comes from the fact that the padding (3) is greater than the stride (2) as a consequence, the last column will not be the only one to take values from the padding (so basically 0s), but in this case also the penultimate. as a consequence the penultimate column for `raw_input_lt` is not the same as the last  column for `raw_input` as the workground has some the 0 that were padding originally that are now values from the 225th input column.

you can try different kernal sizes to understand it : 
`SpatialConvolution(3 -> 64, 7x7, 2,2 3,3)` columns are all the same but the last
`SpatialConvolution(3 -> 64, 5x5, 2,2 2,2)` columns are all the same but the last
`SpatialConvolution(3 -> 64, 3x3, 2,2 1,1)` columns are all the same
`SpatialConvolution(3 -> 64, 9x9, 2,2 4,4)` columns are all the same but the last two

in general case :
`SpatialConvolution(3 -> 64, kWxkH, strideW,strideH (kW-1)/2,(kH-1)/2)` columns are all the same but the last `floor(((kW-1)/2)/strideW)`
note that it is (obviously) the same case for last rows and `kH` and `strideH`.

As to the fact that there is 113 columns and not 122 comes from the fact that the stride is not exactly dividing the number of rows and columns, but ti is just the step from a place to an other. when you have a stride of `strideW` and and a feature map of size `strideW*n + r` with `r` < `strideW` you can do n+1 steps, no matter what `r` is, as long as it is smaller than `strideW`

picture it with a stride of 2: you can do 2 steps with a feature map of length 4, but you can also do 2 steps if the feature map is only of length 3 (a step on (1,1), another on (3,1)). But with a feature map of length 5, you can 3 steps. this is exactly what is happening here. If you try pictures of size `223x223` you will get in then `112x112`feature maps, only if the the picture is smaller.
