### ISSUE TITLE
cmake: problem with THNN soversion

### ISSUE THREAD

**Issue by cdluminate** [torch/nn#1101]
As written in `lib/THNN/CMakeLists.txt`:
```
IF(THNN_SO_VERSION)
  MESSAGE(STATUS "THNN_SO_VERSION: ${THNN_SO_VERSION}")
  SET_TARGET_PROPERTIES(THNN PROPERTIES
    VERSION   ${THNN_SO_VERSION}
    SOVERSION ${THNN_SO_VERSION})
ENDIF(THNN_SO_VERSION)
```

When `THNN_SO_VERSION==0` then cmake considers it as FALSE, which is not expected.

**Comment by soumith** [comment]
the problem is not even that.
I can redo this as:

```
IF(DEFINED THNN_SO_VERSION)
...
```

but the problem as mentioned in the comment is that if I set the SOVERSION, I am hitting a fatal luarocks bug that I have no intention of finding the original reason for, or fixing it.
