### ISSUE TITLE
Feature requests: spatial adaptive average pooling

### ISSUE THREAD

**Issue by ruotianluo** [torch/nn#1102]
Is it fair to add a spatial adaptive average pooling, especially when there has been an adaptive max pooling?

**Comment by soumith** [comment]
yes, that would be great.

**Comment by ruotianluo** [comment]
#1103

**Comment by ruotianluo** [comment]
I modify the SpatialAdaptiveMaxPooling code to make it "average" and created the pull requests #1103 . The cuda version is not ready yet.

**Comment by soumith** [comment]
thanks for your contribution @ruotianluo
