### ISSUE TITLE
SpatialConvolution with fixed bias

### ISSUE THREAD

**Issue by blackecho** [torch/nn#1143]
Hi!
Is it possible to have a `SpatialConvolution` with fixed bias?
`SpatialConvolution.lua` has the method `noBias()` to set the bias to zero, is it possible to fix it to, say, one?

**Comment by nicholas-leonard** [comment]
There are a few ways to do this. The easiest is to reset the bias tensor to its fixed value after each parameter update.

**Comment by blackecho** [comment]
I didn't think about this simple solution, many thanks!
