### ISSUE TITLE
Batch prediction using parallel tables

### ISSUE THREAD

**Issue by varghesealex90** [torch/nn#1144]
Hi;

I would like to club use two pretrained networks as parallel paths and join their results and then make a decision or classification. I used the example given in parallel table section and it seems to work properly when I forward one data point at a time. I am interested to know if there is an option where in I could pass a batch to paralled table. I am attaching the screenshot of the code.

I would interested where in I could use the following code:
prediction= mlp2:forward(bunch) 
rather than using a for loop
![screen shot 2017-02-22 at 9 46 02 am](https://cloud.githubusercontent.com/assets/10129358/23197082/c1f72002-f8e3-11e6-8e3a-d310bd2f881a.png)

**Comment by achalddave** [comment]
Updating your `nn.Parallel` to operate on the 3rd dimension instead of 2nd, and concatenate over the 2nd dimension instead of the 1st should work:

`mlp = nn.Parallel(3, 2)`
