### ISSUE TITLE
Cloning and getParameter

### ISSUE THREAD

**Issue by alirezag** [torch/nn#1147]
When I clone a container (with no sharing) and call getParameter on the new copy something in both old and new copies break and I can't train them independently any more. Isn't clone creating a deep copy?

**Comment by achalddave** [comment]
This shouldn't happen; do you have a test script that shows this issue? The default `:clone()` function basically does the same thing as writing the model out to a file and reading it back from the file, which should completely keep the old and new models separate.

**Comment by alirezag** [comment]
you are right dave. i think i had a variable scoping problem. it is all good now. thanks. sorry i didnt close the ticket. i forgot i posted this here.
