### ISSUE TITLE
nn.SpatialMaxUnpooling shape error 

### ISSUE THREAD

**Issue by itironal** [torch/nn#1172]
Hello,

My code was working correctly in another machine but now I'm getting the following error:

/home/itir/torch/install/bin/luajit: /home/itir/.luarocks/share/lua/5.1/nn/Container.lua:67: 
In 13 module of nn.Sequential:
/home/itir/.luarocks/share/lua/5.1/nn/THNN.lua:110: indices and input shapes do not match: indices [1 x 24 x 32 x 32], input [24 x 32 x 32] at /tmp/luarocks_cunn-scm-1-2433/cunn/lib/THCUNN/generic/SpatialMaxUnpooling.cu:15
stack traceback:
	[C]: in function 'v'
	/home/itir/.luarocks/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialMaxUnpooling_updateOutput'
	.../itir/.luarocks/share/lua/5.1/nn/SpatialMaxUnpooling.lua:18: in function <.../itir/.luarocks/share/lua/5.1/nn/SpatialMaxUnpooling.lua:16>
	[C]: in function 'xpcall'
	/home/itir/.luarocks/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/itir/.luarocks/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	...e/itir/.luarocks/share/lua/5.1/nn/StochasticGradient.lua:35: in function 'train'
	...s/newdisk_fm_cv_train_generic_encoder-128_sym_norelu.lua:92: in main chunk
	[C]: in function 'dofile'
	...itir/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

I think it's caused by the version but although I upgraded nn and cunn, I still get the same error. I appreciate any suggestions to solve this issue.

Thanks in advance.

**Comment by eriche2016** [comment]
it says ```indices and input shapes do not match: indices [1 x 24 x 32 x 32], input [24 x 32 x 32]```.  you can fix your code to make them match.

**Comment by itironal** [comment]
You're right. The syntax of the function has changed. Now it works. Thank you.
