### ISSUE TITLE
Self created Criterion is null when called by generic function

### ISSUE THREAD

**Issue by marcel1991** [torch/nn#1210]
I created my own Criterion but when it calls input.THNN.MyCriterion_updateOutput(,,,) the function is null.
```
MyCriterion.lua:43: attempt to call field 'MyCriterion_updateOutput' (a nil value)
```

The code:
``` lua
function MyCriterion:updateOutput(input, target, spWeights)
 
  ...

   input.THNN.MyCriterion_updateOutput(
      input:cdata(),
      self.target:cdata(),
      self.output_tensor:cdata(),
      self.sizeAverage,
      THNN.optionalTensor(self.weights),
      THNN.optionalTensor(spWeights),
      self.total_weight_tensor:cdata()
   )
   self.output = self.output_tensor[1]
   return self.output, self.total_weight_tensor[1]
end
```

I added the generic declaration of the function to the string of the THNN_h.lua file. And I included the file in the init.lua file. Is there anything else I have to do to register a new criterion?

I should also add that I also wrote my own parent criterion because I need 3 inputs instead of two for the forward() and backward() functions.

**Comment by marcel1991** [comment]
Okay I found that everytime I do luarocks make rocks/* my THNN_h.lua file is overriden with the old version and my changes are not there anymore. Does anyone know why that happens? And how can I force to use my edited THNN_h.lua for the build?

**Comment by June01** [comment]
I also have the same problem, how to forbid the torch call the nn package in old version? how to compile the new nn source code? I have been trapped for almost two days, and i would appreciate very much is anyone could help me with that.
