### ISSUE TITLE
[Test failure] ./nn/test.lua:8285: module 'moses' not found:

### ISSUE THREAD

**Issue by cdluminate** [torch/nn#1219]
What is `moses`? Found nothing at https://github.com/torch/rocks

Caused package build failure: http://debomatic-amd64.debian.net/distribution#experimental/lua-torch-nn/0~20170521-g84b4350+dfsg-1/buildlog

**Comment by lauleehong** [comment]
I have the same issue doing a fresh install of torch, following the steps:
```
git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch; bash install-deps;
./install.sh
```

Missing dependencies for nn:
moses >= 1.0

tried luarocks install moses but doesnt work.

**Comment by omair-kg** [comment]
Same issue as @lauleehong . Any idea what is going on?

**Comment by Naruto-Sasuke** [comment]
@omair-kg @lauleehong  Sometimes,  beacuse of something known of network, using `./install.sh` cannot download moses, you need to download `moses` by hand. [Moses](https://github.com/Yonaba/Moses), then 
```bash
cd Moses;
luarocks makerockspec-1.x.y.rockspec
```
After installation, you can run `./install.sh`, it works fine when you cannot install something else.

**Comment by CDLuminate** [comment]
@Naruto-Sasuke Thank you.

**Comment by omair-kg** [comment]
@Naruto-Sasuke  Thank you.
