### ISSUE TITLE
ClassNLLCriterion - error in forward

### ISSUE THREAD

**Issue by yossibiton** [torch/nn#122]
When dealing with cuda ctitererion i get an error in ClassNLLCriterion whilr executing that line:
input.nn.ClassNLLCriterion_updateOutput(self, input, target)

The error is - 
/usr/local/bin/luajit: /usr/local/share/lua/5.1/nn/ClassNLLCriterion.lua:15: attempt to call field 'ClassNLLCriterion_updateOutput' (a nil value)

**Comment by eternaldensity** [comment]
As referenced above, I'm having a similar problem, but I'm not using CUDA so cutorch and cunn aren't relevant to whatever is causing it.

**Comment by fmassa** [comment]
@eternaldensity I'd advise you to update your packages (even though you said you updated them, the error message does not correspond to the latest version available) and see if there are no error messages while updating. Do
```
luarocks install torch
luarocks install nn
```

and try it again if therr are no errors.
