### ISSUE TITLE
How to find a module in a model exactly by the constructor of the module ?

### ISSUE THREAD

**Issue by Naruto-Sasuke** [torch/nn#1233]
For a easy code snippet:
```lua
require 'nn'
require 'torch'
require 'cunn'
require 'cutorch'

local net = nn.Sequential()
net:add(nn.SpatialConvolution(3,3,3,3))
net:add(nn.SpatialConvolution(3,3,3,3))
net:add(nn.SpatialConvolution(3,8,3,3))
net:add(nn.SpatialConvolution(8,16,3,3))


local function weights_init(m)
   local name = torch.type(m)
   print(name)
   if name:find('Convolution') then
      m.weight:normal(0.0, 0.02)
      m.bias:fill(0)
   end
end

net:apply(weights_init)
net:cuda()
print(net)
```
It ouputs:
```bash
nn.Sequential
nn.SpatialConvolution
nn.SpatialConvolution
nn.SpatialConvolution
nn.SpatialConvolution
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> output]
  (1): nn.SpatialConvolution(3 -> 3, 3x3)
  (2): nn.SpatialConvolution(3 -> 3, 3x3)
  (3): nn.SpatialConvolution(3 -> 8, 3x3)
  (4): nn.SpatialConvolution(8 -> 16, 3x3)
}
```
In the fuction `weights_init`, it init all conv layers making them obey Gaussian distribution. However, I want to init the weight of `nn.SpatialConvolution(3,8,3,3)`  to a different custom distirbution.  In spite of 
the fact that `nn.modules[3]` can work, it suffers from the man-made index.  How to get something like `nn.SpatialConvolution(3 -> 8, 3x3)` to specialize the layer?  This may be  a solution to the problem. Or is there another more elegant way?

**Comment by kmul00** [comment]
Hi,

This can be achieved using a combination of `nn.findModule()` and keeping a tab on the dimension of the weight vector. For example, 

```lua
conv_nodes = net:findModules('nn.SpatialConvolution')
```
will return a flattened list of all the `SpatialConvolution` layers in your model. 
Now performing a 
```lua
for i = 1, #conv_nodes do
  -- do something
end
```
will loop through each of your `SpatialConvolution` layers. Now since you want to access the particular `nn.SpatialConvolution(3,8,3,3)` layer, you can do so by checking the **weight** matrix of the associated layer.

Something like :

```lua
for i = 1, #conv_nodes do
    if conv_nodes[i].weight:size(1) == 8 then
        -- do somehting
    end
end
```

**Comment by Naruto-Sasuke** [comment]
@kmul00 It is a good way. Thank you!

**Comment by Naruto-Sasuke** [comment]
When I want re-initialize the weight of a specific layer, I cannot use this method. It seems that I have to use
man-made index ...

**Comment by kmul00** [comment]
Take a look at https://github.com/Kaixhin/nninit

You can use something like the following for layer-wise weight initialization 

```lua
conv_nodes[3]:init('weight', nninit.constant, 1)
```
