### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Six-wars** [torch/nn#1247]
How do you install nn from the terminal?

**Comment by RishabhMalviya** [comment]
First, [fork](https://help.github.com/articles/fork-a-repo/) this project. Then clone your fork on to your machine using:
`git clone https://github.com/<your-username>/nn.git`.

Then I think you're supposed to do `require(init.lua)` after that, but I may be wrong.

**Comment by RishabhMalviya** [comment]
Nope, then you're supposed to run `luarocks make` in the cloned repo on your machine.

**Comment by Six-wars** [comment]
I figured it out, thanks
