### ISSUE TITLE
What if I already have 'nn' installed (by the torch7 installation script)?

### ISSUE THREAD

**Issue by RishabhMalviya** [torch/nn#1248]
I want to start working on a feature soon, but there's a basic (naive) doubt I have.

I've already installed torch7 on my system (Ubuntu 16.04 LTS), following these instructions: [http://torch.ch/docs/getting-started.html](http://torch.ch/docs/getting-started.html). This also installed the nn package on my system (as a core package of torch7).

So, if I clone this repository onto my system and try to use the nn package from TREPL or an iTorch notebook, how do I ensure that I'm using functions compiled from this repository and not the one installed along with torch7?

Also, in case it is useful: 
Running `find ./ -name 'nn'` in my torch default installation directory (`~/torch`) gives the following:
```
./install/lib/luarocks/rocks/nn
./install/share/lua/5.1/nn
./.git/modules/extra/nn
./extra/nn
```

**Comment by albanD** [comment]
Hi,

If you use `luarocks make` inside `nn` with the luarocks from your torch install, it will replace your current nn installation.
What the install script is actually using the clone of nn located in `./extra/nn` and run `luarocks make` inside it.

**Comment by RishabhMalviya** [comment]
Awesome. That worked. And I learned stuff. Thanks.
