### ISSUE TITLE
:share() not working when sharing weight among 3 sub networks

### ISSUE THREAD

**Issue by abhishekarya286** [torch/nn#1261]
Actually, I need to share the weights among three sub networks.
This is a sample of a network with 3 subnets.
When I'm sharing weights between 2 subnets, it works fine but as soon as the third subnetworks is added, the number of parameters increases.
Please, look into this. 
require 'nn'
require 'nngraph'
--local CNN=require 'cnn_model.lua'

input={}
--table.insert(input,nn.Identity()())
input['lin']=nn.Linear(6,1)()       --subnet1 -layer1
input['lin2']=nn.Linear(1,6)(input['lin'])----subnet1 -layer2

input['sh_lin']=nn.Linear(6,1)()--subnet2 -layer1
input['sh_lin2']=nn.Linear(1,6)(input['sh_lin'])--subnet2 -layer2
--weight sharing between subnet1 and subnet2
input['lin'].data.module:share(input['sh_lin'].data.module, 'weight','bias','gradWeight','gradBias');
input['lin2'].data.module:share(input['sh_lin2'].data.module, 'weight','bias','gradWeight','gradBias');
---
m1=nn.gModule({input['lin'],input['sh_lin']},{input['lin2'],input['sh_lin2']})
p,g=m1:getParameters()
print(p:size(1))---prints 19 which is correct

--subnet3
input['sh2_lin']=nn.Linear(6,1)()
input['sh2_lin2']=nn.Linear(1,6)(input['sh2_lin'])
--weight sharing between subnet1 and subnet3
input['lin'].data.module:share(input['sh2_lin'].data.module, 'weight','bias','gradWeight','gradBias');
input['lin2'].data.module:share(input['sh2_lin2'].data.module, 'weight','bias','gradWeight','gradBias');

m1=nn.gModule({input['lin'],input['sh_lin'],input['sh2_lin']},{input['lin2'],input['sh_lin2'],input['sh2_lin2']})

p,g=m1:getParameters()
print(p:size(1))----prints 38 which is incorrect

**Comment by eriche2016** [comment]
you code is very unfriendly. if you want to share more than 2 modules, why do not try below:
```
encoder = nn.Sequential() 
encoder:add(nn.SpatialConvolution(1, 96, 11, 11, 4, 4))
encoder:add(nn.ReLU(true)) 

mv_share_net = nn.ParallelTable()
-- siamese style 
mv_share_net:add(encoder) 

for k = 1, 2 do 
    mv_share_net:add(encoder:clone('weight','bias', 'gradWeight','gradBias'))
end 

p1, pg1 = mv_share_net:getParameters()
```

**Comment by abhishekarya286** [comment]
Thanks @eriche2016 for your reply. It seems to be a better approach.
