### ISSUE TITLE
Volumetric Upsampling Modules Release Date

### ISSUE THREAD

**Issue by Dimimpel** [torch/nn#1262]
We’re looking to use volumetric upsampling in our network. Some files, e.g. VolumetricUpSamplingNearest.c have appeared in the torch repository last month, related it seems to a pytorch upsampling implementation. The python wrappers for these files were commited to pytorch too, but nothing for LUA here. I was wondering if LUA wrappers for these files are on the roadmap (and thus making them available when someone downloads Torch) and also roughly when is this going to happen in order to decide if it would be best for now to implement these ourselves ?

**Comment by soumith** [comment]
we have no plans yet of writing Lua wrappers. It's best for now to implement these yourselves.

**Comment by Dimimpel** [comment]
Thanks for the immediate answer, however when I tried to insert the wrapper myself, even if everything were compiled, the VolumetricUpSamplingNearest module didn't appear in Torch with the other nn modules.
Namely, I downloaded a Torch, installed the dependencies, inserted the wrapper (attached file),  wrote the following line in the init.lua file: require('nn.VolumetricUpSamplingNearest') and then executed the install.sh (./install.sh).
Everything were compiled but as you can see in the attached image when I entered torch and I typed
require('nn'); and then nn.(tab tab) the VolumetricUpSamplingNearest module wasn't displayed.

![screenshot from 2017-07-17 17-08-26](https://user-images.githubusercontent.com/9349855/28279431-5df3412e-6b18-11e7-9619-64ea8ba2b677.png)

[VolumetricUpSamplingNearest.zip](https://github.com/torch/nn/files/1153360/VolumetricUpSamplingNearest.zip)

**Comment by soumith** [comment]
you'll also have to modify init.lua

**Comment by Dimimpel** [comment]
As I said in the previous message
 **wrote the following line in the init.lua file: require('nn.VolumetricUpSamplingNearest')**
So it isn't that.

**Comment by mikepound** [comment]
Thanks Soumith, we've sorted this now - apparently was an luarocks caching issue. The wrapper works fine, if we add the necessary test and documentation is this something you'd be interested in merging? Alternatively we could probably combine both into an upsample layer much like exists in pytorch, with a mode parameter.

**Comment by soumith** [comment]
i'll merge either of the approaches you do. Thanks for writing the wrappers.

**Comment by soumith** [comment]
and in this context, if you have interest in porting your workflow to pytorch, and you have questions you'd want to ask, let me know.
