### ISSUE TITLE
Why is not nn.MSDCriterion() listed in https://github.com/torch/nn/blob/master/doc/criterion.md  ? 

### ISSUE THREAD

**Issue by NataliaDiaz** [torch/nn#1266]
Should a substitute be used instead?

**Comment by nicholas-leonard** [comment]
By MSD I assume you mean MSE. Still, can you be more specific about your questions?

**Comment by NataliaDiaz** [comment]
Sorry my mistake. I guess for distance among vectors I meant to use cosine distance. Thanks
