### ISSUE TITLE
torch.nn in context of a cuda stream

### ISSUE THREAD

**Issue by uriv** [torch/nn#1273]
The issue relates to pytorch and been moved to [https://discuss.pytorch.org/t/torch-nn-in-context-of-a-cuda-stream/6304](https://discuss.pytorch.org/t/torch-nn-in-context-of-a-cuda-stream/6304).
Thanks to @fmassa for pointing to the right forum.

**Comment by fmassa** [comment]
This is in the wrong repo (this is Lua Torch).
You should direct questions to https://discuss.pytorch.org/

**Comment by uriv** [comment]
> This is in the wrong repo (this is Lua Torch).
> You should direct questions to https://discuss.pytorch.org/

Thanks

**Comment by fmassa** [comment]
Could you close this issue?
