### ISSUE TITLE
nn.FeatureLPPooling has been already assigned a parent class

### ISSUE THREAD

**Issue by MikeChenfu** [torch/nn#1292]
Hello,
I reinstall torch today and install fbcunn on it, but I got following error.

`th> require 'fbcunn'
/home/siri/torch/install/share/lua/5.1/trepl/init.lua:389: /home/siri/torch/install/share/lua/5.1/torch/init.lua:102: class nn.FeatureLPPooling has been already assigned a parent class

stack traceback:
	/home/siri/torch/install/share/lua/5.1/fb/util/error.lua:76: in function </home/siri/torch/install/share/lua/5.1/fb/util/error.lua:72>
	[C]: in function 'error'
	/home/siri/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	[string "_RESULT={require 'fbcunn'}"]:1: in main chunk
	[C]: in function 'real_xpcall'
	/home/siri/torch/install/share/lua/5.1/fb/util/error.lua:85: in function 'xpcall'
	/home/siri/torch/install/share/lua/5.1/trepl/init.lua:661: in function 'repl'
	...uang/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
	[C]: at 0x00406670	`

Thanks for help.

**Comment by tastyminerals** [comment]
Search for `FeatureLPPooling.lua` and see where it occurres. Inspect the `init.lua` file in corresponding  package `nn` or `rnn`. Try commenting out the conflicting `require` method. This issue might be connected with the recent **Element-Research/rnn** and **torch/rnn** merge. 
Best fix could be just using the old code but this is of course not a long-term solution.
```
git clone https://github.com/Element-Research/rnn.git
cd rnn
luarocks make rocks/rnn-scm-1.rockspec
```

**Comment by MikeChenfu** [comment]
Thanks for the help. It works.
