### ISSUE TITLE
The getParameters() function cannot work with the module designed in the criterion part of document

### ISSUE THREAD

**Issue by hfxunlp** [torch/nn#1304]
I want to train the model shown in this part of the doc: 
https://github.com/torch/nn/blob/master/doc/criterion.md#nn.MarginRankingCriterion
with optim package, which need to call getParameters() method, and will lead to this break:
/usr/local/bin/luajit: /usr/local/share/lua/5.1/nn/Module.lua:327: check that you are sharing parameters and gradParameters

**Comment by albanD** [comment]
Hi,

The Criterions don't have learnable parameters, you don't want to call `getParameters()` on them.

**Comment by hfxunlp** [comment]
Sorry, but I mean the module trained by the criterion:
```
p1_mlp = nn.Linear(5, 2)
p2_mlp = p1_mlp:clone('weight', 'bias')

prl = nn.ParallelTable()
prl:add(p1_mlp)
prl:add(p2_mlp)

mlp1 = nn.Sequential()
mlp1:add(prl)
mlp1:add(nn.DotProduct())

mlp2 = mlp1:clone('weight', 'bias')

mlpa = nn.Sequential()
prla = nn.ParallelTable()
prla:add(mlp1)
prla:add(mlp2)
mlpa:add(prla)
```

**Comment by albanD** [comment]
Does using `clone('weight', 'bias', 'gradWeight', 'gradBias')` in both places solves the issue?

**Comment by hfxunlp** [comment]
Yes, it has been solved by doing so. Thank you @albanD
