### ISSUE TITLE
fbcunn -> cunn/nn

### ISSUE THREAD

**Issue by nicholas-leonard** [torch/nn#148]
I am thinking we should move some stuff from fbcunn to cunn/nn. We could add doc, unit tests, C code, etc. What are your thoughts?

**Comment by clementfarabet** [comment]
:+1: there's a bunch of things that would be nice to have here to avoid all the additional dependencies.

**Comment by soumith** [comment]
I think that is reasonable. We have already gotten clearances for this.
I think the most useful ones are nn.DataParallel and nn.ModelParallel to begin with
For this, I would like some of you to review the https://github.com/torch/nn/tree/getParamsByDevice branch and see if it looks acceptable.

**Comment by nicholas-leonard** [comment]
I was looking to move the LookupTableGPU to nn/cunn, but it seems that they are heavily dependent on [fbcuda](https://github.com/facebook/fbcuda). fbcuda also contains lots of nice stuff that cutorch could easily use. I am thinking we could make fbcuda a cutorch or cunn dependency. As in fbcunn, we could just link it directly into the cutorch or cunn repo via some git magic. What is your take on all this?

**Comment by soumith** [comment]
fbcuda fully wont be a dependency for cutorch directly (for a variety of reasons that are not just technical). we are working on an interim solution to be able to use the sorting kernels etc.

**Comment by nicholas-leonard** [comment]
What reasons? And what interim solution? Again my objective is to make it easy to migrate code from fbcunn to nn/cunn. But the codes reliance on fbcuda is a problem. Could we not make fbcuda a dependency of cunn the same way it is a dependency of fbcunn? i.e. git include.

**Comment by andresy** [comment]
It looks to me the getParamsByDevice is too gpu-specific to be accepted in the main nn. This adds a level of complexity which is annoying. There is nothing that avoids cunn to override something in Module btw.

**Comment by andresy** [comment]
There is no way that cunn will depend on a company-specific package: that might be annoying for some other companies ;) Also, fbcunn depends on too many things.

**Comment by clementfarabet** [comment]
I agree, way too many deps. 






On Mon, Feb 9, 2015 at 5:02 PM -0800, "Ronan Collobert" <notifications@github.com> wrote:












There is no way that cunn will depend on a company-specific package: that might be annoying for some other companies ;) Also, fbcunn depends on too many things.

**Comment by nicholas-leonard** [comment]
Ok, so no dependencies. That option being ruled out, I think we are left with only one "viable" option if we want to move stuff from fbcunn -> cunn/nn. We will need to consolidate (copy-paste, change namespace, preserve licences) code from fbcuda (not to be confused with fbcunn) to either cutorch or cunn. Then we can start moving fbcunn stuff over to cunn/nn. 

fbcuda is just a header library of c++ templates. A little like Thrust.

I don't see any way around this copy-pasting. Otherwise, we can forget moving fbcunn stuff to cunn/nn, it would be too much work to remove all that c++ code and make it independent of fbcuda.

In any case, I would hate to see all that nice code remain detached from the core of torch. Furthermore, I really want to use this stuff, but I hate the dependencies (fb* stuff).

So what is the verdict?

**Comment by nicholas-leonard** [comment]
Nobody cares.

**Comment by soumith** [comment]
progress is happening. working on getting the thrust-like parts of fbcuda (made THC branded) into cunn. should land soon.

**Comment by nicholas-leonard** [comment]
Nice!

Nicholas Léonard
450-210-1214
