### ISSUE TITLE
;

### ISSUE THREAD

**Issue by ibmua** [torch/nn#152]
Looks like someone put spare ;s in the docs.. Lots of them.

**Comment by nicholas-leonard** [comment]
Do you have a link?

**Comment by ibmua** [comment]
Sure.

https://github.com/torch/nn/blob/master/doc/containers.md#nn.Containers
https://github.com/torch/nn/blob/master/doc/module.md#nn.Module
at least. It may be present in many others also. You should probably search files for ; if you want to locate all of them.

**Comment by nicholas-leonard** [comment]
Ah you mean in the code? It is still valid Lua. But yeah, it could be removed in a PR as these are redundant.

**Comment by ibmua** [comment]
Yes, exactly.
