### ISSUE TITLE
Preserve sharing semantics when typecasting a network [for example to :cuda()]

### ISSUE THREAD

**Issue by soumith** [torch/nn#187]
Currently, if one creates a network (say a siamese network) where some modules in the network share weights with one another, then once the network is typed to another type like :cuda or :float, then the sharing is untied.

Not only is this confusing, but also undocumented.

It is also fixable pretty simply.

I will prepare a patch for this.

**Comment by jonathantompson** [comment]
Nice! I've always had to rebuild them from scratch.

**Comment by nicholas-leonard** [comment]
Plus one for this. I currently need it.

**Comment by soumith** [comment]
added documentation: https://github.com/torch/nn/commit/de9418dada8a837c231c267a3ce9273f36072170

**Comment by nicholas-leonard** [comment]
I am working on an actual implementation that fixes this.

**Comment by nicholas-leonard** [comment]
https://github.com/nicholas-leonard/rnn/blob/master/Module.lua#L76

**Comment by soumith** [comment]
that looks pretty good to me, can you do a PR for nn, to have it be the default behavior of :type()

**Comment by nicholas-leonard** [comment]
Yeah I can PR. Only issue with making default is all the modules that overload type. They won't pass around the castmap. For example, see Euclidean.

**Comment by AjayTalati** [comment]
nicholas-leonard , soumith this sounds cool :+1:  - will it be easy to understand, for fools like me?

I'm still trying to understand this, [ model_utils.clone_many_times(net, T) ](https://github.com/AjayTalati/practical6/blob/master/model_utils.lua) ? 

Are there are easy papers or reviews of this? I should understand this code, but I don't?

**Comment by Atcold** [comment]
Cool, just tumbled into this same problem. In my case the untieing is caused by issuing `:getParameters()` in order to feed `optim`.

**Comment by dominikgrewe** [comment]
Could we have a multi-pass solution that works with custom implementations of `type`?

1) Traverse modules to look for shared storages.
2) Do the things `type` currently does.
3) If storage sharing was detected in step 1, restore it.

Steps 1 and 3 would only be run on the top-level module. `type` could do this automatically by setting a flag that says whether the current module is the top-level module or not.
The only complication would be that container modules with a custom type method would have to re-implement this logic. Wdyt?

**Comment by nicholas-leonard** [comment]
@dominikgrewe This is how I do it at the moment : https://github.com/nicholas-leonard/dpnn/blob/master/Module.lua#L100

**Comment by Atcold** [comment]
Actually, issuing `:getParameters()` dis-attaches *external sharing* while preserving *in-model sharing* of parameters. It has been *lovely* discovering this :sob:

**Comment by Atcold** [comment]
Update: I'm not sure if I should open another issue, but now I've noticed that, after issuing `:getParameters()`, only the obtained parameters are trained and the model (the network) keeps old stuff in it. Saving the network, therefore, saves just the weight initialised to whatever happen before epoch 1.

I'm not sure if I made sense. I just know this is driving me crazy.

**Comment by dominikgrewe** [comment]
@Atcold The tensors returned by `getParameters()` should share values with the modules in the network. If you have a case where that's not true, I suggest opening a new issue and providing an example that reproduces the issue.

**Comment by Atcold** [comment]
@dominikgrewe, I'm talking about `net2 = net1:clone('weight', 'bias', 'gradWeight', 'gradBias')`. After `net1:getParameters()` `net2` gets disconnected. Nevertheless, sharing within `net1` are preserved.
Are you suggesting to open a new issue reporting this exact problem?

**Comment by dominikgrewe** [comment]
I see. So `getParameters` can preserve weight sharing as long as the shared modules are in the same network. In your example, if `net1` and `net2` were sub-modules of a another module `net3`, then calling `net3:getParameters()` would preserve the shared weights.
If two modules with shared weights are part of separate networks it is impossible to preserve the weight sharing when calling `getParameters` (at least in general), because `getParameters` returns a flat, continuous tensor containing all weights of the network. So, apart from some special cases, modules in separate networks cannot share weights when `getParameters` is called.

The problem described in this bug is related, but different. It's about modules _in the same network_ sharing weights.

**Comment by Atcold** [comment]
OK, tnx @dominikgrewe, so I guess nothing can be done regarding my specific problem of inter-network parameter sharing. OK, no big deal.

**Comment by adamlerer** [comment]
Typecasting a network now preserves tensor sharing semantics within a network (https://github.com/torch/nn/pull/303). @soumith, can this be closed now?
