### ISSUE TITLE
View is broken

### ISSUE THREAD

**Issue by szagoruyko** [torch/nn#193]
commit b94b4576353eeb1ee2421e55c5a31e6c3a1f9dc0 has broken View, ```nn.View(-1):setNumInputDims(3)``` does not work any more, gives an error out of range on https://github.com/torch/nn/blob/master/View.lua#L33 on forward
Thus loadcaffe and backward compatibility are broken.

**Comment by soumith** [comment]
okay patches coming ASAP. thanks for the report. 
Our users wont notice this as they are slightly behind (because of torch-distro).

Thanks for the report. I am estimating patch in 1 hour or less.

**Comment by szagoruyko** [comment]
Thanks for the quick fix!
