### ISSUE TITLE
SpatialFullConvolutionMap does weird things

### ISSUE THREAD

**Issue by Atcold** [torch/nn#210]
Below, `SpatialConvolutionMap` is reported for comparison.
```lua
th> SFC = nn.SpatialFullConvolutionMap(nn.tables.oneToOne(3), 5, 5)                                                                    
                                                                      [0.0005s]
th> SC = nn.SpatialConvolutionMap(nn.tables.oneToOne(3), 5, 5)                                                                         
                                                                      [0.0004s]
th> #SFC:forward(torch.Tensor(3,20,20))                                                                                                

  3
 24
 24
[torch.LongStorage of size 3]

                                                                      [0.0003s]
th> #SC:forward(torch.Tensor(3,20,20))                                                                                                 

  3
 16
 16
[torch.LongStorage of size 3]
```
Shouldn't the first be `3x20x20` instead?
```lua

                                                                      [0.0003s]
th> SFCS = nn.SpatialFullConvolutionMap(nn.tables.oneToOne(3), 5, 5, 4, 4)                                                             
                                                                      [0.0004s]
th> SCS = nn.SpatialConvolutionMap(nn.tables.oneToOne(3), 5, 5, 4, 4)                                                                  
                                                                      [0.0003s]
th> #SFCS:forward(torch.Tensor(3,20,20))                                                                                               

  3
 81
 81
[torch.LongStorage of size 3]

                                                                      [0.0005s]
th> #SCS:forward(torch.Tensor(3,20,20))                                                                                                

 3
 4
 4
[torch.LongStorage of size 3]

                                                                      [0.0003s]
```
What is `81x81`?

**Comment by koraykv** [comment]
I didn't understand why you think it does weird things. It applies 'full' convolution, not 'same' (to speak matlab lingo).

The first is 24x24 since it is full convolution. When you convolve 24x24 with kernel of size 5x5 you get 20x20, that is why. The same calculation is true for your second example, since you have strides.

**Comment by ssakhavi** [comment]
@koraykv , for the second one, Do you mean that adding strides for a Full Convolution operation results in a circular convolution? (I don't think so)

Also if you replicate what @Atcold did and look at the contents of the matrix, some of the number are off the charts! (for example, 7.1431e+186!)

**Comment by soumith** [comment]
@ssakhavi if you look at what @Atcold did, he is sending in uninitialized memory (torch.Tensor(3,20,20) is initialized to random memory). If he sends in something sane as input, you will get something sane as output.

**Comment by ssakhavi** [comment]
But I also didn't also understand the `81x81` as well, @soumith.

Or more generally: What is the definition of a full convolution operation when strides are introduced?

**Comment by soumith** [comment]
@ssakhavi I also was not sure until now, but the code was only 18 lines, so I went ahead and read it: https://github.com/torch/torch7/blob/master/lib/TH/generic/THTensorConv.c#L178
Looks like it is taking 2D outer product.

**Comment by Atcold** [comment]
I have some troubles understanding what's going on for the second case.
In [SpatialFullConvolutionMap.lua](https://github.com/torch/nn/blob/master/SpatialFullConvolutionMap.lua) there is no definition of `output`.
In [SpatialFullConvolutionMap.c+58](https://github.com/torch/nn/blob/master/generic/SpatialFullConvolutionMap.c#L58) I get the size of `output` which has never been defined.
I am missing a point, *i.e.* where the `output` dimension is computed.

**Comment by soumith** [comment]
Right here: https://github.com/torch/nn/blob/master/generic/SpatialFullConvolutionMap.c#L40

**Comment by Atcold** [comment]
`* dh` and `* dw`??? Shouldn't it be `/ dh` and `/ dw`???

**Comment by soumith** [comment]
@Atcold first step, read on what a full convolution is. 
http://www.mathworks.com/help/matlab/ref/conv.html

**Comment by Atcold** [comment]
Yes, I know what it is. It is not clear to me what it should happen when a stride is involved.

**Comment by ssakhavi** [comment]
I have the same problem Alfredo

**Comment by koraykv** [comment]
I think the easiest way to think about full convolution layer is to assume that it will always be the inverse of valid convolution. For example, 

81x81 input, valid convolution by 5x5 kernel with stride 4x4 will give output 20x20.
Therefore, 
20x20 input, full convolution by 5x5 kernel with stride 4x4 will give output 81x81.

I hope it is clear now. It just applies the kernel at every input pixel, but accumulates with stride on the output, opposite of what valid convolution dies.

**Comment by Atcold** [comment]
@koraykv, it's clear now. Should we document this (since it's a bit tricky) or it's something no one is going to ever use?

**Comment by koraykv** [comment]
sure, that would be great

**Comment by Atcold** [comment]
Alright.
