### ISSUE TITLE
nn.View behaviour has changed 

### ISSUE THREAD

**Issue by fmassa** [torch/nn#219]
@Atcold has noted that his old models didn't work anymore when the batch size is equal to 1, the batch dimension being squeezed out.
Since commits https://github.com/torch/nn/commit/b94b4576353eeb1ee2421e55c5a31e6c3a1f9dc0 and https://github.com/torch/nn/commit/6b0a15f3f3f811f483ecd07e91d2f89a01bf4d6d the behaviour of View has changed when the batch size is equal to 1 and the user does not specify the number of input dimensions. 

For exemple

```lua
require 'nn'

m = nn.View(18)
m:forward(torch.rand(1,2,3,3))
```
outputs a tensor of size `18`, not considering the batch dimension as was done before those commits. On the other hand, if the user set 

```lua
require 'nn'
m = nn.View(18):setNumInputDims(3)
m:forward(torch.rand(1,2,3,3))
```
which gives as output a `1x18` tensor, as expected.

I don't think the current behaviour to be a problem, but it is indeed not backward compatible in the case of a batch size of 1. Do you think it should be changed to make it consistent with previous View ?

**Comment by Atcold** [comment]
Oh, I was not aware of
```lua
m = nn.View(18):setNumInputDims(3)
```
The problem is that with `batchSize` as a parameter, the output changes `dim()` for the case `1` and `> 1`.

**Comment by andresy** [comment]
@fmassa , I my opinion the new way is the most consistent. setNumInputDims is supposed to be there when one really wants to specify a batch dimension. In that respect, the old way is unexpected: it assumes a batch were no one was talking about a batch.

**Comment by soumith** [comment]
Agreed, previous behavior was buggy in that aspect. If more people have an issue with the backward-compatibleness I can do a fix, but I believe it'll be a very teeny tiny subset of people that might run into it.

**Comment by Atcold** [comment]
Well, for compatibility, the `loss()` should then still be able to accept *Tensor* targets, even though the `prediction:dim()` is `1` (perhaps performing a `squeeze()`). Now choosing the batch size equal to `1` does break code. Before it was working.

**Comment by soumith** [comment]
i have a patch incoming for the loss.

**Comment by Atcold** [comment]
OK than, that works for me.
