### ISSUE TITLE
Problem with nn.View since last pull

### ISSUE THREAD

**Issue by MichaelMathieu** [torch/nn#221]
Hi,

Since the last pull (of nn and torch), I'm unable to use -1 arguments in nn.View in most situations. For instance, the following code fails:

require 'nn'
a = nn.View(-1, 2)
 x = torch.randn(4)
a:forward(x)

with the following error

.../mathieu/torch_sc/install/share/lua/5.1/torch/Tensor.lua:455: Wrong size for view. Input size: 4. Output size: -2x-1x2
stack traceback:
	[C]: in function 'error'
	.../mathieu/torch_sc/install/share/lua/5.1/torch/Tensor.lua:455: in function 'view'
	/home/mathieu/torch_sc/install/share/lua/5.1/nn/View.lua:72: in function 'forward'
	[string "a:forward(x)"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/mathieu/torch_sc/install/share/lua/5.1/trepl/init.lua:588: in function 'repl'
	...u/torch_sc/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00405910	

x:view(-1, 2) works well, though.

**Comment by andresy** [comment]
-1 means vector, what are you trying to do here?

**Comment by MichaelMathieu** [comment]
As far as I know, -1 means the total number of elements over the product of the other dimensions passed as arguments of view. According to the documentation of view (for tensors, not the module) : "If one of the dimensions is -1, the size of that dimension is inferred from the rest of the elements." . This used to be the behavior of nn.View too and it is the case in the example in the documentation. I'm not sure what "vector" means in this case.

**Comment by soumith** [comment]
@MichaelMathieu is correct. And I noticed that even with :setNumInputDims, it still does not behave correctly.

**Comment by nicholas-leonard** [comment]
Is this the culprit? 
https://github.com/torch/nn/blob/master/View.lua#L12
In any case, it should use absolute value of sizes.

**Comment by andresy** [comment]
i will see that in more details. in the meantime, you can use View(2) for your use case.

**Comment by andresy** [comment]
note also the line you point out is in fact code from the previous view. it is because of this that i did not see the -1 case at first when i added a feature. also, setNumInputDims() and -1 do not go well together.

**Comment by soumith** [comment]
hopefully with this commit, this issue is closed: https://github.com/torch/nn/commit/0063dbdefd77182c9235315d5574caf7bbf25147
