### ISSUE TITLE
In Module:getParameters(), flatten(parameters) produces errors for an non-contiguous table as [parameters]

### ISSUE THREAD

**Issue by hujiewang** [torch/nn#223]
I encountered this error while testing SoftMaxTree 
Shouldn't we use
```
for key,value in pairs(parameters) do
```
instead of 
```
for k = 1,#parameters do
```
for better flexibility?

**Comment by nicholas-leonard** [comment]
SoftMaxTree is in nnx. Can you open your issue there? Thanks.
