### ISSUE TITLE
Removing a layer to specialize an autoencoder

### ISSUE THREAD

**Issue by daviddoria** [torch/nn#224]
I am trying to specialize an autoencoder. Is there a way to delete layers from the encoder to then attach the specialization layers in their place? Or do I have to copy the weights out of the encoder into a new model and then add layers onto the new model? 

Does anyone have an example of doing this?

Thanks,

David

**Comment by soumith** [comment]
if your model is called "model", then look at the table:
model.modules

It is a regular lua table that you can manipulate. you can rewrite the module entries in there with your new modules.
