### ISSUE TITLE
Change in model:forward output dimension while batch size is 1

### ISSUE THREAD

**Issue by rudrapoudel** [torch/nn#227]
Hi guys,

Previously, I used to get  output of 1xNum-of-classes dimension with model:forward while I use to have batch-size = 1. However, after current updates I use to get output of only Num-of-classes dimension with batch-size = 1. Just want to make sure that if this is what we want or it's un-welcomed change.

Code to reproduce above behaviour- https://github.com/rudrapoudel/hello_ml/blob/master/dnn/dnn.lua (outputs variable at line 161, num-of-classes is 6 here). You can execute like this,

```
th dnn.lua -batch_size 1
th dnn.lua -batch_size 2
```

**Comment by nicholas-leonard** [comment]
Instead of `model:add(nn.View(features_out))`, try `model:add(nn.Reshape(features_out, true))`.

**Comment by rudrapoudel** [comment]
Thanks, solved!
