### ISSUE TITLE
SpatialConvolutionMM doesn't pass unit tests

### ISSUE THREAD

**Issue by fmassa** [torch/nn#237]
Since commit c0c79f1d542cc94a8ac3fffdca828c16ca57587b, `nn.test()` segfaults at `SpatialConvolutionMM`.

**Comment by andresy** [comment]
it is certainly because you did not update torch7 core

**Comment by fmassa** [comment]
Precisely, I was using the current torch installation from distro, which doesn't contain the newest commits from torch7. Sorry about the false alarm.

**Comment by andresy** [comment]
arg, maybe @soumith could update it when he finds some time (in his already overbooked schedule)?

**Comment by fmassa** [comment]
It's actually my fault, I only updated the nn repo on top of distro installation.

**Comment by soumith** [comment]
hmm, torch/distro does have the atomic commits now. I updated 3 days ago.

**Comment by fmassa** [comment]
But you didn't update the torch package
https://github.com/torch/distro/commit/bdce3fc75b06a7e5e688494c24f37371bbb137d6

**Comment by soumith** [comment]
good catch, updating. thanks.
