### ISSUE TITLE
type conversion of nn.L1HingeEmbeddingCriterion() to cuda

### ISSUE THREAD

**Issue by lelikchern** [torch/nn#246]
When L1HingeEmbeddingCriterion is transformed into cuda, its interior parameters do not change type from FloatTensor to CudaTensor. 

Example:

th> criterion = nn.L1HingeEmbeddingCriterion()
th> criterion.gradInput
{
  1 : FloatTensor - empty
  2 : FloatTensor - empty
}
th> criterion = criterion:cuda()
th> criterion.gradInput
{
  1 : FloatTensor - empty
  2 : FloatTensor - empty
}

This behavior forbids the correct functioning of criterion:backward for CudaTensors, because it results in an error:
...h/install/share/lua/5.1/nn/L1HingeEmbeddingCriterion.lua:26: bad argument #1 to 'resizeAs' (torch.FloatTensor expected, got torch.CudaTensor)

I think this has something to do with the way that this criterion is constructed, and that it has in fact two gradInputs.

**Comment by soumith** [comment]
Fixed in trunk via: https://github.com/torch/nn/commit/cedc0b997fe39751726632622f52ccc547e85395
