### ISSUE TITLE
MarginRankingCriterion does not change type when casted to Cuda

### ISSUE THREAD

**Issue by lelikchern** [torch/nn#247]
When MarginRankingCriterion is transformed into cuda, its interior parameters do not change type from Float/DoubleTensor to CudaTensor. Could be quickly fixed by providing a type function:

function MarginRankingCriterion:type(type)
   self.gradInput[1] = self.gradInput[1]:type(type)
   self.gradInput[2] = self.gradInput[2]:type(type)
   return parent.type(self, type)
end

(Sorry, can't fix it myself right now)

**Comment by dominikgrewe** [comment]
Isn't the underlying problem that `nn.Criterion:type()` overwrites `nn.Module:type()`? https://github.com/torch/nn/blob/master/Criterion.lua#L31
It should, like `nn.Module`, also be recursive. In fact, is there any reason to overwrite `nn.Module:type()` at all?

**Comment by soumith** [comment]
nn.Criterion does not derive from nn.Module.
A recursive type is probably the best solution. I did not have time to look into doing that.

**Comment by dominikgrewe** [comment]
Good point :) I'm happy to fix it. Should be straightforward given `nn.Module:type()`.

Related question: Do you know why in `recursiveType` (https://github.com/torch/nn/blob/master/Module.lua#L118) we only iterate over the numeric indices? So if you have a nested table, some tensors may not get converted. Maybe to deal with loops in modules?

**Comment by soumith** [comment]
no reason why we do it that way, but i haven't seen a module that has keys that are non-numeric. would be good to fix that to be safe for the future as well.
