### ISSUE TITLE
Module method for custom parameters initialization

### ISSUE THREAD

**Issue by pjkirsch** [torch/nn#255]
Hi!

Do you think that an additionnal method for custom parameters initialization would be relevant for modules such as "nn.Linear" or "nn.SpatialConvolution"?
I noticed that weights and bias are initialized using an uniform(-r,r) distribution by default. However, this is sometimes not the best choice. 
A dedicated method, taking a custom initialization function as input, would be cleaner than directly manipulating the "module.weight" tensor.

**Comment by hohoCode** [comment]
The e-lab from Puedue univ has done that in their torch-toolbox repo, I think you can check this out and use it (though it is not integrated into the nn): 
https://github.com/e-lab/torch-toolbox/tree/master/Weight-init

**Comment by pjkirsch** [comment]
Nice!
Thanks hohoCode, that's exactly what I was looking for.
