### ISSUE TITLE
CrossEntropyCriterion broken

### ISSUE THREAD

**Issue by andresy** [torch/nn#257]
Guys,

You broke CrossEntropyCriterion (which had a specific type()) with #250 
Could you put it back?

Thanks

**Comment by soumith** [comment]
Sorry about that. fixed in https://github.com/torch/nn/commit/e5556492d5efd97cb30a13dab214487a7bc1a6b8

**Comment by andresy** [comment]
thanks :sweat_smile:

**Comment by dominikgrewe** [comment]
Sorry about that. Was the problem that `type` wasn't called correctly on `self.lsm` and `self.nll`? If so, this should be fixed by #259
