### ISSUE TITLE
table.unpack

### ISSUE THREAD

**Issue by nicholas-leonard** [torch/nn#263]
Where is torch supposed to get table.unpack? I get this error : 
```lua
usr/local/bin/luajit: /usr/local/share/lua/5.1/nn/View.lua:77: attempt to call field 'unpack' (a nil value)
stack traceback:
```

I know it was added for compatibility with lua 5.2. Tried reinstalling trepl, xlua and torch, still no table.unpack.

**Comment by andresy** [comment]
maybe a typo was introduced (torch.unpack instead in table.unpack?)

**Comment by nicholas-leonard** [comment]
No that was my comment typo. The problem is that table.unpack is compatible with luajit (at least not mine).
