### ISSUE TITLE
Bug in SpatialConvolution:tostring()

### ISSUE THREAD

**Issue by szagoruyko** [torch/nn#279]
Not happy with this PR https://github.com/torch/nn/pull/276 again: 
```
SpatialConvolution.lua:130: attempt to concatenate field 'padding' (a nil value)
```
fails if padding is nil (in cudnn for example saved models could have no padding)

**Comment by fmassa** [comment]
A quick fix would be to replace in line https://github.com/torch/nn/blob/master/SpatialConvolution.lua#L129
```lua
if self.padding ~= 0 then
```
by
```lua
if self.padding and self.padding ~= 0 then
```
This problem only arises in old models though, saved before the aliasing of `nn.SpatialConvolution` to point to `nn.SpatialConvolutionMM`.
