### ISSUE TITLE
gradWeight and gradBias in constructor

### ISSUE THREAD

**Issue by mys007** [torch/nn#304]
Is there any reason for gradWeight and gradBias being fully allocated in constructor and not in updateGradInput (in cunn, cudnn, ccn2)? In my eyes, this has two disadvantages: 1) they can't be shaved off in model sanitization when saving a model (since they wouldn't be automatically recreated), 2) they use up GPU memory even when the model is used just for forward pass.

**Comment by soumith** [comment]
yes. they are initialized there to enable 

- sharing of parameters across the model
- getParameters flattening of parameters

regardless of if you did a forward+backward on the module yet.

**Comment by mys007** [comment]
Sometimes I'm ashamed of myself. Thanks.
