### ISSUE TITLE
SpatialBatchNormalization should zero gradWeight and gradBias

### ISSUE THREAD

**Issue by wickedfoo** [torch/nn#318]
self.gradWeight = torch.Tensor(nFeature)
  self.gradBias = torch.Tensor(nFeature)

in the initialization are missing :zero().

These can potentially contain garbage (especially CUDA):

> torch.setdefaulttensortype('torch.CudaTensor')
nil
                                                                      [0.0003s]
> m = nn.SpatialBatchNormalization(4)
                                                                      [0.0008s]
> m.gradWeight
-3.4463e-05
 1.1117e-33
 5.2345e+09
 2.8369e+22
[torch.CudaTensor of size 4]

                                                                      [0.0004s]
> m.gradBias
-8.0240e-15
 1.0144e-33
 4.7025e-34
 4.3615e+35
[torch.CudaTensor of size 4]

**Comment by soumith** [comment]
one is expected to call :zeroGradParameters on the model before calling :backward

**Comment by soumith** [comment]
https://github.com/torch/nn/blob/master/doc/module.md#zerogradparameters
