### ISSUE TITLE
LookupTable broke backward compat??

### ISSUE THREAD

**Issue by clementfarabet** [torch/nn#319]
This commit https://github.com/torch/nn/commit/9716078afcc5023e28f39ab0020e66ed4208abb4 killed previously trained modules. Was that intended? We've usually been pretty good at maintaining backward compatibility.

**Comment by clementfarabet** [comment]
So anybody in this situation? What procedure do you follow to upgrade a module like this?

**Comment by soumith** [comment]
if this broke backward compatibility, this is definitely unintentional. We could patch it quickly to restore backward compat. Do you have a small test (expected vs actual) that we can use?

**Comment by soumith** [comment]
cc: @colesbury

**Comment by soumith** [comment]
I think I've identified the issues. some temporary buffers are initialized in the constructor, making them lazy-initialized will fix all issues. Will prepare a patch for this now.

**Comment by clementfarabet** [comment]
self._count = torch.IntTensor()
self._input = torch.LongTensor()

These two buffers didn't exist before and are not created lazily.

**Comment by clementfarabet** [comment]
Great, thanks!
