### ISSUE TITLE
CAddTable has the same bug that JoinTable did

### ISSUE THREAD

**Issue by shawnjhenry** [torch/nn#332]
Hi,

A while ago I noticed a bug in JoinTable here: https://github.com/torch/nn/issues/321.  It appears that CAddTable has exactly the same issue.  It might be a good idea to check that all of the table modules that should accept tables of varying size actually can.

Thanks,
Shawn

**Comment by soumith** [comment]
hi! sorry about this. fixed 4 more modules in #333, looking into the rest now.

**Comment by shawnjhenry** [comment]
No problem - thanks for fixing them so quickly!

**Comment by shawnjhenry** [comment]
Hey, sorry to bother you again, but there are still more table modules with the bug.  ConcatTable is one of them.

Thanks,
Shawn

**Comment by soumith** [comment]
thanks a lot for the report, fixing it.

**Comment by soumith** [comment]
hey @shawnjhenry I'm not able to reproduce it for ConcatTable. Can you give me a short example script to reproduce it?

**Comment by shawnjhenry** [comment]
Sure.

```
test = nn.ConcatTable()
test:add(nn.Identity())
test:add(nn.Identity())

x = {torch.randn(5), torch.randn(5)}
y = {torch.randn(5)}

print("output1")
print(test:forward(x))
print("gradInput1")
print(test:backward(x, {x, x}))
print("output2")
print(test:forward(y))
print("gradInput2")
print(test:backward(y, {y, y}))
```

As you can see, gradInput2 is a table of size two, when in fact it should be a table of size one.

Thanks,
Shawn

**Comment by soumith** [comment]
@shawnjhenry concattable bug fixed via https://github.com/torch/nn/pull/378
