### ISSUE TITLE
HardShrink problem

### ISSUE THREAD

**Issue by joohongyoo** [torch/nn#346]
Hi, I have a problem about HardShrink.
I've got an error with message, "attempt to call field 'HardShrink_updateOutput' (a nil value)."
Threhold works well.
So, I don't know why the HardShrink does not work.

Does anybody have some ideas about this problem?

Thanks.

**Comment by soumith** [comment]
@joohongyoo HardShrink has not been implemented for CUDA, that's why you see this error.

**Comment by soumith** [comment]
A pull request to implement this for CUDA is welcome. until then, closing the issue.
