### ISSUE TITLE
CosineEmbeddingCriterion does not support batch mode

### ISSUE THREAD

**Issue by soumith** [torch/nn#352]
https://github.com/torch/torch7/issues/298

**Comment by boknilev** [comment]
Hi,

Does anyone have a solution to batch mode in CosineEmbeddingCriterion? I saw that CosineDistance already supports batch mode in https://github.com/torch/nn/pull/300, but was wondering about the criterion.

**Comment by fmassa** [comment]
@boknilev I'll try to find some time this week to fix it.

**Comment by boknilev** [comment]
Thanks, @fmassa!

**Comment by fmassa** [comment]
@boknilev I've pushed a version of `CosineEmbeddingCriterion` which works with batches in https://github.com/torch/nn/pull/359

**Comment by boknilev** [comment]
@fmassa Thanks for the quick solution!
