### ISSUE TITLE
Issue with ClassNLLCriterion

### ISSUE THREAD

**Issue by uuddlrlrbas** [torch/nn#369]
Hi,

I got the following error message after I updated my torch, problem still existed after a clean install.

==> Converting model to CUDA	
==> doing epoch on training data:	
==> online epoch # 1	
/usr/local/bin/luajit: /usr/local/share/lua/5.1/nn/ClassNLLCriterion.lua:50: bad argument #1 to 'ClassNLLCriterion_updateOutput' (torch.CudaTensor expected, got nn.ClassNLLCriterion)
stack traceback:
	[C]: in function 'ClassNLLCriterion_updateOutput'
	/usr/local/share/lua/5.1/nn/ClassNLLCriterion.lua:50: in function 'forward'
	/usr/local/share/lua/5.1/fbnn/Optim.lua:146: in function 'optimize'
	...Desktop/git_my_branch/research/Lua/autocat_CNN/train.lua:285: in function 'f2'
	.../Desktop/git_my_branch/research/Lua/autocat_CNN/data.lua:35: in function 'addjob'
	...Desktop/git_my_branch/research/Lua/autocat_CNN/train.lua:202: in function 'train'
	main.lua:61: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00406260

**Comment by korkinof** [comment]
Hi guys,
Any news about this issue, as I'll need to update and I'd like to make sure it will be ok?
Best,
D.

**Comment by fmassa** [comment]
@uuddlrlrbas reading your error message, I think you forgot to update `nn` and updated only `cunn`. Look at https://github.com/torch/nn/commit/ef2e3d290418c411add8eee8dd5ca7d486362ad8#diff-1aa6a505cf16ad0e59498ada8432afb5L50 and https://github.com/torch/nn/commit/ef2e3d290418c411add8eee8dd5ca7d486362ad8#diff-1aa6a505cf16ad0e59498ada8432afb5R50 . `self` is not passed anymore to the cuda function.

**Comment by soumith** [comment]
I think @fmassa is right. it seems like you forgot to update one of nn/cunn. Updating both will fix it.
