### ISSUE TITLE
ReLU, Leaky ReLU, PReLU and RReLU

### ISSUE THREAD

**Issue by andreaskoepf** [torch/nn#380]
The paper 'Empirical Evaluation of Rectifed Activations in Convolution Network' by Bing Xu et. al.
http://arxiv.org/pdf/1505.00853.pdf compares several rectifier variants. It shows that simple Leaky ReLUs (constant a) and Randomized ReLUs (uniform random a during training) can outperform PReLUs on CIFAR-10 & CIFAR-100 on the test set.
I would like to have the full set of rectifier non-linearities for my models. Is anybody already working on this? Otherwise I would like to work on a solution and prepare a PR.

**Comment by andreaskoepf** [comment]
To clarify this: The error-advantage of Leaky ReLU & RReLU over PReLUs is probably not relevant in most cases .. but I would like to get rid of extra learned parameters if they offer no clear improvements. At least having an impl of a Leaky ReLU is trivial and would not hurt.

**Comment by soumith** [comment]
We only have ReLU and PReLU implemented so far.
Leaky ReLU is indeed trivial, and a Pull Request is welcome.
@szagoruyko implemented Leaky ReLU in his cunn-rtc package (dynamically compile cuda kernels using nvrtc).

https://github.com/szagoruyko/cunn-rtc/blob/master/LeakyReLU.lua

https://github.com/szagoruyko/cutorch-rtc

**Comment by andreaskoepf** [comment]
@soumith & all: Design question: Should we create a single transfer-function that implements different flavors of the ReLU-Family .. from an implementation perspective ReLU, Leaky ReLU and PReLU  are very similar (e.g. Leaky ReLUs are PReLU with learning disabled and ReLU itself is then just skipping a multiplication). But it would no longer be possible to derive from nn.Threshold. Having separate impls could make them more accessible for the user but I am a little bit afraid of 'ReLU-bloat'. It would be possible to create a ReLUFamily base (or equip ReLU with optinal ctor args) and have derived classes mainly to introduce the other names... what do you think?

**Comment by soumith** [comment]
@andreaskoepf I think we can keep a common set of C / CUDA functions that are called to avoid code bloat. Subclassing is a matter of taste, I have no opinion over deriving subclasses, or holding separate classes, as long as they are calling common functions underneath.

**Comment by andreaskoepf** [comment]
We have now PRs for [LeakyReLU](https://github.com/torch/nn/pull/445) by @rotmanmi  and [RReLU](https://github.com/torch/nn/pull/437) by myself. A general question is whether we combine everything into one impl. E.g. my RReLU impl already behaves like LeakyReLU if lower == upper and like ReLU if lower == upper == 0 (this could be detected as special case to maximize speed). To merge the PReLU impl would take some time but should be possible...

**Comment by andreaskoepf** [comment]
Separate impls have been merged.
