### ISSUE TITLE
SpatialUpSamplingNearest is not on Spatial Modules list in the docs

### ISSUE THREAD

**Issue by apaszke** [torch/nn#382]
SpatialUpSamplingNearest is documented, but it isn't listed on top of `convolution.md`, so it's hard to find it if you don't know that it exists

**Comment by soumith** [comment]
fixed via https://github.com/torch/nn/commit/4c0534848f02f13493efeb17205a60953850b5a5

In the future, just sending a PR would also be nice (and a faster fix) :)

**Comment by apaszke** [comment]
I'm sorry, I'll do better next time :blush:
