### ISSUE TITLE
Crash loading GPU models saved as float

### ISSUE THREAD

**Issue by etrulls** [torch/nn#388]
After updating torch I cannot load saved models anymore. It crashes on getParameters():
```
...ls/soft/torch-distro/install/share/lua/5.1/nn/Module.lua:247: invalid arguments: CudaTensor ByteTensor
expected arguments: [*CudaTensor*] CudaTensor CudaTensor
stack traceback:
        [C]: in function 'maskedSelect'
        ...ls/soft/torch-distro/install/share/lua/5.1/nn/Module.lua:247: in function 'flatten'
        ...ls/soft/torch-distro/install/share/lua/5.1/nn/Module.lua:272: in function 'getParameters'
```
It only happens if you save the models after converting them to float/double, which I do for CPU/GPU compatibility (it's always worked for me). This gist reproduces the problem on my system:
https://gist.github.com/etrulls/7d99bbd1f947da62bbf8
(If you try to interact with the model afterwards, torch crashes entirely.)

It seems to work again if I revert 7105419c8382c, but I'm having trouble following that commit.

**Comment by soumith** [comment]
thanks, working on a patch.

**Comment by etrulls** [comment]
Actually the saving has nothing to do with it, sorry. Crashes with :clone():float():cuda() on the model too.

**Comment by soumith** [comment]
committed a patch in #389 to fix this. sorry about that.

**Comment by soumith** [comment]
@etrulls fixed in a commit in cunn. If you upgrade your cunn, you wont have this issue anymore.
