### ISSUE TITLE
make nn.Linear handle 3D tensor

### ISSUE THREAD

**Issue by blackyang** [torch/nn#396]
Hi there,

Could we extend nn.Linear so that it can handle 3D tensor?

When dealing with RNN, sometimes I have an output tensor with shape:
> (nb_batch * nb_seq_len * nb_dim1). 

I want to feed it into a fully connected layer in order to get a tensor of shape:
>(nb_batch * nb_seq_len * nb_dim2). 

However since both **nb_batch** and **nb_seq_len** may vary (namely both of them are unknown in general case. Although in practice I am able to know nb_batch myself), I couldn't reshape it into 2D tensor, use nn.Linear and then reshape back to 3D tensor. 

Thus I think it would be convenient if nn.Linear is able to handle 3D tensor. Such need is common when dealing with RNN. I guess it shouldn't be too hard to do this extension, I can give a try when I have time.

**Comment by szagoruyko** [comment]
isn't https://github.com/torch/nn/blob/master/doc/simple.md#nn.MM what you want?

**Comment by blackyang** [comment]
Hi @szagoruyko , sorry I am not sure whethe I get your point, but I want a **trainable** fully connected layer, not a matrix multiplication

**Comment by szagoruyko** [comment]
oh yeah sure, I think I have seen it somewhere. You can take a look at nn.MM and nn.Linear implementations, has to be pretty easy to combine them.

**Comment by blackyang** [comment]
Yes it should be easy to implement, I can give a try when I have time. Thanks for your pointer to nn.MM :)

**Comment by hughperkins** [comment]
I'd like to see this too :-)

**Comment by blackyang** [comment]
Hi all, I made a pull request  [here](https://github.com/torch/nn/pull/398)

**Comment by ankitvgupta** [comment]
I know this thread been closed a while, but I had a similar need and solved it with nn.Bottle (https://github.com/torch/nn/blob/master/doc/containers.md#nn.Bottle) - just wanted to put that here since I suspect others will be searching for this too.
