### ISSUE TITLE
Problem of nn.lookuptable parameters updating while performing on-line learning

### ISSUE THREAD

**Issue by riverhxz** [torch/nn#423]
nn.lookuptable is used to perform the embedding. In some cases, e.g. matrix factorization, few parameters were updated in each iteration.  And there are many iteration in each epoch. It is very inefficient to update all parameters in each iteration.

**Comment by fmassa** [comment]
I think this is the use-case of [accUpdateGradParameters](https://github.com/torch/nn/blob/master/doc/module.md#accupdategradparametersinput-gradoutput-learningrate).
Give it a try instead of `updateParameters` or `optim.sgd`.

**Comment by riverhxz** [comment]
@fmassa thanks. `lookuptable` usually embeded in a custom network integrated by `gMoudule`. `accUpdateGradParameters` seems not being implemented by `gMoudule`.
so i can just use `lookuptable` efficiently or seperately ?

**Comment by riverhxz** [comment]
@fmassa  you are helpful. now i can implement factorization machine in several lines with torch.

**Comment by fmassa** [comment]
@riverhxz a simple way of doing it could also be to use [backwardUpdate](https://github.com/torch/nn/blob/master/Module.lua#L35), tip from [here](https://groups.google.com/forum/#!topic/torch7/XJMlNEC4YoE)

**Comment by riverhxz** [comment]
@fmassa `backward` will call `accGradParameters` in `nn.Module`. It works for [nn.gModule](https://github.com/torch/nngraph/blob/master/gmodule.lua) ,too, as the `nn.gModule` implements `accGradParameters`.

it is not working for `accUpdateGradParameters` as `nn.gModule` doesn't implement it. 
The version of `nn.Module` is invoked when you call `accUpdateGradParameters` through `backwardUpdate`.
