### ISSUE TITLE
Create better graph for softplus function

### ISSUE THREAD

**Issue by andreaskoepf** [torch/nn#428]
The 'random' softplus graph in the nn docs https://github.com/torch/nn/blob/master/doc/image/softplus.png obfuscates the fact that the softplus function can be seen as a [soft version of the rectifier units](https://en.wikipedia.org/wiki/Rectifier_%28neural_networks%29#/media/File:Rectifier_and_softplus_functions.png). 

-> I think we should add 'classic' function + first derivative plots.

Is there a special reason why the softplus graph was created in a similar way to the SoftMin and SoftMax graphs which divide by a sum and since an isolated view does not make much sense?

**Comment by soumith** [comment]
I believe the doc was created that way because of how SoftPlus was first used in the context. It makes sense to modify the docs and add a regular graph like other non-linearities.

**Comment by andreaskoepf** [comment]
OK, I will create a PR with a replacement later today.
