### ISSUE TITLE
division by zero in normalize.lua (L60)

### ISSUE THREAD

**Issue by rlebret** [torch/nn#440]
https://github.com/torch/nn/blob/master/Normalize.lua#L60
can divide by zero. pow(p-2) divides for p<2.
It could be changed to 
  self.buffer:abs(input):add(self.eps):pow(self.p-2):cmul(input)
to fix this.

**Comment by soumith** [comment]
if you send a PR for it, happy to accept.

**Comment by fmassa** [comment]
I'll prepare a patch for it

**Comment by soumith** [comment]
should be fixed now.
