### ISSUE TITLE
CosineEmbeddingCriterion batch mode

### ISSUE THREAD

**Issue by einatkermany** [torch/nn#448]
Hello,
I'm trying to use CosineEmbeddingCriterion with batch (without cuda) and get the error:
/opt/torch/install/bin/luajit: inconsistent tensor size at /opt/torch/pkg/torch/lib/TH/generic/THTensorMath.c:72
From: CosineEmbeddingCriterion.lua:63
I check in a command line and see that:
when a is 0 [torch.ByteTensor of size 1]
x[a] - when x is Tensor size 1 it's ok but when x is a vector the same error is raised.
Can you help ?
Thanks,
Einat

**Comment by fmassa** [comment]
can you give a minimum example reproducing the problem ?

**Comment by einatkermany** [comment]
x1=torch.rand(1)
x4=torch.rand(4)
y=x4.new(1)
y[1]=1
a=torch.ByteTensor()
y.eq(a,y,-1)

x1[a] - it's fine
x4[a] - error

**Comment by albanD** [comment]
I think the answer is in the way you index Tensor, see the doc [here](https://github.com/torch/torch7/blob/master/doc/tensor.md#tensor--dim1dim2--or--dim1sdim1e-dim2sdim2e-): when you use ByteTensor, you should provide a mask. Thus the ByteTensor must have the same number of elements as the Tensor you try to index.
In you case `a` has one element so it works with `x1` that also contains one element but not with `x4` that has 4 elements.

**Comment by fmassa** [comment]
if you are using batches, then the number of target elements should be equal to the batch size.
For example, the following example works
```lua
m = nn.CosineEmbeddingCriterion()
batch_size = 5
dim = 10
input = {torch.rand(batch_size,dim),torch.rand(batch_size,dim)}
target = torch.Tensor{1,-1,1,-1,1}
m:forward(input,target)
```

**Comment by einatkermany** [comment]
Thanks for the answers.
I assumed that y can be default value (1) and therefore used it like:
m:forward(input) 
And in this way it doesn't work...
