### ISSUE TITLE
back-propagation in MulConstant Layer 

### ISSUE THREAD

**Issue by harrywy** [torch/nn#451]
Hi @jonathantompson 

This maybe a stupid thought, however, I think this make sense:

The layer could be used as an amplifier that upscale input,
which on the other hand  downscale error when back-prop.

output = scale * input 
when back-prop: 
gradInput = 1/ scale * gradOutput

Mathematically:
y = a * x
dy = a *dx 
dx = 1/a dy

Correct me if I am wrong, if I am right I will push my modified code. 
(Just change mul to div in updateGradInput)

Best,
Wenyi

**Comment by andreaskoepf** [comment]
updateGradInput() computes the gradient w.r.t. the input vector: The multiplication in the current impl of MulConstant is correct. Backprop is not about inverting the functions it is about the chain rule: (f(g(x)))' = f'(g(x)) * g'(x) ...

**Comment by jonathantompson** [comment]
The intention of this layer was to multiply a non-learnable constant. If you want to make the constant a learnable parameter you can make this an option in the constructor.
