### ISSUE TITLE
Install on Windows: error C3016

### ISSUE THREAD

**Issue by nathanprat** [torch/nn#455]
When trying to install nn on windows(with diz-vara's  luarocks), it gives

`appdata\local\temp\luarocks_nn-scm-1-862\nn\generic/SpatialConvolutionMM.c(19): error C3016: 'nip': index variable in OpenMP 'for' statement must have signed integral type`

The solution is to make a small modification in `generic/SpatialConvolutionMM.c`
replace `size_t nip;` by `int nip;` on line 19
Or use this [patch](https://gist.github.com/nathanprat/f63895d79054ec75ab5d) 

With that modification, it installs fine.

**Comment by fmassa** [comment]
Well, this modification will not make everyone happy, it was recently changed to support huge inputs, see https://github.com/torch/nn/pull/443
Would using `long` be enough ?

**Comment by nathanprat** [comment]
It seems to install fine with `long nip;`  
As a more permanent solution, maybe we could use a platform-dependent typedef?
Something like
```
#ifdef _WIN32  
typedef long nipType;  
#else  
typedef size_t nipType;  
#endif
```  
and declaring *nip* with `nipType nip;`

**Comment by soumith** [comment]
it's long long now, so that should hopefully fix this
