### ISSUE TITLE
SpatialConvolutionMM unsigned logic for signed numbers

### ISSUE THREAD

**Issue by szagoruyko** [torch/nn#457]
https://github.com/torch/nn/pull/443 might introduce bugs after switching to `size_t` from `int`. clang complains:
```
/tmp/luarocks_nn-scm-1-4089/nn/generic/SpatialConvolutionMM.c:32:20: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
            if (iy < 0 || iy >= inputHeight) {
                ~~ ^ ~
/tmp/luarocks_nn-scm-1-4089/nn/generic/SpatialConvolutionMM.c:43:27: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
                   if (ix < 0 || ix >= inputWidth){
                       ~~ ^ ~
/tmp/luarocks_nn-scm-1-4089/nn/generic/SpatialConvolutionMM.c:92:16: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
        if (iy < 0 || iy >= inputHeight) {
            ~~ ^ ~
/tmp/luarocks_nn-scm-1-4089/nn/generic/SpatialConvolutionMM.c:110:23: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
               if (ix < 0 || ix >= inputWidth)
                   ~~ ^ ~
```

**Comment by dominikgrewe** [comment]
Yes, I don't think those variables should be `size_t` if they can take on negative values. `long long` may be more suitable. The variables themselves actually don't seem to need that range, I think it's only the computation they're involved in that might go out of the range of ints. So maybe casting them in those computations might be sufficient.

@anastasiuspernat

**Comment by anastasiuspernat** [comment]
Probably that's right for ix & iy only - I'll try that and see how it goes right now.

**Comment by anastasiuspernat** [comment]
The following pull request should fix it: https://github.com/torch/nn/pull/462
