### ISSUE TITLE
clnn and cltorch on mac with Intel

### ISSUE THREAD

**Issue by mikeconnors909** [torch/nn#470]
Hi, I am trying to run this code (https://github.com/karpathy/char-rnn), which has support for OpenCl. Normally mac has an OpenCl preinstalled. However, when I try to run the code with the opencl option, it says to install the clnn and cltorch modules (they are installed) and if they are installed, to check my OpenCL driver's configuration. This is on a macbook pro with an Intel HD4000 card running OS X Mavericks. Any idea what is happening? How do I fix?

**Comment by soumith** [comment]
Hi there. Please file the issue under clnn: https://github.com/hughperkins/clnn or cltorch
