### ISSUE TITLE
In table.md, could you explain a meaning of a senctence?

### ISSUE THREAD

**Issue by LeeTaewoo** [torch/nn#485]
In https://github.com/torch/nn/blob/master/doc/table.md#selecttable, I can't interpret the following sentence. Could you explain it in easier way?

"This is true regardless of the depth of the encapsulated Tensor as the function used internally to do so is recursive."

My guess is this:
This is true regardless of the depth of the encapsulated Tensor.
As(=Since) the function used internally to do so is recursive.

**Comment by soumith** [comment]
yea, there needs to be a comma:

> This is true regardless of the depth of the encapsulated Tensor, as the function used internally to do so is recursive.

sorry about that.

**Comment by LeeTaewoo** [comment]
Oh, I see. Thank you so much. :)
