### ISSUE TITLE
SpatialAdaptiveMaxPooling backward is imposible without forward?

### ISSUE THREAD

**Issue by korkinof** [torch/nn#494]
Hi guys,
I've been having cuda errors (which have been driving me crazy!) trying to run the backward pass of this layer, without the forward, or with forward of different featuremap.
Is it the case that memory allocation needed for the backward pass are taking place in the forward?
Best,
D.

**Comment by fmassa** [comment]
There is this common supposition in nn that you can only call backward after calling forward.
Indeed, for the `SpatialAdaptiveMaxPooling`, the max indexes are stored during forward, to speed up backward pass.
Also, the forward pass is going to resize this buffer which stores the max indexes, which might allocate new memory.
