### ISSUE TITLE
Minor BUG: Use of newContiguous(output) in SpatialFullConvolutionMap.c

### ISSUE THREAD

**Issue by andreaskoepf** [torch/nn#521]
In [ SpatialFullConvolutionMap.c](https://github.com/torch/nn/blob/31d7d2bc86a914e2a9e6b3874c497c60517dc853/generic/SpatialFullConvolutionMap.c#L46) `output = THTensor_(newContiguous)(output);` which does not assign the new contiguous storage to the original output-tensor in case the output was not contiguous.

Possible solutions:
1. Check with isContiguous() and generate an THError() if a non-contigous output-tensor is present.
2. use something like
```
THTensor *tmp = THTensor_(newContiguous)(output);
THTensor_(set)(output, tmp);
THTensor_(free)(tmp);
```

btw I personally would like to suggest to implicitly generate contiguous tensors when resize is called, e.g. when the output-size matches but a non contiguous stride is used. This would probably also [fix this issue](https://github.com/torch/torch7/issues/289). The [resize documentation](https://github.com/torch/torch7/blob/master/doc/tensor.md#resizing) currently at least hints in this direction as it says: 'In particular, the elements of the resized tensor are contiguous in memory.' (e.g. it does not indicate that this is not the case if the target size is already matched).

**Comment by dominikgrewe** [comment]
I think a common solution is to use `freeCopyTo`. At least that's what's being used in cutorch a lot, e.g. https://github.com/torch/cutorch/blob/master/lib/THC/THCTensorMath2.cu#L405

It copies the input tensor to the output tensor if they are not equal and then frees the input tensor: https://github.com/torch/torch7/blob/master/lib/TH/generic/THTensor.c#L603.

**Comment by andreaskoepf** [comment]
@dominikgrewe ok, that means to operate on the contiguous tensor and copy it back afterwards with freeCopyTo().
```
THTensor* output_ = THTensor_(newContiguous)(output);

// work on output_

THTensor(freeCopyTo)(output_, output);
```
sounds like a reasonable solution! :+1:
