### ISSUE TITLE
Can't get ELU to work

### ISSUE THREAD

**Issue by larspars** [torch/nn#523]
I'm trying to use the recently added Exponential Linear Unit.

A clean reinstallation of Torch doesn't seem to include use the latest version of nn. When I try to use ELU I get this error:

    attempt to call field 'ELU' (a nil value)

If I pull down the latest version of nn from git, and build it:

    git clone https://github.com/torch/nn.git
    luarocks make rocks/nn-scm-1.rockspec 

I get this error:

    attempt to call field 'ELU_updateOutput' (a nil value)

Am I installing this incorrectly? Or is something else going wrong?

**Comment by willwilliams** [comment]
Maybe you haven't updated to the most recent `cunn` version?

**Comment by larspars** [comment]
That was it, thanks!
