### ISSUE TITLE
annotation in line 99

### ISSUE THREAD

**Issue by zhangguoxiao** [torch/nn#529]
The annotation in line 99   " -- 1 / E([x - E(x)]^2)"   seems to be wrong.
The part of E([x - E(x)]^2)  need to add eps ,after which a redical sign is also needed.

**Comment by fmassa** [comment]
Could you give a bit more context to it ? Which file ?

**Comment by zhangguoxiao** [comment]
Sorry!  It is in line 99 of the file nn <https://github.com/torch/nn>/
*BatchNormalization.lua.*

2015-12-15 1:26 GMT+08:00 Francisco Massa <notifications@github.com>:
