### ISSUE TITLE
Strange bug with nn.Module.parameters

### ISSUE THREAD

**Issue by mavenlin** [torch/nn#538]
The following code:
```
lin=nn.Linear(10, 10)
a, b, c, d = lin:parameters()
```
Note that `parameters` only returns two tables, `c` and `d` are supposed to be `nil` if nothing's wrong, but you'll see that `c` is an empty table, where does this empty table comes from?

**Comment by kmul00** [comment]
Can you please recheck once again, or maybe update the `nn` package and try again. Because I ran the same piece of code, i.e.
    
    require 'nn';
    lin = nn.Linear(10, 10)
    a, b, c, d, = lin:parameters()

and, `c` and `d` are `nil` only.

**Comment by mavenlin** [comment]
With updated nn, it is resolved. Thanks I'll close this.
