### ISSUE TITLE
question on organization of weights

### ISSUE THREAD

**Issue by YitzhakSp** [torch/nn#540]
Hi. How exactly are the weigths organized in the container 'Sequential'? The function 'getParameters()' returns all the weights in a onedimensional array. How do I translate it to the 3-dimensional weightmatrix w_(i,j,k) where i represents the level and j,k the corresponding neurons ?

**Comment by soumith** [comment]
@YitzhakSp getParameters returns a flattened tensor of parameters. What you are looking for is model:parameters(), which returns a table of parameters that are unflattened.
