### ISSUE TITLE
"Attempt to call field 'SpatialMaxUnpooling_updateOutput'"

### ISSUE THREAD

**Issue by gpleiss** [torch/nn#541]
When I try using the SpatialMaxUnpooling module, I get the following error:

```
...s/torch/install/share/lua/5.1/nn/SpatialMaxUnpooling.lua:26: attempt to call field 'SpatialMaxUnpooling_updateOutput' (a nil value)
```

I get this error whether or not I'm using cuda.

**Comment by soumith** [comment]
You simply have to reinstall your nn / cunn I think.

**Comment by chtlp** [comment]
Hi, I am having the same issue. Reinstalled cunn/nn by `luarcoks install cunn/nn`, and even
```
git clone https://github.com/torch/nn.git
luarocks make rocks/nn-scm-1.rockspec
```
but it didn’t work either.

I am under Ubuntu 14.04 with CUDA 7.5. Any help would be greatly appreciated!

**Comment by fmassa** [comment]
There is for the moment no cuda version of this module, that's why you are seeing this error.
@clement-masson could you prepare the cuda PR ?

**Comment by clement-masson** [comment]
@fmassa I'll do it this afternoon :) !

**Comment by clement-masson** [comment]
Done.
https://github.com/torch/cunn/pull/186

**Comment by chtlp** [comment]
It's now working. Thanks for the quick response!
