### ISSUE TITLE
problem with model:backward()

### ISSUE THREAD

**Issue by YitzhakSp** [torch/nn#543]
I want to calculate the derivative wrt. to the outputs themselves and wrt. to some error criterion. In this case I shall call  
<pre><code>
model:backward(x,1.0)
</code></pre>
right? beacause the derivative of the output wrt. to itself is 1.0. 
I tested this on a small net containing only one linear layer. However it seems to give me a wring result. 
Am I missing something?

**Comment by soumith** [comment]
The output of the linear layer is a tensor, not a number. backward(input, gradOutput) here expects gradOutput to be a tensor. gradOutput should be exactly of the same type and size as model.output, check that and make sure it's the case. If you still have issues, reopen with a script to reproduce the example.
