### ISSUE TITLE
SoftShrink seems to be broken

### ISSUE THREAD

**Issue by edouardoyallon** [torch/nn#566]
Hi,

In the code SoftShrink.lua, I think the call to "input.nn.SoftShrink_updateOutput(self, input)" at line 9 is incorrect. Indeed, when I try to use this non linearity via a forward in a NN architecture, I get the following message:

torch/install/share/lua/5.1/nn/SoftShrink.lua:9: attempt to call field 'SoftShrink_updateOutput' (a nil value)..............................] ETA: 0ms | Step: 0ms          
stack traceback:
        ...torch/install/share/lua/5.1/nn/SoftShrink.lua:9: in function 'updateOutput'
        ...torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
        ...torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
        ...torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
        ...torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        ****.lua:104: in function 'opfunc'
        ...torch/install/share/lua/5.1/optim/sgd.lua:43: in function 'sgd'

The last update of this slice of code was 3 years ago, and I agree there are some alternative ways to build it with some bizarre hints and combination of ReLU and ConcatTable, however any help would be appreciated.

Thanks.

**Comment by fmassa** [comment]
The issue is that `SoftShrink` is not implemented in GPU. Could you open an issue in [`cunn`](https://github.com/torch/cunn) ? It should be trivial to implement
