### ISSUE TITLE
cannot install torch every time I try: unsupported gcc version- please help 

### ISSUE THREAD

**Issue by onemartian** [torch/nn#570]
In file included from /usr/include/cuda_runtime.h:59:0,
                 from <command-line>:0:
/usr/include/host_config.h:82:2: error: #error -- unsupported GNU version! gcc 4.9 and up are not supported!
 #error -- unsupported GNU version! gcc 4.9 and up are not supported!
  ^
In file included from /usr/include/cuda_runtime.h:59:0,
                 from <command-line>:0:
/usr/include/host_config.h:82:2: error: #error -- unsupported GNU version! gcc 4.9 and up are not supported!
 #error -- unsupported GNU version! gcc 4.9 and up are not supported!
  ^
In file included from /usr/include/cuda_runtime.h:59:0,
                 from <command-line>:0:
/usr/include/host_config.h:82:2: error: #error -- unsupported GNU version! gcc 4.9 and up are not supported!
 #error -- unsupported GNU version! gcc 4.9 and up are not supported!
  ^
In file included from /usr/include/cuda_runtime.h:59:0,
                 from <command-line>:0:
/usr/include/host_config.h:82:2: error: #error -- unsupported GNU version! gcc 4.9 and up are not supported!
 #error -- unsupported GNU version! gcc 4.9 and up are not supported!
  ^
CMake Error at THC_generated_THCBlas.cu.o.cmake:206 (message):
  Error generating
  /home/auto/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o

lib/THC/CMakeFiles/THC.dir/build.make:63: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMake Error at THC_generated_THCReduceApplyUtils.cu.o.cmake:206 (message):
  Error generating
  /home/auto/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o

lib/THC/CMakeFiles/THC.dir/build.make:55: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o] Error 1
CMake Error at THC_generated_THCStorage.cu.o.cmake:206 (message):
  Error generating
  /home/auto/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o

lib/THC/CMakeFiles/THC.dir/build.make:71: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o] Error 1
CMake Error at THC_generated_THCTensorSort.cu.o.cmake:206 (message):
  Error generating
  /home/auto/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorSort.cu.o

lib/THC/CMakeFiles/THC.dir/build.make:231: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorSort.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorSort.cu.o] Error 1
CMakeFiles/Makefile2:191: recipe for target 'lib/THC/CMakeFiles/THC.dir/all' failed
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.
auto@cerebellum:~/torch$

**Comment by soumith** [comment]
update the CUDA version on your machine.
Next time, try googling for such issues first before posting.

**Comment by arnwas** [comment]
I have the same problem, and i am newest cuda for my distro.
Can I force the whole build system to only use gcc-4.8?
I cannot uninstall gcc-5 for millions of dependencies, but i have 4.8 along....

Cheers, Arno

**Comment by szagoruyko** [comment]
@arnwas `CC=gcc-4.8 CXX=g++4.8 luarocks install cutorch`

**Comment by arnwas** [comment]
Am 03.03.2016 um 00:15 schrieb Sergey Zagoruyko:
>
> @arnwas <https://github.com/arnwas> |CC=gcc-4.8 CXX=g++4.8 luarocks 
> install cutorch|
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/torch/nn/issues/570#issuecomment-191488394>.
>

This did not work until I uninstalled both gcc-4.9 and gcc-5. Which was 
quite a mess since I need those versions for other things...

Cheers, Arno

**Comment by c4mden** [comment]
The following command worked for me:
CC=gcc-4.9 CXX=g++-4.9 luarocks install cutorch

Note the added hyphen in the g++ package.  I didn't have to uninstall any newer packages of gcc to get this working on the latest Ubuntu (15.10).

**Comment by iyn** [comment]
If somebody has this error on Arch Linux, cuda needs an older version of GCC (4.9 is ok): https://wiki.archlinux.org/index.php/GPGPU#Using_CUDA_with_an_older_GCC

But at this moment, gcc4.9 from AUR won't install properly, you need to change few things in the PKGBUILD by hand, citing comments from https://aur.archlinux.org/packages/gcc49/
```
same error as nsdfyd here. Fixed it by telling configure explicitly to use $CHOST from /etc/makepkg.conf, i.e.

--- ../aurpkg/gcc49/PKGBUILD 2016-05-21 19:22:14.396651118 +0200
+++ PKGBUILD 2016-05-21 19:46:46.239910486 +0200
@@ -61,6 +61,7 @@
CXXFLAGS=${CXXFLAGS/-pipe/}

${srcdir}/${_basedir}/configure --prefix=/usr \
+ --build=${CHOST} \
--libdir=/usr/lib --libexecdir=/usr/lib \
--mandir=/usr/share/man --infodir=/usr/share/info \
--with-bugurl=https://bugs.archlinux.org/ \


not exactly sure what this is but I think older autoconf version report the system as `x86_64-unknown-linux-gnu` whereas newer ones use `x86_64-pc-linux-gnu`
```

```
Compiled only after adding "--build=${CHOST}" and commented out line #100 (find command) to avoid the error "Cannot remove libiberty: is a directory"
```

This solved my problem after looking for solution for a few hours, so I'm posting here, maybe it'll save someone some time.
