### ISSUE TITLE
[Question]: LookupTable error - LookupTable_accGradParameters

### ISSUE THREAD

**Issue by aleSuglia** [torch/nn#571]
Hi to all,

I am trying to create a CNN for modeling documents and sentences. I have created the network (it is far from complete, but the forward step works):

```
require 'nn';

vocab = {hello=1, alex= 2, john=3, mary=4, lisa=5, home=6, school=7, goes=8}
vocab_size = 8

s1_d1 = {vocab['hello'], vocab['alex'], vocab['goes'], vocab['home']}
s2_d1 = {vocab['hello'], vocab['john'], vocab['goes'], vocab['school']}

s1_d2 = {vocab['hello'], vocab['lisa'], vocab['goes'], vocab['home']}
s2_d2 = {vocab['hello'], vocab['mary'], vocab['goes'], vocab['school'] }

max_sentences_doc = 2

d1 = {s1_d1, s2_d1}
d2 = {s1_d2, s2_d2}

items = {d1, d2}
items_size = 2

embeddings_size = 7

document_model = nn.Sequential()
document_model:add(nn.LookupTable(vocab_size, embeddings_size))

sentences_model = nn.ParallelTable()

for _=1, max_sentences_doc do
    local sentence_model = nn.Sequential()
    local filter_size = 5
    -- paddings to perform wide convolution
    sentence_model:add(nn.Padding(1, -(filter_size-1)))
    sentence_model:add(nn.Padding(1, filter_size-1))
    sentence_model:add(nn.TemporalConvolution(
        embeddings_size, -- dimensionality of one sequence element
        6, -- # of filters (# of derived features for one sequence element)
        filter_size -- filter size
    ))
    sentences_model:add(sentence_model)
end

document_model:add(sentences_model)

document_model:add(nn.JoinTable(1))

input_doc = torch.Tensor(d1)

criterion = nn.MSECriterion()
pred = document_model:forward(input_doc)
print(pred)

output = torch.randn(16, 6)
document_model:zeroGradParameters()
print(document_model:backward(input_doc, criterion:backward(document_model.output, output)))

```
When I execute it I got this strange error:
```
../lua/5.1/nn/LookupTable.lua:71: bad argument #3 to 'LookupTable_accGradParameters' (torch.DoubleTensor expected, got number)
```

It seems that the ParallelTable container is not able to correctly propagate backward the gradient to the LookupTable module. 
According to the issue #568, I have tried to set to an empty function the ParallelTable's member **updateGradInput**.  But obviously it is not related because there is nothing before the LookupTable. I think that is a pretty weird error that is not related to the network's structure that I have defined until now.

Thank you in advance for your help.

Alessandro

**Comment by fmassa** [comment]
`ParallelTable` expects a table as input, and you are providing a tensor to it.
It works for the `forward` because the indexing is the same for tensors or tables, but the `backward` outputs a table, and that's why your module is not working.
Add a `document_model:add(nn.SplitTable(1))` just after you `LookupTable` and everything should be fine.
Also, those questions are better suited for the [Google Groups](https://groups.google.com/forum/#!forum/torch7).
