### ISSUE TITLE
memory efficient use of CNN clones

### ISSUE THREAD

**Issue by shaayaansayed** [torch/nn#574]
I need to create clones of a CNN (loaded from caffe using the loadcaffe library) for an end-to-end video captioning model. The number of clones is equal to the number of frames (essentially an image) in the largest video in the split. 

The issue I'm having is not in the clone construction, but when using the clones. 

I pass the video frame by frame through clones. With each additional pass, the gpu memory spikes by about 600 MiB allowing me to only pass about 8-9 frames before running out of memory. 

This occurs whether I use nn or cudnn as a backend to loadcaffe. 

The issue only occurs when I pass input to a never before used clone. If I pass the frames through one CNN clone, the memory only increases by 600. For each additional clone I call forward on, the memory use goes up by 600 each. 

Note that this unnatural spike in memory doesn't happen if I use gmodule LSTM clones for example. Is this just how memory intensive a CNN pass is?  

EDIT: looking at benchmarks, I'm thinking that it is natural for a CNN pass to take this much memory.

**Comment by soumith** [comment]
The larger memory component of CNNs is the states and not the weights. So such additional memory spikes per clone after passing the video frame is normal.
