### ISSUE TITLE
Changing cuda implementation of fractional max pooling

### ISSUE THREAD

**Issue by mattdns100689** [torch/nn#592]
Hi. I wish to change some code in a torch cuda script regarding fractional max pooling (SpatialFractionalMaxPooling.cu) and I wondered if I could get a bit of help;

The code that (I think) I wish to change is;
```

26  THCDeviceTensor<float, 3> samples,

39    int poolW = getInterval(samples[batch][plane][0], outputW,
40                            input.getSize(3), output.getSize(3), poolSizeW);
41    int poolH = getInterval(samples[batch][plane][1], outputH,
42                         input.getSize(2), output.getSize(2), poolSizeH);


```
to 

'''
26  THCDeviceTensor<float, 2> samples,

39    int poolW = getInterval(samples[batch][0], outputW,
40                            input.getSize(3), output.getSize(3), poolSizeW);
41    int poolH = getInterval(samples[batch][1], outputH,
42                         input.getSize(2), output.getSize(2), poolSizeH);

```
That is I would like to be able to make the pooling indexes to be independent of the planes/features. I tried to compile this with luarocks but ended up with an error. I am not sure if I have to change the code in the SpatialFractionalMaxPooling.lua file for this to happen.

Thanks!

**Comment by soumith** [comment]
@mattdns100689 sorry for the delay in reply. To make such changes, you can do:

```bash
git clone https://github.com/torch/cunn
cd cunn
# make your changes
luarocks make rocks/cunn-scm-1.rockspec
```

**Comment by mattdns100689** [comment]
@soumith thanks for that.
