### ISSUE TITLE
Question about derivative

### ISSUE THREAD

**Issue by sanek777** [torch/nn#595]
Is that true, that in Module:backward we calculate derivative two times, in updateGradInput and accGradParameters. Why do we need this?

**Comment by fmassa** [comment]
Each one of them do different things.
`updateGradInput` computes the derivative with respect to the data (input), whereas `accGradParameters` computes the derivatives with respect to the parameters.
Check [here](https://github.com/torch/nn/pull/234#issuecomment-98099276) for some more information/insight.
BTW, this kind of question should be asked in the [google groups](https://groups.google.com/forum/#!forum/torch7)
