### ISSUE TITLE
dealing with shared parameters in optim functions

### ISSUE THREAD

**Issue by willwhitney** [torch/nn#613]
When you create two modules that share parameters, typically you only share the parameters and not the gradParameters to avoid overwriting. However, this means that calling `p, gp = container:getParameters()` on a container which contains both of them will give you `p` and `gp` of different dimensionality. This makes it hard to use use e.g. `optim.rmsprop`, which expects them to be the same dimension.

Is there a simple, clean way to work around this? And is this something we could improve going forward?

**Comment by soumith** [comment]
actually, when you create two modules that share parameters, typically you share both parameters and gradparamters, as you dont overwrite but accumulate gradients.

**Comment by willwhitney** [comment]
Cool, that's a good answer. We should update the docs appropriately then.

e.g. the example of `clone`:

```lua
-- make a copy that shares the weights and biases
mlp2=mlp1:clone('weight','bias');
```

**Comment by fmassa** [comment]
@willwhitney have a look in here as well https://github.com/torch/nn/blob/master/doc/overview.md#a-note-on-sharing-parameters

**Comment by willwhitney** [comment]
Ahh, that makes sense. Thanks for the pointer!
