### ISSUE TITLE
VolumetricFullConvolution does not pass gradient checks

### ISSUE THREAD

**Issue by fbesse** [torch/nn#625]
There is a problem with VolumetricFullConvolution, as it produces a large error (~1) when checking for correctness of gradients using totem.nn.checkGradients.

Here is the code for the test:

```
local totem = require 'totem'
require 'nn'

local test = totem.TestSuite()
local tester = totem.Tester()

function test.gradVolumetric()
    local input = torch.randn(2, 2, 4, 5, 6)
    local module = nn.VolumetricFullConvolution(2, 3, 4, 5, 5, 2, 3, 3, 1, 2, 2)
    totem.nn.checkGradients(tester, module, input)
end

return tester:add(test):run()
```

And the output:
```
Running 1 test
1/1 gradVolumetric ...................................................... [FAIL]
Completed 2171 asserts in 1 test with 1 failure and 0 errors
--------------------------------------------------------------------------------
gradVolumetric
wrong grad w.r.t. params
TensorEQ(==) violation: max diff=0.99793128440039, tolerance=0.0001
	third_party/lua/totem/totem/nn.lua:267: in function 'checkGradients'
	testVolumetricFullConvolution.lua:10: in function <testVolumetricFullConvolution.lua:7>
```

As a side issue, it does not support non-batch and requires kH == kW && pH == pW which is quite limiting. Finally the way weights are stored is transposed compared to what SpatialFullConvolution does - it would be nice to store them in the same way for consistency.

**Comment by andreaskoepf** [comment]
@fbesse I noticed this as well during the THNN conversion and discussed this with @soumith.

From https://gitter.im/torch/torch7 log:
andreaskoepf, Feb 01 11:06: @soumith I noticed that SpatialFullConvolution.lua uses self.weight = torch.Tensor(nInputPlane, nOutputPlane, kH, kW) while VolumetricFullConvolution.lua uses self.weight = torch.Tensor(nOutputPlane, nInputPlane, kT, kH, kW). I guess the order of the inputPlane/outputPlane dimensions was swapped in SpatialFullConvolution compared to SpatialConvolution in oder to be able to share weights (e.g. indirectly transposed) between a convolution and 'deconvolution' operation (to generate some kind of near orthogonal matrix during optimization). Probably this is not that easy to change now (at least special care would have to be taken to correctly deserialize old models). Should we leave the weight-tensor-structure of VolumetricFullConvolution as it is right now or should it be made consistent with SpatialFullConvolution?
soumith, Feb 01 14:25: @andreaskoepf no one uses VolumetricFullConv right now at the moment. even if someone does, it's minor usage. If it's consistent, let's change the weight layout. One can make it backward compatible via a :read method that checks the shape against: https://github.com/torch/nn/blob/master/VolumetricFullConvolution.lua#L14-L15

@fbesse Do you have time to work on this? I think a PR would be appreciated!

**Comment by fbesse** [comment]
I've got a potential PR which re-implements VolumetricFullConvolution like SpatialFullConvolution, (also removing the limitation on kernel/padding/batches) - but it takes it out from THNN and puts it back next to SpatialFullConvolution - would that be ok as a first step? I also have the matching cunn implementation.
I now use back-compatible, transposed weights.

**Comment by andreaskoepf** [comment]
@fbesse If you could push your changes to https://github.com/fbesse/nn I could do the 'THNN conversion' as a PR to your prepo - basically everything stays the same, only the parameters are passed directly as function arguments instead of retrieving them form luastate.

**Comment by fbesse** [comment]
Great idea, thanks! The changes are pushed in this branch of my repo: https://github.com/fbesse/nn/tree/volumetric_full_fix

**Comment by andreaskoepf** [comment]
PR with the THNN conversion is [ready](https://github.com/fbesse/nn/pull/1). Next we need to do the same for cunn/THCUNN.
