### ISSUE TITLE
Norm of prediction errors

### ISSUE THREAD

**Issue by lakehanne** [torch/nn#638]
How is the prediction error calculated in the stochastic gradient example that was given on the doc page:

```torch
function gradUpdate(mlp, x, y, criterion, learningRate) 
  local pred = mlp:forward(x)
  local err = criterion:forward(pred, y)
  local gradCriterion = criterion:backward(pred, y)
  mlp:zeroGradParameters()
  mlp:backward(x, gradCriterion)
  mlp:updateParameters(learningRate)
end
```

For example, I have a single-input, multi-output (6 outputs actually) system. When I pass the input through the `forward` method, I get six predictions but the error that is computed as I do the backward pass is a scalar value. Is there some way to know what sort of norm torch uses in aggregating backward pass errors into a scalar value during each iteration of the backward propagation process?

Will appreciate your reply. Thanks!

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use github issues for bug tracking. We'll happily reply there. Thanks.
