### ISSUE TITLE
Bug in Bilinear's gradInput

### ISSUE THREAD

**Issue by swiseman** [torch/nn#658]
nn.Bilinear does not seem to calculate its gradInput correctly. For example, running the following code:
```lua
require 'nn'

local bilin = nn.Bilinear(4, 3, 2)
local input = {torch.randn(2, 4), torch.randn(2, 3)}
bilin:forward(input)
local gradIn = bilin:backward(input, torch.ones(2,2))
print(gradIn[1])
print(gradIn[2])
```

will print two tensors that are all zero (though they shouldn't be...). 

Looking at the code, it looks like updateGradInput doesn't incorporate gradOuput as it should. I've made a pull request in #657 that corrects this, and also adds some additional tests to test.lua.

**Comment by soumith** [comment]
cc: @lvdmaaten

**Comment by lvdmaaten** [comment]
You're right, good catch!

In #657, I am unsure if the perf win of dealing with the `k=1` case separately is worth the extra code (makes it a bit hard to read imho).

**Comment by swiseman** [comment]
Ok, great. Yeah, I definitely hear the readability concern; I had sort of assumed that most people would be using Bilinear to get a scalar output, which might make it reasonable to optimize that case, but maybe not. In any case, I'm happy to update the code so it's simpler.
