### ISSUE TITLE
Batch Normalization Momentum?

### ISSUE THREAD

**Issue by n3011** [torch/nn#695]
For the batch normalization layer what does the line "The running sum is kept with a default momentum of 0.1"  means.  How does momentum is used here to updates mean and variance?

**Comment by colesbury** [comment]
The running mean and variances are computed using an exponential moving average with smoothing factor 0.1.

i.e `running_mean[t] = running_mean[t-1]*0.9 + batch_mean[t]*0.1`

**Comment by n3011** [comment]
Thanks @colesbury, its really helpful.

**Comment by Atcold** [comment]
@n3011, perhaps you'd like to improve the documentation with @colesbury's answer :grimacing:
