### ISSUE TITLE
nn.Concat is currently broken

### ISSUE THREAD

**Issue by kosyumote** [torch/nn#709]
Luckily I know exactly what the issue is:

Line 37 of Concat.lua reads

local currentGradInput = self:rethrowErrors(module, i, 'updateGradInput', gradOutput:narrow(self.dimension, offset, currentOutput:size(self.dimension)))

but it should read

local currentGradInput = self:rethrowErrors(module, i, 'updateGradInput', **input,** gradOutput:narrow(self.dimension, offset, currentOutput:size(self.dimension)))

since rethrowErrors will then call updateGradInput with the arguments that follow it, and updateGradInput needs two args

(done in this commit:
https://github.com/torch/nn/commit/b1cf092d84bb6bfdbb6442d13cc0900e3aea7109)

Sorry I'm really new to this whole Linux/git/working as a community thing, so I don't know the right way to address this!

Hopefully this didn't cause too many people trouble :)

**Comment by apaszke** [comment]
@kosyumote I sent a PR with a fix for this issue, thanks for posting it and sorry for trouble!
