### ISSUE TITLE
Backpropagation breaks when using ConcatTable(CAddTable) with CriterionTable

### ISSUE THREAD

**Issue by aalok1993** [torch/nn#715]
Hello,

In the model shown below there is a ConcatTable followed by the CriterionTable. The last layer inside the concat table is the CAddTable. The forward pass works perfectly, but the backward pass breaks down. The arising issue is because, the gradient passed back by the criterion is in table format { grad }. But the gradient required by the CAddTable is supposed to be in Tensor format. 

During the backward pass, the concat table is supposed to provide the gradients in Tensor format to the CAddTable right ? Why doesn't it do that?
Or is the error due to some other problem ?

**CODE**

1) Following is the model

    model = nn.Sequential()
    model:add(nn.SplitTable(1))
        c = nn.ConcatTable()
            part1 = nn.Sequential()
                part1:add(nn.NarrowTable(1,2))
                part1:add(nn.CAddTable())
            part2 = nn.Sequential()
                part2:add(nn.NarrowTable(3,1))
                part2:add(nn.CAddTable())
        c:add(part1)
        c:add(part2)
    model:add(c)
        crit = nn.CriterionTable(nn.MSECriterion())
    model:add(crit)

2) Following is the forward and backward pass

    criterion= nn.MSECriterion()
    x = torch.rand(3,2)
    y = torch.rand(1)
    pred = torch.Tensor({model:forward(x)})
    print(pred)
    local err=criterion:forward(pred,y)
    local gradCriterion = criterion:backward(pred,y)
    model:zeroGradParameters()
    model:backward(x, gradCriterion)

**ERROR**

/home/aalok/torch/install/share/lua/5.1/nn/Container.lua:69: 
In 2 module of nn.Sequential:
In 2 module of nn.ConcatTable:
In 2 module of nn.Sequential:
**/home/aalok/torch/install/share/lua/5.1/nn/CAddTable.lua:27: bad argument #1 to 'copy' (torch.*Tensor expected, got nil)**
stack traceback:
	[C]: in function 'copy'
	/home/aalok/torch/install/share/lua/5.1/nn/CAddTable.lua:27: in function 'updateGradInput'
	/home/aalok/torch/install/share/lua/5.1/nn/Module.lua:30: in function </home/aalok/torch/install/share/lua/5.1/nn/Module.lua:28>
	[C]: in function 'xpcall'
	/home/aalok/torch/install/share/lua/5.1/nn/Container.lua:65: in function 'rethrowErrors'
	/home/aalok/torch/install/share/lua/5.1/nn/Sequential.lua:84: in function </home/aalok/torch/install/share/lua/5.1/nn/Sequential.lua:78>
	[C]: in function 'xpcall'
	/home/aalok/torch/install/share/lua/5.1/nn/Container.lua:65: in function 'rethrowErrors'
	/home/aalok/torch/install/share/lua/5.1/nn/ConcatTable.lua:35: in function </home/aalok/torch/install/share/lua/5.1/nn/ConcatTable.lua:30>
	[C]: in function 'xpcall'
	...
	[string "criterion= nn.MSECriterion()..."]:12: in main chunk
	[C]: in function 'xpcall'
	/home/aalok/torch/install/share/lua/5.1/itorch/main.lua:179: in function </home/aalok/torch/install/share/lua/5.1/itorch/main.lua:143>
	/home/aalok/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
	/home/aalok/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
	/home/aalok/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
	/home/aalok/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
	/home/aalok/torch/install/share/lua/5.1/itorch/main.lua:350: in main chunk
	[C]: in function 'require'
	[string "arg={'/run/user/1000/jupyter/kernel-3b3c710d-..."]:1: in main chunk

**Comment by aalok1993** [comment]
I think the problem is with the CriterionTable.
The input to the CriterionTable is a table of Tensor as shown below

    {
      1 : DoubleTensor - size: 2
      2 : DoubleTensor - size: 2
    }

So after the backward pass the gradinput should also be of the same size right?
But the gradinput obtained is the following

    {
      1 : DoubleTensor - size: 2
    }

Shouldn't the input and gradinput be of the same size ?

**Comment by fmassa** [comment]
It seems that `CriterionTable` supposes that your second element from the input is the target, and thus should not be backpropagated. That's not the case in your situation.
You can change your model to get the desired behaviour:

```lua
-- define your model as before, but without the CriterionTable
-- and replace it by a PairwiseDistance
model:add(nn.PairwiseDistance(2))

criterion = nn.MSECriterion()
```

**Comment by aalok1993** [comment]
@fmassa : Thanks a lot. PairwiseDistance actually solves the issue for me.

On a side note, shouldn't CriterionTable treat both the tensors as input (instead of treating the second one as target). Because, if it treats both as input and send back the gradient for both of them, then we can use different types of error functions directly from the Criterions, without having to seperately make a nn.Layer_module each time.

**Comment by fmassa** [comment]
@aalok1993 sorry, I don't quite get your point. Isn't it the use case of [`MultiCriterion`](https://github.com/torch/nn/blob/master/doc/criterion.md#nn.MultiCriterion) and ['ParallelCriterion'](https://github.com/torch/nn/blob/master/doc/criterion.md#parallelcriterion) ?
About the behaviour of `CriterionTable`, you don't backpropagate through the targets (the derivatives are only computed wrt the input), and there is no option in the criterions to do that, so what you propose doesn't actually work with current `Criterion` implementations.

**Comment by aalok1993** [comment]
@fmassa : Oh sorry, I misunderstood it earlier. I get it now (that the implementation of `Criterion` wouldn't allow that type of usage). Thanks. 
I'll close the issue now.
