### ISSUE TITLE
method 'updateOutput' (a nil value) Error  !  When I try to do  criterion:forward(x1,1) 

### ISSUE THREAD

**Issue by amirkhango** [torch/nn#716]
I am doing test as this pic:

![lua_test](https://cloud.githubusercontent.com/assets/13656622/13836865/b816c5e8-ec40-11e5-946d-0364aada6f08.png)

That's ------------    /home/kudou/torch/install/share/lua/5.1/nn/Criterion.lua:12: attempt to call method 'updateOutput' (a nil value)

What's wrong?

**Comment by fmassa** [comment]
It should be
```lua
criterion:forward(x1,1)
```
Also, next time please post this kind of question in the google groups https://groups.google.com/forum/embed/?place=forum%2Ftorch7#!forum/torch7 as the github issues are used to track bugs.

**Comment by amirkhango** [comment]
@fmassa  That's OK.Thanks
Then would u like to tell me when I use "," or ":" ? I am very confused about these two characters.
And I'am not very clear about github issues zone and Google groups, which type problems can be issued to the github issues zone?

**Comment by korkinof** [comment]
':' is used for function member of class, '.' for accessing data within the object.
The examples are really helpful to infer how to use things and it's pretty easy really.

**Comment by amirkhango** [comment]
@korkinof  thx! I will
