### ISSUE TITLE
dilated convolution

### ISSUE THREAD

**Issue by fguney** [torch/nn#721]
How hard would it be to integrate dilated convolution from this paper: http://arxiv.org/pdf/1511.07122v2.pdf to the SpatialConvolution module?

**Comment by fmassa** [comment]
Not hard actually, just need to transfer the [these changes](https://github.com/BVLC/caffe/commit/93bfcb53120416255d6d7261b638f0b38ff9e9bf#diff-ce49df6c3a7ef14730eee5f5d1bf8e0bR30) to [here](https://github.com/torch/cunn/blob/master/lib/THCUNN/im2col.h#L21-L29) for the GPU version. The CPU version can be similarly handled.

**Comment by laky** [comment]
Hi, I'm just wondering whether there are any plans to add these dilations in convolutions to torch? Thanks.

**Comment by fguney** [comment]
I implemented it myself only for GPU version by modifying cunn. It's not that hard following the changes in caffe as @fmassa pointed out :) I think integrating it to torch is another issue, since cunn and nn are so interleaved, but I can try to help if it's going to happen.

**Comment by fmassa** [comment]
@fguney what about pushing your cuda dilated convolution to a separate repo at the moment? that could already help @laky and others who are looking for this function. What do you think ?

**Comment by soumith** [comment]
i'm going to do it today.

**Comment by fguney** [comment]
I guess that's a better solution, thanks :)

**Comment by laky** [comment]
Sounds really good! Thanks a lot, can't wait to use it :)

**Comment by Kaixhin** [comment]
Just happened to read the paper and noticed that Section 3 mentions that a special initialisation was needed to get good results. Is this something that should be addressed inside or outside of the `nn` repo? Would suggest a PR to [`nninit`](https://github.com/Kaixhin/nninit) if the latter. Not working on this myself so don't know how important the init is.

**Comment by apaszke** [comment]
I used dilated convolutions and they seemed to work fine without any custom initialization. Maybe that's because they were interleaved with other layers, instead of putting many of them in a sequence. Still, if anyone writes code for this scheme, it's probably worth trying it.
