### ISSUE TITLE
Recent update to nn doesn't let nn.SpatialFullConvolution run on GPU

### ISSUE THREAD

**Issue by anuragranj** [torch/nn#727]
Running on an old torch version, the following code works:

    th> im = torch.rand(3,384,512)
    th> cunn = require('cunn')
    th> nn = require('nn')
    th> fullconv = nn.SpatialFullConvolution(3,2,4,4,2,2,1,1)
    th> fullconv = fullconv:cuda()
    th> im = im:cuda()
    th> o = fullconv:forward(im)

Running the same code on the new version updated yesterday (for torch and nn packages using luarocks) gives the following error:

    th> im = torch.rand(3,384,512)
    th> cunn = require('cunn')
    th> nn = require('nn')
    th> fullconv = nn.SpatialFullConvolution(3,2,4,4,2,2,1,1)
    th> fullconv = fullconv:cuda()
    th> im = im:cuda()
    th> o = fullconv:forward(im)
    ...orch/install/share/lua/5.1/nn/SpatialFullConvolution.lua:74: attempt to call field     'SpatialFullConvolution_updateOutput' (a nil value)
    stack traceback:
	...orch/install/share/lua/5.1/nn/SpatialFullConvolution.lua:74: in function 'forward'
	[string "o = fullconv:forward(im)"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/aranjan/torch/install/share/lua/5.1/trepl/init.lua:669: in function 'repl'
	...njan/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670

**Comment by szagoruyko** [comment]
`luarocks install cunn`

**Comment by anuragranj** [comment]
That does it!
