### ISSUE TITLE
BCECriterion is not safe

### ISSUE THREAD

**Issue by clementfarabet** [torch/nn#730]
Anyone using it currently?

The output of the sigmoid (input to BCECriterion) should be capped so that we never see probabilities at 0 or 1 (log(0) or log(1-1) will get to inf). The module currently only forbids probs at 0, but not probs at 1 (although very rare because of the epsilon shift, they can still occur). 

https://github.com/torch/nn/blob/master/BCECriterion.lua#L46

For reference, this is what we do in the autograd version:
https://github.com/twitter/torch-autograd/blob/master/src/loss/init.lua#L28
(that's 100% safe).

cc @alexbw

**Comment by fmassa** [comment]
@clementfarabet could you provide a small test case illustrating this behaviour ? I quickly tried to reproduce it and I wasn't able to find a non-working case.
Also, a similar problem was addressed by https://github.com/torch/nn/pull/401 , are you on the latest `nn` ?

**Comment by soumith** [comment]
I used it in my lapgan paper, and we use it quite routinely. Why would the output of the sigmoid be more than 1? Never had issues with it the way it is now.

**Comment by clementfarabet** [comment]
So it happens in this case:

```lua
nn.BCECriterion():forward(torch.Tensor{1-1e12}, torch.Tensor{0})
```

which admittedly, is rare, but I actually hit it :-).

**Comment by clementfarabet** [comment]
Scratch that – can't repro, closing for now, I have to single out where my issue comes from.

**Comment by clementfarabet** [comment]
And yes I had an earlier version – the current one is fixed.
