### ISSUE TITLE
Parallel Table fails when input CudaTensor

### ISSUE THREAD

**Issue by ywu36** [torch/nn#757]
Here is a simple net: 

require 'nn'
require 'cutorch'

   local branches = nn.ParallelTable()

   branches:add(
   nn.Sequential()
      :add(nn.SpatialConvolution(3, 32, 4, 4))
      :add(nn.ReLU())
      :add(nn.SpatialMaxPooling(2, 2, 2 ,2):ceil())
      :add(nn.View(-1))
   )

   branches:add(
   nn.Sequential()
      :add(nn.SpatialConvolution(3, 32, 3, 3))
      :add(nn.ReLU())
      :add(nn.SpatialMaxPooling(2, 2, 2 ,2):ceil())
      :add(nn.View(-1))

   )

   local net = nn.Sequential()
      :add(branches)
      :add(nn.JoinTable(1))

local input  = { torch.CudaTensor(3, 10, 10), torch.CudaTensor(3, 10, 10) }
local output = net:forward(input)
print(#output)

---------------------------------------------------------------------------------------------------------------------------
Error:

Program starting as '"/opt/zbstudio/bin/linux/x64/lua" -e "io.stdout:setvbuf('no')" "/home/yuhang/GitRepos/ECCV16-YW/MyCoreCode/landmark_detector_training/Deep_trainer/test.lua"'.
Program 'lua' started in '/home/yuhang/GitRepos/ECCV16-YW/MyCoreCode/landmark_detector_training/Deep_trainer' (pid: 14618).
/opt/zbstudio/bin/linux/x64/lua: /home/yuhang/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
In 1 module of nn.ParallelTable:
In 1 module of nn.Sequential:
...ng/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:104: attempt to index field 'THNN' (a nil value)
stack traceback:
	...ng/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:104: in function <...ng/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:100>
	[C]: in function 'xpcall'
	/home/yuhang/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/yuhang/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/yuhang/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	/home/yuhang/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	.../yuhang/torch/install/share/lua/5.1/nn/ParallelTable.lua:12: in function <.../yuhang/torch/install/share/lua/5.1/nn/ParallelTable.lua:10>
	[C]: in function 'xpcall'
	/home/yuhang/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/yuhang/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	...oreCode/landmark_detector_training/Deep_trainer/test.lua:33: in main chunk
	[C]: at 0x004054e8

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/yuhang/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/yuhang/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	...oreCode/landmark_detector_training/Deep_trainer/test.lua:33: in main chunk
	[C]: at 0x004054e8
Program completed in 0.38 seconds (pid: 14618).

-------------------------------------------------------------------------------------------------------------------------------
**However, the program returns 1024 if I changed the torch.CudaTensor to torch.DoubleTensor**

**Comment by apaszke** [comment]
I think you forgot to `require 'cunn'`

**Comment by ywu36** [comment]
Thanks for a quick reply. The issue remains after I added it.

**Comment by apaszke** [comment]
Oh, you also forgot to send your network to a GPU. Add `net:cuda()` before calling forward.

**Comment by ywu36** [comment]
Cool ! It solved the issue. Thank you so much Apaszke ~

**Comment by ywu36** [comment]
I meet another problem, when I tried to train the network using mini-batch with the input:

input  = { torch.rand(**32**, 3, 10, 10), torch.rand(**32**, 3, 10, 10) }


  it reports an error like this:

/opt/zbstudio/bin/linux/x64/lua: /home/yuhang/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
In 1 module of nn.ParallelTable:
In 11 module of nn.Sequential:
/home/yuhang/torch/install/share/lua/5.1/nn/Linear.lua:51: size mismatch at /tmp/luarocks_cutorch-scm-1-5316/cutorch/lib/THC/THCTensorMathBlas.cu:36
stack traceback:
	[C]: in function 'addmv'
	/home/yuhang/torch/install/share/lua/5.1/nn/Linear.lua:51: in function </home/yuhang/torch/install/share/lua/5.1/nn/Linear.lua:47>
	[C]: in function 'xpcall'
	/home/yuhang/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/yuhang/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/yuhang/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	/home/yuhang/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	.../yuhang/torch/install/share/lua/5.1/nn/ParallelTable.lua:12: in function <.../yuhang/torch/install/share/lua/5.1/nn/ParallelTable.lua:10>
	[C]: in function 'xpcall'
	/home/yuhang/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/yuhang/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	.///core_detector.lua:62: in function 'opfunc'
	/home/yuhang/torch/install/share/lua/5.1/optim/nag.lua:55: in function 'nag'
	.///core_detector.lua:76: in function 'core_detector'
	...tector_training/Deep_trainer/train_detector_left_eye.lua:58: in function 'training'
	...tector_training/Deep_trainer/train_detector_left_eye.lua:72: in main chunk
	[C]: at 0x004054e8

Any idea how to train it with mini-batch ?

**Comment by RuiShu** [comment]
You hard-code the assumption that you're feeding non-batch data into your network. I've adjusted your code (see bold) so that it works with batch data. These questions are best suited for stackoverflow.

require 'nn'
require 'cutorch'
**require 'cunn'**

local branches = nn.ParallelTable()

branches:add(
   nn.Sequential()
      :add(nn.SpatialConvolution(3, 32, 4, 4))
      :add(nn.ReLU())
      :add(nn.SpatialMaxPooling(2, 2, 2 ,2):ceil())
      **:add(nn.View(512))**
)

branches:add(
   nn.Sequential()
      :add(nn.SpatialConvolution(3, 32, 3, 3))
      :add(nn.ReLU())
      :add(nn.SpatialMaxPooling(2, 2, 2 ,2):ceil())
      **:add(nn.View(512))**
)

local net = nn.Sequential()
   :add(branches)
   **:add(nn.JoinTable(1,1))**

**net:cuda()**

local input = {torch.CudaTensor(32, 3, 10, 10), torch.CudaTensor(32, 3, 10, 10)}
local output = net:forward(input)
print(#output)

**Comment by ywu36** [comment]
It works ~ thank you so much !

**Comment by soumith** [comment]
Next time, could you post stuff like this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking. We'll happily reply there. Thanks.
