### ISSUE TITLE
How do I figure out the size of a network?

### ISSUE THREAD

**Issue by mbchang** [torch/nn#764]
Is there a method that I can call on an nn.Module to find out how much space it takes in memory?

**Comment by soumith** [comment]
there isn't such a method, and we do not plan to provide one.

**Comment by jonathantompson** [comment]
But this would be nice though :-) I have hacky code... but baking flops and memory requirements into torch proper would be useful.

**Comment by soumith** [comment]
there's not an obvious way to do it because of variable input size modules like Spatial*. We've definitely thought about doing it, but couldn't find a good way.

This repo here has some memory measurement etc. https://github.com/fmassa/optimize-net

**Comment by jonathantompson** [comment]
Yeah makes sense.... But the function could have an input as part of its signature (that's what I do).

**Comment by mbchang** [comment]
I'm getting a cuda memory error 

```
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-3786/cutorch/lib/THC/generic/THCStorage.cu line=41 error=2 : out of memory
/om/user/mbchang/torch/install/bin/luajit: /om/user/mbchang/torch/install/share/lua/5.1/torch/File.lua:351: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-3786/cutorch/lib/THC/generic/THCStorage.cu:41
```
when trying to clone a network. I'm trying to debug it, and so far running ```collectgarbage("count")``` is the only method I know of viewing network memory. Is there a better way to do this?

**Comment by soumith** [comment]
@mbchang https://github.com/fmassa/optimize-net might help.

**Comment by mbchang** [comment]
Thanks
