### ISSUE TITLE
[feature request] relaxing the restriction of nn.Linear

### ISSUE THREAD

**Issue by iamalbert** [torch/nn#774]
For now `nn.Linear` only accept 1D or 2D tensors as input. It would be better if its batch-mode can deal with 3D and 4D tensors. That is, a relaxed `nn.Linear(n,m)` can transform a tensor of dimension `p x q x n` into another tensor of `p x q x m`, and likewise `p x q x r x n` into `p x q  x r x m`.

This is useful when processing sequences. For example, suppose I have a tensor of `N x T x D` (representing a mini-batch of `N` sequences, each having `T` vectors of `D`-dimension), and I want an extra abstraction of all the vectors. If `N` and `T` are variable among instances, this cannot be done by adding `nn.View` before/after the linear module, but the relaxed version of `nn.Linear(D,D2)` can make it.

What do you think about this suggestion? If I want to send a PR, should I change the implementation of `nn.Linear` or add a new module like `nn.GeneralizedLinear` or something?

**Comment by JoostvDoorn** [comment]
I think this use case exists with many other modules as well. In @nicholas-leonard's RNN package you have `nn.Sequencer()` that can be used on tables, it is more advanced as it also allows for use with RNNs. It might make sense to have a Container that can do the same just on tensors.

**Comment by iamalbert** [comment]
yes, but using `nn.Sequencer` introduces too much overhead

**Comment by szagoruyko** [comment]
I think it would be useful to have this, but should be a separate from nn.Linear module that wraps it. Can't think of a good name now.

**Comment by nicholas-leonard** [comment]
So like @iamalbert mentioned, you can do this by encapsulating the input module with two `nn.View` instances : 
```lua
seqlinear = nn.Sequential()
   :add(nn.View(p*q*r,n))
   :add(nn.Linear(n,m))
   :add(nn.View(p,q,r,m))
```
But this will not support varying values of p, q, r, etc... Such that I agree with @iamalbert that this would be a useful module. 

It could be done by simply by inheriting a `nn.Linear` module where the above view changes are applied manually before and after calling the `nn.Linear.updateOutput` : 

```lua
local SeqLinear, parent = torch.class("nn.SeqLinear", "nn.Linear")
function SeqLinear:updateOutput(input)
   input = input:view(...) -- squash the first dims
   parent.updateOutput(input)
   self.output = self.output:view(...) -- unsquash
   return self.output
end
```

But then we would end up needing to do this for other modules like `SpatialConvolution`, etc... 

The third option could be to implement a general purpose decorator that takes as argument the number of input dims (that do not need to be bottled/unbottled) and a module to decorate (like `nn.Linear`, `nn.SpatialConvolution`, etc.) : 
```lua
local Bottle, parent = torch.class("nn.Bottle", "nn.Container")

function Bottle:__init(module, ninputdim)
   parent.__init(self)
   self.ninputdim = ninputdim
   -- add module to modules
   self.modules[1] = module
end

function Bottle:updateOutput(input)
   -- bottle the first dims
   local size = ...
   input = input:view(...)
   local output = self.modules[1]:updateOutput(input)
   -- unbottle
   self.output = output:view(size...)
end
```

So I vote for option 3. I like Bottle for the name, but I haven't really considered alternatives, so feel free to...

**Comment by iamalbert** [comment]
Thanks @nicholas-leonard ,
I think option 3 is better than creating a new module like I requested.

**Comment by shawnjhenry** [comment]
I have something of a work-around for this that I mentioned in an issue but never got around to making a PR.  I have a custom module I call nn.Tensordot that exactly implements the torch version of the numpy tensordot op - the generalized dot product between two tensors of any dimension along any sequence of pairs of axes that have the same size.  The relaxed version of nn.Linear being discussed is actually just a special case where the first tensor is a matrix (of parameters for the module).  Currently nn.Tensordot takes two inputs like nn.MM, but it would be easy to make a version that allows for a tensor of arbitrary dimension as parameters and takes inputs of the appropriate size.  Would this be of interest?

**Comment by JoostvDoorn** [comment]
@shawnjhenry You shouldn't have to pass weights to a nn module though, these should be parameters of the module. Or maybe I misunderstood your suggestion?

**Comment by shawnjhenry** [comment]
@JoostvDoorn I think you are misunderstanding my comment.  What I said was the that the module as I use it takes two arguments like nn.MM, but that it would be very easy to modify so that it only takes one argument and has a tensor of parameters like the weight in nn.Linear, except that it could have arbitrarily many dimensions and would take an additional argument in init specifying the sequence of dimensions along which we want to take the tensor dot product of the parameter tensor with the input.

**Comment by JoostvDoorn** [comment]
I opened a pull request for option 3.
