### ISSUE TITLE
save_mean and save_var get lost when checkpointing

### ISSUE THREAD

**Issue by cbarokk** [torch/nn#788]
Hi,
When I checkpoint my model, it seems the *save_mean* and *save_var* tensors get lost (not part of the *model.forwardnodes.node.data.module*). So that when I restore a checkpoint, the *evaluate()* mode does not work.
I guess people have used this module with checkpoints successfully, so I wonder what I am missing.
Thanks.
Cyril

**Comment by fmassa** [comment]
In evaluate mode, what is used is [`running_mean` and `running_var`](https://github.com/torch/nn/blob/master/lib/THNN/generic/BatchNormalization.c#L50-L51) (the average mean/var over all the batches so far), so everything is fine (as those quantities are not erased during save).
