### ISSUE TITLE
SparseLinear:accGradParameters wrong multithreaded behavior?

### ISSUE THREAD

**Issue by nkoumchatzky** [torch/nn#790]
#789 is a test that passes with OMP_NUM_THREADS=1, but not otherwise with OMP + OpenBlas (or MKL, for that matter). The OMP statement in the SparseLinear.c accGradParameters function makes concurrent updates of gradWeight possible if the same index occurs multiple times in the input. The legacy code should be wrong too. Anything I missed?

EDIT: the behavior we get out of this will make the algo converge eventually as it amounts to doing "hogwild" updates. But it should at least be an option.

**Comment by soumith** [comment]
no, the multi-threaded OMP based aggregator made a tradeoff on correctness if i remember. I did ask @ebetica to do a tree reduction so that the gradients are exactly correct and aggregation is not bottlenecked by mutexes, i cant remember from memory whether he finished that.

**Comment by ebetica** [comment]
#722, I never got around to it. If it's urgent for you I'll make it a priority to fix.

**Comment by zhangxiangxiao** [comment]
This is less of a worry for most cases so far, because we would have used Hogwild anyway for any practical CPU application. But exact gradients would have been nice. If your data is in batch mode, IIRC the GPU version by @ebetica should be good.

**Comment by nkoumchatzky** [comment]
Thanks @soumith! I'm ok to leave it as is, but people should be aware of it. And ideally, we could implement it correctly indeed (cc @ebetica: thanks for all these implementations btw).
@zhangxiangxiao we don't really need GPU for sparse linear in general, and the issue can also arise in non-batch mode. I agree we can go hogwild, but I like to control how "hogwild" I go :)
