### ISSUE TITLE
Layer-wise Relevance Propagation Module

### ISSUE THREAD

**Issue by jkschin** [torch/nn#793]
http://arxiv.org/pdf/1509.06321v1.pdf

Visualization tools are important in neural network research. I think this module would be a great addition to Torch. I'm new to torch and would like to implement this module or perhaps get some help in implementing such a module. A summary of what needs to be done:

1) Train a neural network.
2) Forward propagate and save the activations of each neuron.
3) Backpropagate the relevance score according to an equation (skip ReLU, max unpool)
4) Plot a heatmap of relevance scores.

**Comment by jrieke** [comment]
@jkschin Did you try anything in that direction or have any ideas/approaches how it might be possible in pytorch? Want to do this myself for a project.
