### ISSUE TITLE
Support for Intel Compilers?

### ISSUE THREAD

**Issue by fmassa** [torch/nn#794]
There seems to be an issue with current CMakeLists for Intel compilers.
Recently, [C99 became a requirement for `nn`](https://github.com/torch/nn/pull/550), but it seems that the current [CMakeLists is not robust enough to handle Intel compilers](https://groups.google.com/forum/#!topic/torch7/09XXTMMj84w) (it looks like it requires the flag to be `-std=c99` instead of `--std=c99`).

Do we support intel compilers? If yes, it seems that we need to fix the CMakeLists to handle this particular case.

**Comment by soumith** [comment]
yes we want to, and the patch seems really small to incorporate. can you send in a PR?

**Comment by fmassa** [comment]
Sure, will send a PR later today or tomorrow.

**Comment by fmassa** [comment]
Fixed via https://github.com/torch/nn/pull/799
