### ISSUE TITLE
installation error: 'shfl-down'

### ISSUE THREAD

**Issue by lifengjin** [torch/nn#801]
Was installing CUNN and got this (CUTORCH installed fine.):

/tmp/luarocks_cunn-scm-1-3280/cunn/lib/THCUNN/SpatialClassNLLCriterion.cu(16): error: identifier "__shfl_down" is undefined

1 error detected in the compilation of "/tmp/pbstmp.6641547/tmpxft_000055a9_00000000-7_SpatialClassNLLCriterion.cpp1.ii".
CMake Error at THCUNN_generated_SpatialClassNLLCriterion.cu.o.cmake:264 (message):
  Error generating file
  /tmp/luarocks_cunn-scm-1-3280/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_SpatialClassNLLCriterion.cu.o

make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/./THCUNN_generated_SpatialClassNLLCriterion.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by soumith** [comment]
what version of CUDA are you using?

**Comment by szagoruyko** [comment]
seems that SpatialClassNLLCriterion breaks pre-kepler compatibility

**Comment by soumith** [comment]
oooh, cc: @apaszke

**Comment by apaszke** [comment]
Yes I have just realized this. It can be fixed by using 2 blockReduce calls in updateOutput, instead of using __shfl intrinsics there. I won't have access to my computer until tomorrow evening. Sorry!

**Comment by apaszke** [comment]
But it should be very straightforward to fix it, if you could take a look

**Comment by lifengjin** [comment]
Seems to work now. Closing this.
