### ISSUE TITLE
nn not working

### ISSUE THREAD

**Issue by prov3it** [torch/nn#803]
Hi,

When running: _th -lnn    -e "nn.test()"_ i get multiple errors, however nn did install without any errors. Im lost, can anybody help me out?
```

not found: THNN_FloatAbs_updateOutput/usb2/torch/install/share/lua/5.2/nn/THNN.lua:107: internal error: missing link for to_typed_pointer

not found: THNN_FloatAbsCriterion_updateOutput/usb2/torch/install/share/lua/5.2/nn/THNN.lua:107: NYI: call arg type
```

I got about 120 lines more with the same kind of errors.

**Comment by nitish11** [comment]
@prov3it : Any lead ??
I got similar error on my device.
 Linux raspberrypi 4.4.15-v7+ #897 SMP armv7l GNU/Linux

**Comment by nitish11** [comment]
The issue was in installation of Torch. Install torch using following instructions.
```
rm -rf ~/torch

# in a terminal, run the commands WITHOUT sudo
git clone https://github.com/torch/distro.git ~/torch --recursive
./clean.sh
./install.sh

# On Linux with bash
source ~/.bashrc

luarocks install nn
luarocks install dpnn
```

Test torch installation using :

` th -lnn -e "nn.test()"`

**Comment by nicholas-leonard** [comment]
@nitish11 Can you provide the stacktrace or error report?

**Comment by nitish11** [comment]
@nicholas-leonard  : I resolved the issue by following torch installation mentioned in the above steps.
thanks.
