### ISSUE TITLE
Low SoftMax precision?

### ISSUE THREAD

**Issue by MatejNikl** [torch/nn#804]
```
require 'nn'
local input = torch.Tensor{-5.2040, 7.8325}

print("LogSoftMax:")
print(nn.LogSoftMax():forward(input))

print("SoftMax + Log:")
print(nn.SoftMax():forward(input):log())

print("SoftMax:")
print(nn.SoftMax():forward(input))

print("LogSoftMax + Exp:")
print(nn.LogSoftMax():forward(input):exp())
```
gives
```
LogSoftMax:	
-13,0365
  0,0000
[torch.DoubleTensor of size 2]

SoftMax + Log:	
       -inf
 0,0000e+00
[torch.DoubleTensor of size 2]

SoftMax:	
 0
 1
[torch.DoubleTensor of size 2]

LogSoftMax + Exp:	
 2,1793e-06
 1,0000e+00
[torch.DoubleTensor of size 2]
```
I don't think this is a correct behavior or am I missing something?

It was a great pain to debug (for a beginner Torch user), since they should give equivalent outputs (as [this comment](https://github.com/torch/nn/issues/357#issuecomment-135522916) states as well) and when a model gets more confident (and outputs e.g. the provided Tensor), "suddenly" weights become all NaNs (because gradient consequently goes to Inf as well).

**Comment by fmassa** [comment]
The guilty in here I think is the [approximate exponential](https://github.com/torch/torch7/blob/master/lib/TH/THLogAdd.c#L58) in [SoftMax](https://github.com/torch/nn/blob/master/lib/THNN/generic/SoftMax.c#L67). `LogSoftMax` [used to use this approximation](https://github.com/torch/nn/commit/4438ec99b8ed74c1b5691b4eea12e66216e8be07#diff-b7ec32765cda659d15e923ddf3401741R49) as well, but it was recently removed to use `exp`.
The proposed fix is in https://github.com/torch/nn/pull/805

**Comment by MatejNikl** [comment]
Alright, thanks for the fix!
