### ISSUE TITLE
Bug for "MarginRankingCriterion.lua" Batch Mode

### ISSUE THREAD

**Issue by todpole3** [torch/nn#813]
The current version returns the following error if a batch of size "1" is passed, since the code has a condition branch that treats a size-1 batch as a number (while in fact it is a tensor).

> torch/install/bin/luajit: ...orch/install/share/lua/5.1/nn/MarginRankingCriterion.lua:13: bad argument #2 to 'max' (number expected, got userdata)

**Comment by soumith** [comment]
Thanks for the bug report. Fixed via commit: https://github.com/torch/nn/commit/f9be7619272577a2a98d482b284cabe8bc2dfebe
