### ISSUE TITLE
[feature request] merging Sequential containers

### ISSUE THREAD

**Issue by RuiShu** [torch/nn#817]
Is there value in creating a functionality such that containers can be merged? I was looking at https://github.com/szagoruyko/cifar.torch/blob/master/models/vgg_bn_drop.lua#L6 and noticed the way in which they were defining ConvBNReLU as a convenience layer breaks the style of adding torch layers:
```
ConvBNReLU(3,64):add(nn.Dropout(0.3))
ConvBNReLU(64,64)
vgg:add(MaxPooling(2,2,2,2):ceil())
```

I think a more stylistically consistent approach would be if the following were allowed i.e.:
```
local function ConvBNReLU(nInputPlane, nOutputPlane)
  model = nn.Sequential()
  model:add(nn.SpatialConvolution(nInputPlane, nOutputPlane, 3,3, 1,1, 1,1))
  model:add(nn.SpatialBatchNormalization(nOutputPlane,1e-3))
  model:add(nn.ReLU(true))
  return model
end

model = nn.Sequential()
model:merge(ConvBNReLU(3,64))
model:merge(ConvBNReLU(64,64))
```
where the merge functionality iteratively adds the modules from sequential module B to sequential module A when doing `A:merge(B)`. The closest alternative would be to do:
```
model = nn.Sequential()
model:add(ConvBNReLU(3,64))
model:add(ConvBNReLU(64,64))
```
But that creates unnecessary nesting of sequential modules. Or if there are better ways of making convenience layers on-the-fly, please let me know too.

Thanks!

**Comment by iamalbert** [comment]
you can pass the container as an argument into `ConvBNReLU`, where you can then add the modules. 
```lua
local function ConvBNReLU(model, nInputPlane, nOutputPlane)
  model:add(nn.SpatialConvolution(nInputPlane, nOutputPlane, 3,3, 1,1, 1,1))
  model:add(nn.SpatialBatchNormalization(nOutputPlane,1e-3))
  model:add(nn.ReLU(true))
  return model
end
```

However if you want to construct deep, complex, and modularized network, you should definitely try [nngraph](https://github.com/torch/nngraph).

**Comment by RuiShu** [comment]
nngraph feels like too much overhead for this particular task. And what you've proposed has been my current solution. I was hoping to be able to preserve the `foo:func(bar)` syntax for combining layers and wanted to know if anyone else had this desire. If not, I'll close this request.

Thanks!

**Comment by fmassa** [comment]
I think this `merge` function will only really exist for sequential containers, as all other containers are not equivalent if we do this merging, i.e., merging two concats or parallels, right?

What are the use-cases of having all modules flattened in a single `nn.Sequential`? Easily removing the absolute `n`th layer/inserting in the absolute `k`th position? Or for visualization ?

I somewhat faced this when working on the [graph visualizations of `optnet`](https://github.com/fmassa/optimize-net#visualizing-the-memory-reuse), but this could easily be bypassed in that case.

I tend to think that current functionality is enough for model construction though... but others might think differently.

**Comment by RuiShu** [comment]
Thanks for your thoughts on the matter, guys. Since the functionality is limited in scope and isn't urgent, I will close this issue.
