### ISSUE TITLE
Small Problem in the Lookup Table Documentation

### ISSUE THREAD

**Issue by RishabhMalviya** [torch/nn#828]
I think the matrix multiplication analogy is wrong in the documentation for the nn.LookupTable documentation (https://github.com/torch/nn/blob/master/doc/convolution.md#nn.LookupTable). 

It isn't a major problem, just that the actual output of the forward operation is the transpose of that shown in the documentation.   
`(M P)'`  

It's not a major problem, but if you're nit-picky about mathematical details like me, it gets to you.

**Comment by nicholas-leonard** [comment]
@RishabhMalviya Could you send a PR?

**Comment by RishabhMalviya** [comment]
[Done](https://github.com/torch/nn/pull/831)

**Comment by BhargavaRamM** [comment]
I just want to mention one very small documentation mistake in nn.Bilinear. According to the documentation, the input tensor given in forward(input) is a table containing both inputs x_1 and x_2, which are tensors of size N x inputDimension1 and N x inputDimension1, respectively. It is supposed to be  N x inputDimension1 and N x inputDimension2. 

[https://github.com/torch/nn/blob/master/doc/simple.md#nn.Bilinear](url)

**Comment by soumith** [comment]
@BhargavaRamM thanks, fixed via https://github.com/torch/nn/commit/a81143f095c2aeb897f3f043699d10d0c4a96375
