### ISSUE TITLE
Allow SplitTable to split tensor on user-determined size

### ISSUE THREAD

**Issue by RuiShu** [torch/nn#837]
The following issue came up on https://groups.google.com/forum/#!topic/torch7/HehYJTG-s4E
I've encountered similar issues in the past when working on VAEs, when it is desirable to split a tensor of size Nx(2*C)xHxW into two tensors of size NxCxHxW. 

I think it would be nice if SplitTable were instead to behave like this: https://gist.github.com/RuiShu/c06423f78bd26f243e027da83769300d

The "downside" is that, unlike the existing SplitTable, the proposed alternative does not squeeze the function along the dimension of interest. But this isn't necessarily a bad thing, as this will finally allow SplitTable to behave more like the reverse of JoinTable, thus allowing the following to be possible:

```lua
x = torch.rand(2,4,4,5)
split = nn.SplitTable(1,3)
join = nn.JoinTable(1,3)
y  = join:forward(split:forward(x))
print(x:eq(y):all()) -- false with current SplitTable, true with proposed implementation
```

**Comment by clement-masson** [comment]
I also faced the same need "to split a tensor of size Nx(2*C)xHxW into two tensors of size NxCxHxW"

At the beginning I implemented a nn.SplitNTable(dimension, nInputDim) module (notice the 'N' in the module name) to control the size N of the output tensors along splitting dimension.
Then I realized there was an already existing, not that complex, way of doing it:
 
`half_splitter = nn.Sequential():add(nn.View(-1,2,C,H,W)):add(nn.SplitTable(1,4))`

example:
```
th> C,H,W = 3,4,4
th> half_splitter = nn.Sequential():add(nn.View(-1,2,C,H,W)):add(nn.SplitTable(1,4))
th> x = torch.Tensor(16,2*C,H,W)
th> half_splitter:forward(x)
{
  1 : DoubleTensor - size: 16x3x4x4
  2 : DoubleTensor - size: 16x3x4x4
}
```

**Comment by RuiShu** [comment]
Good point!
