### ISSUE TITLE
Squeeze.lua:25: bad argument #1 to 'set' 

### ISSUE THREAD

**Issue by DylanAuty** [torch/nn#846]
Hi,

I've had a look for similar open issues but found nothing, though I have found [This previously closed issue](https://github.com/torch/nn/issues/502) which details a similar problem with nn.Identity().
I'm having issues using the Squeeze module. It seems to be related to the type of input. The following works fine:
```
net = nn.Sequential()
net:add(nn.Squeeze(3))
in1 = torch.DoubleTensor(1, 1, 1, 10)
net:forward(in1)
```
Returning a `[torch.DoubleTensor of size 1x1x10]`.

However, the same thing with either `in1 = torch.LongTensor(1, 1, 1, 10)` or `in1 = torch.ByteTensor(1, 1, 1, 10)` doesn't work, which is bizarre since the error message thrown is seemingly unrelated to the input type:
```
Squeeze.lua:26: bad argument #1 to 'set' (expecting number or torch.DoubleTensor or torch.DoubleStorage at /tmp/luarocks_torch-scm-1-9064/torch7/generic/Tensor.c:1125)
```
To confuse things further, I am using a modified version of [torch-rnn](https://github.com/jcjohnson/torch-rnn), and attempting to sample a checkpoint even with a forcibly inserted DoubleTensor instead of a ByteTensor is yielding a similar issue (the type was checked by inserting a line into Squeeze.lua, printing out the input).

Is there a known solution to this problem? My apologies if this has already been solved!

Thanks!

**Comment by fmassa** [comment]
Yes, you need to convert the module type to the input type of the data (as is usual in `nn`, if your data is float your model should be float as well).
You can do it by calling
```lua
net:type('torch.LongTensor')
```

or you can convert only the squeeze module to the desired type, or add a `nn.Copy` module to do the conversion for you

**Comment by DylanAuty** [comment]
Hi, thank you so much for your response! I can't believe I missed that, it seems to be working now. Thank you again!

**Comment by michaelholm-ce** [comment]
I believe I'm having the same error as outlined here (see above DIGITS issue #1187).  I have tried inserting a statement like ```net:type('torch.DoubleTensor')``` into my model architecture file, but I'm probably putting it in the wrong place.  I tried putting it after both ```local net = nn.Sequential()``` lines in the model definition file shown in the DIGITS issue #1187 linked above.  

Will one of you @DylanAuty or @fmassa please advise me on where to place that line in the torch definition file?

**Comment by fmassa** [comment]
There is a bug in your code, you don't pass the right number of arguments to your createModel function call. Except from that, I don't see any problem with the model definition
