### ISSUE TITLE
no KMax layer

### ISSUE THREAD

**Issue by shuzi** [torch/nn#848]
Hi ,  it seems that there is no Kmax layer in Torch nn package,  is that ture?

**Comment by fmassa** [comment]
What do you mean by Kmax, a layer similar to what topk does ?
If you need something like that, I wrote a simple function to do it some time ago, but I haven't written unit tests so use with care https://github.com/fmassa/torch-nn/blob/master/TopK.lua

**Comment by shuzi** [comment]
Thanks!  I am just starting to a layer using the same torch.topk as you did!
