### ISSUE TITLE
License problem: please remove doc/image/lena.jpg

### ISSUE THREAD

**Issue by CDLuminate** [torch/nn#854]
NN is distributed under BSD license however `lena.jpg` is not free.

According to Debian's policy checker:
```
lua-torch-nn source: license-problem-non-free-img-lenna doc/image/lena.jpg

The given source file is cropped from playboy centerfold.

This image is a picture of Lena S�derberg, shot by photographer Dwight
Hooker, cropped from the centerfold of the November 1972 issue of
Playboy magazine.

According to Hutchison, Jamie (May-June 2001). "Culture, Communication,
and an Information Age Madonna" (PDF). IEEE Professional Communication
Society Newsletter 45 (3). (page 5 second column second paragraph), this
image is distributable but not free.

Moreover, Lenna photo has been pointed to as an example of sexism in the
sciences, reinforcing gender stereotypes.

Please use well known and free test images.
```

**Comment by soumith** [comment]
while i would like to, there are likely downstream unit tests based on this image that would break. I dont want to break userland.

**Comment by CDLuminate** [comment]
Understand. I searched the code and find this:
```
$ ack lena
doc/convolution.md
775:lena = image.rgb2y(image.lena())
778:processed = m:forward(lena)
779:w1=image.display(lena)
782:![](image/lena.jpg)![](image/lenap.jpg)
```
I think only the doc needs `lena.jpg`, and unit test `test.lua` involves no `lena.jpg` test.

lena is a good example for CV people but in order to meet the legal requirement, I have to deal with this image downstream, deleting it and breaking the document integrity. Could you please consider an alternative free test image?

**Comment by nicholas-leonard** [comment]
We could just replace lena.jpg with a creative commons image of the same
size (and still call it lena.jpg). I don't think any unit tests rely on the
exactness of the image being lenna.

Nicholas Léonard
917-741-7570

**Comment by CDLuminate** [comment]
@nicholas-leonard @soumith 

I thinks there are only two points related to `lena`:  
1. the document uses `lena.jpg` as original example image  
2. the document uses `lenap.jpg`, as convolution output example image.

So expected changes are 2. I can do them if you dicide which picture to use.

**Comment by fmassa** [comment]
We will then face the same problem with `image`, right? There are several images there, including lena https://github.com/torch/image/tree/master/assets

**Comment by CDLuminate** [comment]
@fmassa I'm afraid yes. `lena` is a high-frequency trouble maker in Debian community: we reported similar lena-removal requests to e.g. `python-skimage` to avoid their debian packages being removed from official release.

https://github.com/scikit-image/scikit-image/issues/1855  
https://github.com/scikit-image/scikit-image/issues/2091#issuecomment-220156849

**Comment by CDLuminate** [comment]
we can use an alternative image and temporarily create a symbol link `lena.jpg -> free_test_image.jpg`

**Comment by CDLuminate** [comment]
I had a quick look at `image`, and I think I may simply remove `lena.jpg` and `lena.png`, and patch the `image.lena()` function to make it return a `randn(lena_image_size)` Tensor and explain the reason of removing it, because in this package `lena` picture is used in unit test.

**Comment by andreaskoepf** [comment]
So I will have to go to wikipedia's [lena image](https://en.wikipedia.org/wiki/Lenna), or [www.lenna.org](http://www.cs.cmu.edu/~chuck/lennapg/lenna.shtml) and download that to do some standard testing? To replace lena with a different natural image (as suggested by @nicholas-leonard ) would be ok IMO but please not by random values.

**Comment by CDLuminate** [comment]
@andreaskoepf I think I should print the true lena image link in the modified `image.lena()` function. Random noise is the simplest solution but I know its meaningless for image processing or anything else, however I don't know what image is both `well-known test image` and `free image`.

https://en.wikipedia.org/wiki/Standard_test_image

Debian logo is CC/LGPL licensed but I think it's a bad option here.
https://www.debian.org/logos/

**Comment by nicholas-leonard** [comment]
That standard image should do the trick.

Nicholas Léonard
917-741-7570

**Comment by soumith** [comment]
I'll change it tomorrow

**Comment by CDLuminate** [comment]
@nicholas-leonard did you mean the image in this page:
https://en.wikipedia.org/wiki/Standard_test_image
which is a sample from USC-SIPI dataset?

Well with a closer look I found that this image is indeed available for this purpose:
the picture `jelly beans` https://en.wikipedia.org/wiki/File:SIPI_Jelly_Beans_4.1.07.tiff
lies in section 4.1.07, 4.1.08 of that dataset and is free to use.
http://sipi.usc.edu/database/copyright.php

How do you like this solution?
replace lena image with jelly bean, keeping the filename `lena.jpg`, and update corresponding convolution output `lenap.jpg`.

**Comment by nicholas-leonard** [comment]
Yeah I mean the Standard_test_image.

**Comment by soumith** [comment]
fixed via https://github.com/torch/image/commit/797fcb101b76c9b329b3ee83349b0f6adeacac94

following Matplotlib and Pillow to add grace hopper instead
https://github.com/matplotlib/matplotlib/pull/1581

**Comment by CDLuminate** [comment]
Thanks for fixing it!

**Comment by chrisranderson** [comment]
I think it would be best if any references to Lena in this repo were removed because of its pornographic (and thus objectification of women, all-other-bad-things-about-pornography-here) origins. Is this possible?

**Comment by soumith** [comment]
we've removed lena. we cant change the name because of breaking API. See: https://github.com/torch/image/commit/797fcb101b76c9b329b3ee83349b0f6adeacac94

Hopefully we consider the topic closed here.
