### ISSUE TITLE
Error using encoder-decoder with cuda

### ISSUE THREAD

**Issue by satwikkottursc** [torch/nn#856]
I tried using the encoder-decoder-coupling example with cunn using `opt.useSeqLSTM=false` and added the lines:
```
require 'cutorch'
require 'cunn'
enc = enc:cuda();
dec = dec:cuda();
criterion = criterion:cuda();
encInSeq = encInSeq:cuda();
decInSeq = decInSeq:cuda();
decOutSeq = decOutSeq:cuda();
```
I have also changed [Line 111](https://github.com/Element-Research/rnn/blob/master/examples/encoder-decoder-coupling.lua#L111) to `local zeroTensor = torch.CudaTensor(encOut):zero()`.

It throws me the following error:
```
symbol lookup error: <path>/torch/install/lib/lua/5.1/libTHCUNN.so: undefined symbol: THC_overlappingIndices
```

I am using CudNN 5 with CUDA v7.5. What am I missing ? Thanks.

**Comment by soumith** [comment]
that error means update your cutorch and cunn:

luarocks install cutorch
luarocks install cunn
