### ISSUE TITLE
Feature Request: Dilated Convolution and Pooling

### ISSUE THREAD

**Issue by psicalculus** [torch/nn#862]
Could you please add VolumetricDilatedConvolution to torch nn?
Also, could you please add dilated pooling (VolumetricDilatedMaxPooling, VolumetricDilatedAveragePooling, VolumetricDilatedMaxUnpooling, SpatialDilatedMaxPooling, SpatialDilatedAveragePooling and SpatialDilatedMaxUnpooling)?

We are trying to perform 3D deep learning on EM images and we need 3D dilated convolution and 3D dilated pooling.

**Comment by fyu** [comment]
It will be great to have this support in 3D. People working on 3D shapes will find this helpful as well.

High dimensional dilated convolution is supported in caffe: https://github.com/BVLC/caffe/blob/master/src/caffe/util/im2col.cu#L160. It may be helpful for implementing the feature in Torch.

**Comment by kmul00** [comment]
Hi,

`VolumetricDilatedConvolution` will be very easy to implement. 

Using Soumith's implementation of the `Spatial` counterpart as pointer (taking care of the extra *dimension*), [these](https://github.com/torch/nn/commit/7e86ba4f2b687d8cfe1d34fc8770506610bb4f94) changes need to be replicated in `VolumetricDilatedConvolution` and made in `VolumetricFullConvolution` .

**Comment by kmul00** [comment]
Also, just out of curiosity, can you please briefly explain, or point me to some resources, regarding how `DilatedPooling` is supposed to work ?

I couldn't find any relevant paper/ implementation/ explanation regarding it.

Thanks in advance.

**Comment by psicalculus** [comment]
DilatedPooling is like DilatedConvolution in terms of how you apply filters to pixels/voxels. The only difference is that you do something else with the "selected pixels/voxels" - you take the maximum (max-pooling) or the average (average-pooling).

**Comment by kmul00** [comment]
Ah, I see !

Thanks for clarifying. :)

**Comment by psicalculus** [comment]
Has there been any progress in implementing 3D dilated convolution and 2D/3D dilated pooling in Torch?

**Comment by psicalculus** [comment]
We are trying to get some GPU-based platform to work for our research, right now. Implementations of 3D dilated convolution and 2D/3D dilated pooling would be very much appreciated.

**Comment by psicalculus** [comment]
Please also see https://github.com/torch/nn/issues/886 which is related to this request.

**Comment by soumith** [comment]
#886 is not related to this request.

Anyways, I am working on VolumetricDilatedConvolution.

Will get to Pooling after that.

**Comment by soumith** [comment]
committed CPU and CUDA versions of VolumetricDilated convolution via https://github.com/torch/nn/pull/902 and https://github.com/torch/cunn/pull/313

**Comment by psicalculus** [comment]
Thanks!

**Comment by soumith** [comment]
SpatialDilated pooling is also now implemented thanks to @kmul00 . Just need VolumetricDilatedPooling. @kmul00 want to implement that too? :p

**Comment by kmul00** [comment]
@soumith  Yeah I will. That was the plan. I wanted to wait and find out the reviews for `SpatialDilatedMax Pooling`, if it's breaking any code or something.

Like Sergey said, once I fix that concern, I'll get on with the `Volumetric` version.

**Comment by soumith** [comment]
these are now implemented, both dilated convolution and pooling for both spatial and volumetric
