### ISSUE TITLE
getParameters() update does not change cloned module weight

### ISSUE THREAD

**Issue by karandwivedi42** [torch/nn#871]
When using `clone()`, changing the `weight` of one module changes another's `weight`. However, changing its flattened parameters does not change the other module's `weight`.
```lua
require 'nn'
first = nn.Linear(2,2)
second = first:clone('weight' , 'bias' , 'gradBias' , 'gradWeight')
first.weight:fill(111)
params, gradParams = first:getParameters()
params:fill(999)
print(first.weight)
print(second.weight)
```

Output:

```
th> print(first.weight)
 999  999
 999  999
[torch.DoubleTensor of size 2x2]

                                                                      [0.0001s]
th> print(second.weight)
 111  111
 111  111
[torch.DoubleTensor of size 2x2]
```

I expected `second.weight` and `first.weight` to be equal. What is the way to do that?

**Comment by nicholas-leonard** [comment]
Try `nn.Container():add(first):add(second):getParameters()`

That will preserve the shared parameters.

**Comment by karandwivedi42** [comment]
Thanks @nicholas-leonard 

Why is this behaving like this though?

**Comment by nicholas-leonard** [comment]
getParameters() will assign a single storage to all parameters and gradParameter tensors in the model. It can preserve parameter sharing, but only if all shared parameters are part of the same model.

**Comment by karandwivedi42** [comment]
thanks @nicholas-leonard

**Comment by karandwivedi42** [comment]
@nicholas-leonard if the layers are part of a bigger module, and I want only some of the layers' weights in getParameters(), like in [this](https://lh3.googleusercontent.com/-Tvdzl8yejpA/VZbE3hhUDCI/AAAAAAAAADk/ecGAz9EhPZo/s1600/Untitled%2Bdrawing.png), if I want to optimise 1+2a followed by 1+2b in every iteration, then I cannot use `getParameters()` of complete model.

**Comment by fmassa** [comment]
You can overwrite `parameters` and `accGradParameters` to be empty functions. This  way you can still call `getParameters`, but the some weights will be frozen
