### ISSUE TITLE
MaxUnpooling modules not working?

### ISSUE THREAD

**Issue by MKimiSH** [torch/nn#878]
I was intended to use unpooling layers(nn.VolumetricMaxUnpooling), but it didn't work out. And I tested the SpatialMaxUnpooling layer too and it gave the same error. Here's the code I used:

`require 'nn'
require 'nngraph'
require 'image'

nngraph.setDebug(true)
m = nn.Sequential()
local volconv = nn.VolumetricConvolution
local volfulconv = nn.VolumetricFullConvolution
local poolingmodule = nn.VolumetricMaxPooling(2,2,2, 2,2,2,0,0,0) -- the parameters seem to have no relation to this error)
local volunpool = nn.VolumetricMaxUnpooling(poolingmodule)

volunpool:setParams()
print(poolingmodule)
print(volunpool)
print(volunpool.otime)

input = nn.Identity()()
m:add(volconv(3, 10, 3,5,5)):add(nn.View(2,5,18,16,16)):add(nn.Max(1))
m:add(volunpool)
--m:add(poolingmodule)

output = m(input)
--output = volunpool(input)

g = nn.gModule({input}, {output})
indata = torch.rand(3,20, 20, 20)
g:forward(indata)
--graph.dot(g.fg, 'volunpool', 'volunpool')`

ERROR is as follows:
`/home/mkimish/torch/install/bin/luajit: /home/mkimish/torch/install/share/lua/5.1/nn/THNN.lua:109: bad argument #5 to 'v' (cannot convert 'nil' to 'int')
stack traceback:
	[C]: in function 'v'
	/home/mkimish/torch/install/share/lua/5.1/nn/THNN.lua:109: in function 'VolumetricMaxUnpooling_updateOutput'
	...orch/install/share/lua/5.1/nn/VolumetricMaxUnpooling.lua:25: in function 'func'
	.../mkimish/torch/install/share/lua/5.1/nngraph/gmodule.lua:333: in function 'neteval'
	.../mkimish/torch/install/share/lua/5.1/nngraph/gmodule.lua:368: in function <.../mkimish/torch/install/share/lua/5.1/nngraph/gmodule.lua:288>
	[C]: in function 'xpcall'
	.../torch/install/share/lua/5.1/nngraph/graphinspecting.lua:35: in function 'forward'
	volunpool.lua:27: in main chunk
	[C]: in function 'dofile'
	...mish/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50
stack traceback:
	[C]: in function 'error'
	.../torch/install/share/lua/5.1/nngraph/graphinspecting.lua:43: in function 'forward'
	volunpool.lua:27: in main chunk
	[C]: in function 'dofile'
	...mish/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50
`

Maybe I should transfer to FullConvolution layers? I think they do the same thing as the unpooling+convolution layers.

Thanks in advance.

**Comment by fmassa** [comment]
Looks like you are not including the `MaxPooling` module in your network, and when you add it, you are adding it **after** the `MaxUnpooling`, but it should be before. This fixes your snippet

**Comment by MKimiSH** [comment]
So I have to include `MaxPooling` in the network whenever I want to use `MaxUnpooling` ?

**Comment by fmassa** [comment]
That's the principle of `MaxUnpooling`: to take the indices that were pooled from `MaxPooling` and 'unpool' them, filling the rest with zero.

**Comment by MKimiSH** [comment]
Many thanks. I am new of torch. Closing this.
