### ISSUE TITLE
Why DistKLDivCriterion is different from wikipedia KL Divergence formula?

### ISSUE THREAD

**Issue by euwern** [torch/nn#883]
In the documentation, DistKLDivCriterion loss is defined as
loss(x, target) = 1/n \sum(target_i * (log(target_i) - x_i))

If n = 1 then the loss is
loss(x, target) = \sum(target_i * (log(target_i) - x_i))

But the KL Divergence formula from wikipedia looks like: (note I am translating the math equation to the similar syntax used above)
loss(x, target) = \sum(x_i * log(x_i / target_i))
https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence

The wikipedia formula makes sense because if the x and target probability distribution are the same then it will yield zero loss. 

Can someone clarify why the implementation in torch is different from the formula from wikipedia?

**Comment by kuangliu** [comment]
The math doesn't make sense to me. 
when x=target, the distance should be zero... I suppose.

@soumith

**Comment by agane** [comment]
The inputs x are expected to be log-probabilities https://github.com/torch/nn/blob/master/doc/criterion.md. When x == log(target) the distance is 0.

**Comment by euwern** [comment]
Thanks agane, you are right. The document clearly states that
" the input given through a forward() is expected to contain log-probabilities"

By setting x = log(x)
we will get:
loss(log(x), target) = \sum(target_i * (log(target_i) - log(x_i)))

The wikipedia formula, can also be rewritten as
log(target, x) = \sum(target_i * log(target_i / x_i))
log(target, x) = \sum(target_i * (log(target_i) - log(x_i)))
