### ISSUE TITLE
Feature Request: Support for 2D/3D Sliding Window CNNs

### ISSUE THREAD

**Issue by psicalculus** [torch/nn#886]
Could you please add support for 2D/3D sliding window CNNs in Torch nn?

The following papers use sliding window CNNs:
1) http://people.idsia.ch/~juergen/nips2012.pdf
2) https://papers.nips.cc/paper/5636-recursive-training-of-2d-3d-convolutional-networks-for-neuronal-boundary-prediction.pdf
3) http://arxiv.org/pdf/1606.02382.pdf
4) http://arxiv.org/pdf/1606.07372.pdf

The only software framework available for doing this is ZNN but it only runs on CPUs:
http://znn-release.readthedocs.io/en/latest/index.html

We would appreciate a GPU-based implementation of sliding window CNNs (similar to what the people in paper 1) used).

**Comment by soumith** [comment]
you actually misunderstand. Torch does and always supported "sliding window CNNs".
If you have your entire neural network consiting of Spatial* modules, for example SpatialConvolution, SpatialMaxPooling etc., then if you give a larger input than what the network experts, the network is slid over the larger input to give a larger output than 1x1.
Hope this helps.
