### ISSUE TITLE
about WeightedMSECriterion

### ISSUE THREAD

**Issue by Doubaibai** [torch/nn#887]
Hi,

I found that the WeightedMSECriterion module is different from what I understand a weighted MSE's function. 

Suppose output is o, target is t, weights for WeightedMSECriterion is w. Then a typical weighted MSE should do like:
\sum_i  {w_i*(o_i-t_i)^2}

However, what the module does is:

\sum_i {(w_i*o_i - t_i)^2}

In sum, the weights are multiplied to the targets instead of the individual Squared Error.  Could somebody help me explain this?

Thanks!

**Comment by joeyhng** [comment]
This has been discussed in #384.
