### ISSUE TITLE
MaskedSelect Layer

### ISSUE THREAD

**Issue by jingweiz** [torch/nn#893]
Hey,
I have a question as how to use this MaskedSelect Layer in my model definition. So the way to do a forward pass on this layer is to do:
local out = module:forward({input, mask})
then if I want to put this layer inside my network definition, how should I do it? Cos now I suppose I must first do a forward pass on all the layers before it, then get the output, then feed the output along with the mask to this layer, or is there another way of doing it that I'm missing?
Thanks in advance!

**Comment by fmassa** [comment]
you can use `Table` modules to do the task for you, without having to stop in the middle and do another forward.
If writing your model definition is too involved using pure `nn` modules, you should consider using `nngraph`.
Also, those questions are better suited for the [gitter](https://gitter.im/torch/torch7) or [Google Groups](https://groups.google.com/forum/#!forum/torch7)
