### ISSUE TITLE
Unable to do parameter sharing in Torch between [sub]networks

### ISSUE THREAD

**Issue by Amir-Arsalan** [torch/nn#897]
I am trying to share the parameters between the encoder/decoder sub-networks of an architecture with another encoder/decoder in a different architecture. This is necessary for my problem since at the test time it requires a lot of computation (and time) to do a forward pass on the original architecture and then extract the decoder results. However, what I noticed was although I have explicitly asked for parameter sharing when doing clone(), the parameters are not shared and each architecture has its own parameters while training.

I am showing the difference between the results of the two architecture via some print() statements by forward-propagating some random vectors into the decoder and encoders of both architectures (you can do also compare their weights).

So I wonder, can anyone help me find out what I'm doing wrong when sharing the parameters?

Below I post a simplified version of my code. The encoder and decoder are also cloned and their outputs are used for some other purposes in addition to some other complexities for the original architecture. But the example below should be a good, simplified version of my main architecture:

```
require 'nn'
require 'nngraph'
require 'cutorch'
require 'cunn'
require 'optim'


input = nn.Identity()()
encoder = nn.Sequential():add(nn.Linear(100, 20)):add(nn.ReLU(true)):add(nn.Linear(20, 10))
decoder = nn.Sequential():add(nn.Linear(10, 20)):add(nn.ReLU(true)):add(nn.Linear(20, 100))
code = encoder(input)
reconstruction = decoder(code)

outsideCode = nn.Identity()()
decoderCloned= decoder:clone('weight', 'bias', 'gradWeight', 'gradBias')
outsideReconstruction = decoderCloned(nn.JoinTable(1)({code, outsideCode}))
dumbNet = nn.Sequential():add(nn.Linear(100, 10))
codeRecon = dumbNet(outsideReconstruction)

input2 = nn.Identity()()
encoderTestTime = encoder:clone('weight', 'bias', 'gradWeight', 'gradBias')
decoderTestTime = decoder:clone('weight', 'bias', 'gradWeight', 'gradBias')
codeTest = encoderTestTime(input2)
reconTest = decoderTestTime(codeTest)

gMod = nn.gModule({input, outsideCode}, {reconstruction, codeRecon})
gModTest = nn.gModule({input2}, {reconTest})

criterion1 = nn.BCECriterion()
criterion2 = nn.MSECriterion()

-- Okay, the module has been created. Now it's time to do some other stuff

params, gParams = gMod:getParameters()

numParams = params:nElement()
memReqForParams = numParams * 5 * 4 / 1024 / 1024 -- Convert to MBs

-- If enough memory on GPU, move stuff to the GPU
if memReqForParams <= 1000 then
    gMod = gMod:cuda()
    gModTest = gModTest:cuda()
    criterion1 = criterion1:cuda()
    criterion2 = criterion2:cuda()
    params, gParams = gMod:getParameters()
end

-- Data

Data = torch.rand(200, 100):cuda()
Data[Data:gt(0.5)] = 1
Data[Data:lt(0.5)] = 0

fakeCodes = torch.rand(400, 10):cuda()

config = {learningRate = 0.001}
state = {}

-- Start training
print ("\nEncoders before training: \n\tgMod's Encoder: " .. gMod:get(2):forward(torch.ones(1, 100):cuda()):sum() .. "\n\tgModTest's Encoder: " .. gModTest:get(2):forward(torch.ones(1, 100):cuda()):sum())
print ("\nDecoders before training: \n\tgMod's Decoder: " .. gMod:get(3):forward(torch.ones(1, 10):cuda()):sum() .. "\n\tgModTest's Decoder: " ..  gModTest:get(3):forward(torch.ones(1, 10):cuda()):sum())


gMod:training()
for i=1, Data:size(1) do
    local opfunc = function(x)
        if x ~= params then
            params:copy(x)
        end
        gMod:zeroGradParameters()
        recon, outsideRecon = unpack(gMod:forward({Data[{{i}}], fakeCodes[{{i}}]}))
        err = criterion1:forward(recon, Data[{{i}}])
        df_dw = criterion1:backward(recon, Data[{{i}}])

        errFake = criterion2:forward(outsideRecon, fakeCodes[{{i*2-1, i * 2}}])
        df_dwFake = criterion2:backward(outsideRecon, fakeCodes[{{i*2-1, i * 2}}])

        errorGrads = {df_dw, df_dwFake}
        gMod:backward({Data[{{i}}], fakeCodes[{{i*2-1, i * 2}}]}, errorGrads)

        return err, gParams
    end

    x, reconError = optim.adam(opfunc, params, config, state)
end

print ("\n\nEncoders after training: \n\tgMod's Encoder: " .. gMod:get(2):forward(torch.ones(1, 100):cuda()):sum() .. "\n\tgModTest's Encoder: " .. gModTest:get(2):forward(torch.ones(1, 100):cuda()):sum())
print ("\nDecoders after training: \n\tgMod's Decoder: " .. gMod:get(3):forward(torch.ones(1, 10):cuda()):sum() .. "\n\tgModTest's Decoder: " ..  gModTest:get(3):forward(torch.ones(1, 10):cuda()):sum())
```

**Comment by fmassa** [comment]
If you call `getParameters` it will destroy any sharings that you have done if they are not inside the network in which you call getParameters.
I haven't looked into details in your code, but wrapping your two networks in a `nn.Container` and calling `getParameters` on this container should fix it.

```lua
container = nn.Container()
container:add(gMod)
container:add(gModTest)
params, gradParams = container:getParameters()
```

**Comment by soumith** [comment]
please dont post the same question at many different places. we only have a limited time for supporting users, and duplicate questions is very bad. You have posted the same question at 5 different places! This question belongs on the google groups.

**Comment by Amir-Arsalan** [comment]
@soumith I believe the goal here should be to help others not being mad at people for posting their questions in different places, which is what people are supposed to do naturally ...

**Comment by Amir-Arsalan** [comment]
@soumith Well if I had not posted my question on several places I wouldn't have been able to get the answer. Thanks to @fmassa for providing a very easy solution to the problem. I'll now update my posts in other places :)

**Comment by soumith** [comment]
Please follow the rules. 

Getting an answer by posting to several places is a terrible way of using volunteers time, and we get drained seeing the same question at many places.

Do not do it again.

Post questions on google groups and post bugs on github issues.

**Comment by Amir-Arsalan** [comment]
@soumith Well I definitely knew this is a place where people report possible bugs. After trying out a lot of methods to resolve my issue, I was almost confident that this is a bug. The documentation is incomplete and does not point out anything about these subtle points, otherwise I wouldn't post my question here. If you look at the times I posted my questions on the Google forum and StackOverflow you can see that I posted those before posting the issue here.

Anyways, thanks for all your support and I understand the points you made.

**Comment by Liu0329** [comment]
@Amir-Arsalan Thank you Amir, I just have the same problem !

**Comment by Liu0329** [comment]
@Amir-Arsalan Hi, now I have a similar problem, but @fmassa 's solution seems not work here. I want the linear module with mlp1&2 share the same params, is there a way to do that ?
```
local h = nn.Identity()()
local mlp1 = nn.Linear(5, 1)(h)
local mlp2 = nn.Linear(5, 1)(h)
gmod = nn.gModule({h}, {mlp1, mlp2})
x = torch.rand(3, 5)
y = gmod:forward(x)
```

**Comment by alirezag** [comment]
Try mlp2 = mlp1:clone('weight','bias','gradWeight','gradBias');
