### ISSUE TITLE
Is SparseLinear:updateGradInput necessary?

### ISSUE THREAD

**Issue by ameenetemady** [torch/nn#906]
It seems to me that SparseLinear is only used as the first layer of the network. If so, it helps performance to not implement the updateGradInput in it, right? 
[I tried in a different Linear module which I use only in the first layer, and training seem to work fine. or maybe I'm missing something? Avoiding it helped me by avoiding extra memory allocation]

**Comment by nkoumchatzky** [comment]
There is a 'doGradInput' option that is false by default, meaning
updateGradInput won't do anything. But you could imagine cases where
SparseLinear could be used as the non-first layer.


2016-08-04 14:27 GMT-04:00 ameenetemady <notifications@github.com>:

**Comment by ameenetemady** [comment]
Nice, thanks, I didn't catch that.
