### ISSUE TITLE
SpatialDilatedConvolution: dilationW/H params acquired in wrong order

### ISSUE THREAD

**Issue by xonobo** [torch/nn#908]
The dilationW and dilationH parameters are scanned in different order.
m = nn.SpatialDilatedConvolution(1, 3, 5, 5, 1, 1, 2, 0, 1, 2)
print(m) --> nn.SpatialDilatedConvolution(1 -> 3, 5x5, 1,1, 2,0, 2,1)
print(m.dilationW) --> 2	
print(m.dilationH) --> 1

**Comment by xonobo** [comment]
Seems to use swapped versions of dilation parameters.

m = nn.SpatialDilatedConvolution(1, 3, 5, 5, 1, 1, 0, 0, 1, 2)
print(m) --> nn.SpatialDilatedConvolution(1 -> 3, 5x5, 2,1)
m:forward(torch.Tensor(1,9,5)):size() --> 3x1x1 [torch.LongStorage of size 3]

(I assume the tensor dimensions are taken as CxHxW)

**Comment by soumith** [comment]
see documentation. the constructor ordering of all parameters is W, H

**Comment by xonobo** [comment]
The dilation is applied in height dimension in the last example but the m.dilationH=1 while m.dilationW=2. This mix should be corrected. The result is coherent with the constructor call but not with module's dilation parameters.

**Comment by soumith** [comment]
hi @xonobo . There must be some confusion. I fixed this issue a couple of days ago in https://github.com/torch/nn/pull/902 and the bug was present in earlier versions. updating your nn will fix it.
