### ISSUE TITLE
Make a dataset with my own images for train/test a model

### ISSUE THREAD

**Issue by jmortizs** [torch/nn#909]
First, sorry if this is not the place to post this question.
I'm been working with nvidia DIGITS for design and training some models for classify MRI images now I decided to use torch outside of DIGITS for an specific task, so I'm stuck with the "dataset creation" because with DIGITS is as simple as have your images separated in folders, each folder is a class.

```
-Dataset/
--FolderClass0/
---Image1.png
---image2.png
--FolderClass1/
---Image1.png
---image2.png
```
Did not find a tutorial/demo that teach me how to create my own dataset for train my newtwork in torch.

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.
