### ISSUE TITLE
Does VolumetricFullConvolution support 3D DeConvolution (Upsampling)?

### ISSUE THREAD

**Issue by barrykui** [torch/nn#912]
Does torch implement 3D DeConvolution (Upsampling)? Found that the documentation of **SpatialFullConvolution** says, Other frameworks call this operation "In-network Upsampling", "Fractionally-strided convolution", "Backwards Convolution," "Deconvolution", or "Upconvolution.".
So I guess that VolumetricFullConvolution could  do 3D deconvolution, but not sure, can anyone tell me?

Best Regards,
Kui

**Comment by soumith** [comment]
yes
