### ISSUE TITLE
Element-by-element Cosine Distance?

### ISSUE THREAD

**Issue by davidechicco** [torch/nn#919]
Hi
I've a little problem with CosineDistance, perhaps someone can help me.

Is there a way I can use CosineDistance to compute the cosine distance of each pair of single values in two tensors?

I have a table made of two Tensors:
```

require 'nn'
N = 4
aaaTensor = torch.randn(N)
bbbTensor = torch.randn(N)
thisTable = {aaaTensor, bbbTensor}
```

I would like to compute the cosine distance for each pair of single values of aaaTensor and bbbTensor:

    the cosine distance between aaaTensor[1] and bbbTensor[1]
    the cosine distance between aaaTensor[2] and bbbTensor[2]
    ...
    the cosine distance between aaaTensor[N] and bbbTensor[N]

And I don't know how to do this. If I use the nn.CosineDistance() module (link), it will compute the general cosine distance between aaaTensor and bbbTensor:

```
cosine = nn.CosineDistance()
cosine:forward{aaaTensor, bbbTensor}
0.7185
[torch.DoubleTensor of size 1]
```

I want to have N=4 outputs.

How could I implement this one-by-one cosine distance computation? Thanks

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.

**Comment by davidechicco** [comment]
Sure I can (even if often people do not answer on that Google Group...).

Thanks
