### ISSUE TITLE
nn.JoinTable negative dimension support errors

### ISSUE THREAD

**Issue by deet** [torch/nn#920]
The code
```
nn.JoinTable(-1):forward{torch.randn(5, 1), torch.randn(5, 1)}
```
produces an error at 

`nn/JoinTable.lua:14: attempt to call method 'dim' (a nil value)`

(https://github.com/torch/nn/blob/ead8af9c14f26116c1fe4fc5d58a6b0de2b2603f/JoinTable.lua#L14)

while
```
nn.JoinTable(1):forward{torch.randn(5, 1), torch.randn(5, 1)}
```
works fine.

This code appears copied from from SplitTable, but the input to JoinTable is table, not a tensor, so there is no `dim` method.

**Comment by soumith** [comment]
thanks for the report. fixed now in master.
