### ISSUE TITLE
How to print  the output dimension size of each layer, just like "Top shape" in caffe

### ISSUE THREAD

**Issue by barrykui** [torch/nn#922]
Dear all, I want to know output dimension size of each layer. As we know, caffe print the "Top shape" while running. But I don't know how to print it in torch.

"Top shape" by caffe
> I0810 14:03:04.434058 43020 net.cpp:127] Top shape: 10 3 16 112 112 (6021120)

Best Regards,
Kui

**Comment by kmul00** [comment]
Hi,

Every layer in torch's models can be accessed using `model.modules`.
For example if you have a model like this :
```lua
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> output]
  (1): nn.Linear(10 -> 20)
  (2): nn.Linear(20 -> 15)
  (3): nn.Linear(15 -> 2)
}
```
Once you have made a `forward` pass, like this :

```lua
input  = torch.Tensor(5, 10)
model:forward(input)
```
You can view the output dimension of each layer.

If you want to view for a particular layer, say the second layer in the above case, you can simply do:

```lua
th> model.modules[1].output:size()
  5
 20
[torch.LongStorage of size 2]
```
Or you can view for all the layers by simpy doing `model.modules`. It will display all relevant information (like weight, biases, output dimensions e.t.c) for each layer.

**Comment by barrykui** [comment]
Yeah, It works! Thank you so much.

**Comment by scotwilli** [comment]
Hi. How to do it in caffe2. Thanks
