### ISSUE TITLE
nn.DistKLDivCriterion()

### ISSUE THREAD

**Issue by haanvid** [torch/nn#923]
About the Kullback-Leibler divergence ( nn.DistKLDivCriterion() )

nn/lib/THNN/generic/DistKLDivCriterion.c
https://github.com/torch/nn/blob/master/lib/THNN/generic/DistKLDivCriterion.c
at line 15

`sum += *target_data > 0 ? *target_data * (log(*target_data) - *input_data) : 0;`

shouldn't " *input_data " be a " log(*input_data) "?
Is " *input_data  " already a log of model class output  distribution?

Also, the readme for the criterion seems to contain wrong information about the Kullback-Leibler divergence.
at https://github.com/torch/nn/blob/master/doc/criterion.md#nn.Criterions,
first line of explanation on nn.DistKLDivCriterion(),

> loss(x, target) = 1/n \sum(target_i * (log(target_i) - x_i))

shouldn't it be a

loss(x, target) = 1/n \sum(target_i * (log(target_i) - log(x_i)))  ?

link for explanation on Kullback-Leibler divergence on wikipedia: https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence

**Comment by soumith** [comment]
The input to nn.DistKLDivCriterion is log(output).

It is given in the doc here: https://github.com/torch/nn/blob/master/doc/criterion.md#nn.DistKLDivCriterion

**Comment by soumith** [comment]
> shouldn't it be loss(x, target) = 1/n \sum(target_i * (log(target_i) - log(x_i))) ?

Because x_i is already expected to be the output of a log transform, one does not need to take log on x_i again.

**Comment by soumith** [comment]
Relevant line:

> As with ClassNLLCriterion, the input given through a forward() is expected to contain log-probabilities, however unlike ClassNLLCriterion, input is not restricted to a 1D or 2D vector (as the criterion is applied element-wise).

**Comment by haanvid** [comment]
Thanks!
