### ISSUE TITLE
Difference between MaxPooling and SubSampling

### ISSUE THREAD

**Issue by dolaameng** [torch/nn#944]
Forgive me if I am asking a naive question. What is the difference between Pooling and Sampling, say [TemporalMaxPooling](https://github.com/torch/nn/blob/master/doc/convolution.md#temporalmaxpooling) vs [TemporalSubSampling](https://github.com/torch/nn/blob/master/doc/convolution.md#temporalsubsampling), and [SpatialMaxPooling](https://github.com/torch/nn/blob/master/doc/convolution.md#spatialmaxpooling) and [SpatialSubSampling](https://github.com/torch/nn/blob/master/doc/convolution.md#spatialsubsampling)?  

My understanding is that both of them are layer-wise operations (as special cases of convolution?), where each layer of the input will be mapped independently to a layer of the output. With the difference that a `MaxPooling` uses a max op and `SubSampling` uses a `Weighted sum of the local region`. 

So is it safe to say that `SubSampling` is a generalization of `MaxPooling` and `AveragePooling`? Is there any references on how to use `SubSampling` in practice?

The documentations on both [TemporalSubSampling](https://github.com/torch/nn/blob/master/doc/convolution.md#temporalsubsampling) and  [SpatialSubSampling](https://github.com/torch/nn/blob/master/doc/convolution.md#spatialsubsampling) are a little confusing. E.g.,
- In TemporalSubSampling Section, it says "If the input sequence is a 2D tensor `nInputFrame x inputFrameSize`, the output sequence will be `inputFrameSize x nOutputFrame`", should it be `nOutputFrame x inputFrameSize` based on the definition equation below or I misunderstood it?
- Similar as in SpatialSubSampling section, where it says "the output image size will be `nInputPlane x oheight x owidth`", but in the equation below `output[i][j][k] = bias[k] + weight[k] sum_{s=1}^kW sum_{t=1}^kH input[dW*(i-1)+s)][dH*(j-1)+t][k]`, the order of the input and output dimension is actually `owidth x oheight x nInputPlane`.

Appreciate it if someone can help.

**Comment by soumith** [comment]
SubSampling is simply AveragePooling with learnable weights per feature map. SubSampling is not a generalization of MaxPooling, it is a generalization of AveragePooling

**Comment by dolaameng** [comment]
Thank you @soumith! I was kinda thinking that the max op can also be approximated by an adaptive weighted sum with one for the maximum elements and zeros everywhere else. But I think i got what you mean.

**Comment by fast-reflexes** [comment]
Hmm... I just keep wondering, subsampling with learnable weights sounds a lot like a regular convolution layer, what would be the difference?
