### ISSUE TITLE
Wrong size of output feature map in SpatialDilatedConvolution layers

### ISSUE THREAD

**Issue by sunshineatnoon** [torch/nn#945]
I have three layers of SpatialDilatedConvolution like this:
```
self.encoder:add(nn.SpatialDilatedConvolution(64, 64, 3, 3, 2, 2, 1, 1, 2, 2))
...
self.encoder:add(nn.SpatialDilatedConvolution(128, 128, 3, 3, 2, 2, 1, 1, 2, 2))
...
self.encoder:add(nn.SpatialDilatedConvolution(256, 256, 3, 3, 2, 2, 1, 1, 2, 2))
```
Between them are some convolutional layers that don't change input feature map size. My input is 64\*64 images, from the documentation of SpatialDilatedConvolution:

```
owidth  = floor(width + 2 * padW - dilationW * (kW-1) + 1) / dW + 1
oheight = floor(height + 2 * padH - dilationH * (kH-1) + 1) / dH + 1
```
 the output feature map size should be 8\*8, 

```
floor((64+2*1-2*2+1)/2+1) = 32
floor((32+2*1-2*2+1)/2+1) = 16
floor((16+2*1-2*2+1)/2+1) = 8
```
but I got this error:

`Wrong size for view. Input size: 50x512x7x7. Output size: 50x32768`
Indicating the output size is 7\*7.
Am I doing anything wrong here? THX!

**Comment by kmul00** [comment]
Hi,

You're right. There is a typo in the doc. The actual formulation is :
```lua
outputWidth = floor((inputWidth + 2*padW - (dilationW * (kW - 1) + 1)) / dW) + 1;
```
You can verify [here](https://github.com/torch/nn/blob/master/lib/THNN/generic/SpatialDilatedConvolution.c#L40-L41) in the actual code for `SpatilDilatedConvolution`.

**Comment by sunshineatnoon** [comment]
Thanks! That solves my issue.
