### ISSUE TITLE
TemporalDilatedConvolution

### ISSUE THREAD

**Issue by Kaixhin** [torch/nn#957]
Feature request for `nn.TemporalDilatedConvolution`. The paper hasn't been released publicly, but according to this [blog post](https://deepmind.com/blog/wavenet-generative-model-raw-audio/) it seems to be a key component of WaveNets.

**Edit**: The link to the paper at the time of posting was only accessible to Google members. Upon reading they do indeed use 1D dilated convolutions.

**Comment by soumith** [comment]
Paper is released and here: 
https://drive.google.com/file/d/0B3cxcnOkPx9AeWpLVXhkTDJINDQ/view

**Comment by syhw** [comment]
You can use https://github.com/torch/nn/blob/master/doc/convolution.md#nn.SpatialDilatedMaxPooling in 1D.

**Comment by Kaixhin** [comment]
That's definitely a solution - the question remains whether it's worth making a special version for 1D? If not then I'll close this.

**Comment by soumith** [comment]
i'm going to work out the algo tomorrow, but this is not super easy to implement into nn.TemporalConvolution because it heavily piggy-backs on using gemm directly over each feature-map. Using nn.SpatialDilated* is prob better here..

**Comment by soumith** [comment]
the way TF implements it is by invoking a pretty crazy transpose, copy and unfold every forward/backward.
