### ISSUE TITLE
clearState and garbage collection

### ISSUE THREAD

**Issue by karandwivedi42** [torch/nn#972]
For example

```lua
require 'nn';
x = nn.Linear(10000,10000)
x = nil
collectgarbage()
```
immediately frees up memory but

```lua
require 'nn';
x = nn.Linear(10000,10000)
x:clearState()
x = nil
collectgarbage()
```

does not.

Is there some other way to remove a model than `model = nil` ?

**Comment by fmassa** [comment]
I can reproduce the problem.
This is very weird. I don't know yet why this is happening.
We can reduce even further the problem to the following snippet:

```lua
require 'nn';
x = nn.Linear(10000,10000)
nn.utils.clear(x) -- this is supposed to do nothing
x = nil
collectgarbage()
```

@szagoruyko any idea on this?

**Comment by iamalbert** [comment]
`clearState` only clears `gradInput` and `output`, not destroy the module. Why should the memory decrease?

**Comment by albanD** [comment]
@fmassa I guess you run this in your interpreter?
`nn.utils.clear` actually returns the module. And the interpreter store it in a global to be able to show it to you. Doesn't this prevent the garbage collection?
If you use `x = nn.utils.clear(x)`, does it work as expected?

**Comment by karandwivedi42** [comment]
Yes. Using `x = nn.utils.clear(x)` works as expected.

**Comment by fmassa** [comment]
Yes @albanD, I was running in the interpreter, and I had checked with `who()` and `_G` but I didn't see the `x` module, but I didn't look hard enough for it.
Thanks fir finding the issue !

**Comment by albanD** [comment]
After looking into the `trepl` code:
The last returned element can be found in the `_RESULT` global variable.
And all the previous returned elements can be found in the `_RESULTS` global table.
You will find the reference to the `x` module inside this `_RESULTS` table after the `collectgarbage()` call that returned `0`.
