### ISSUE TITLE
THNN.lua:110: wrong number of arguments for function call

### ISSUE THREAD

**Issue by samikbanerjee69** [torch/nn#975]
After updating to this version of 'nn', the error I'm getting this error:

/home/vplab/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
In 1 module of nn.Sequential:
In 3 module of nn.Sequential:
/home/vplab/torch/install/share/lua/5.1/nn/THNN.lua:110: wrong number of arguments for function call
stack traceback:
	[C]: in function 'v'
	/home/vplab/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialMaxPooling_updateOutput'
	...lab/torch/install/share/lua/5.1/nn/SpatialMaxPooling.lua:42: in function <...lab/torch/install/share/lua/5.1/nn/SpatialMaxPooling.lua:31>
	[C]: in function 'xpcall'
	/home/vplab/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/vplab/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/vplab/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	/home/vplab/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/vplab/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/vplab/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	...
	/home/vplab/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
	/home/vplab/Desktop/samik/trainGraph.lua:172: in function 'trainBatch'
	/home/vplab/Desktop/samik/trainGraph.lua:207: in function 'train'
	/home/vplab/Desktop/samik/trainGraph.lua:218: in main chunk
	[C]: in function 'dofile'
	[string "_RESULT={dofile('/home/vplab/Desktop/samik/tr..."]:1: in main chunk
	[C]: in function 'xpcall'
	/home/vplab/torch/install/share/lua/5.1/trepl/init.lua:652: in function 'repl'
	...plab/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x004065d0

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/vplab/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/vplab/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	/home/vplab/Desktop/samik/trainGraph.lua:166: in function 'opfunc'
	/home/vplab/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
	/home/vplab/Desktop/samik/trainGraph.lua:172: in function 'trainBatch'
	/home/vplab/Desktop/samik/trainGraph.lua:207: in function 'train'
	/home/vplab/Desktop/samik/trainGraph.lua:218: in main chunk
	[C]: in function 'dofile'
	[string "_RESULT={dofile('/home/vplab/Desktop/samik/tr..."]:1: in main chunk
	[C]: in function 'xpcall'
	/home/vplab/torch/install/share/lua/5.1/trepl/init.lua:652: in function 'repl'
	...plab/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x004065d0

Previously the code was working ok.

@soumith Please throw some light on this.

**Comment by soumith** [comment]
update nn and cunn
