### ISSUE TITLE
new cast error

### ISSUE THREAD

**Issue by holgafreak** [torch/nn#980]
Earlier I got error FloatTensor  to CudaTensor, but trying the new 2 hrs old commit, the error changed to 

/home/xxxx/torch/install/bin/luajit: /home/xxxx/torch/install/share/lua/5.1/nn/THNN.lua:110: bad argument #3 to 'v' (cannot convert 'struct THCudaLongTensor *' to 'struct THCudaTensor *')
stack traceback:
	[C]: in function 'v'
	/home/xxxx/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'ClassNLLCriterion_updateOutput'
	...xx/torch/install/share/lua/5.1/nn/ClassNLLCriterion.lua:41: in function 'forward'

**Comment by soumith** [comment]
hi matti, i just committed a fix to both nn and cunn that makes sure that ClassNLLCriterion's targets are consistent with CPU and CUDA.

You must've updated one, but not the other.
Update both packages via:
luarocks install nn
luarocks install cunn

Best
S

**Comment by holgafreak** [comment]
thanks, that error got away by install new cunn. Anyway for some reason on my ubuntu 16.04 and cuda 7.5 the workaround set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FORCE_INLINES") is not triggered. Explicitly forcing this in THCNN CMakeLists.txt, compiles cunn ok.
best
-m

**Comment by soumith** [comment]
thanks for the feedback, i'll adjust the workaround criteria. What is your GCC version?
You can get the GCC version with the command:

gcc --version

**Comment by holgafreak** [comment]
it's gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 

-m

**Comment by HuitingLiu** [comment]
luarocks install nn
luarocks install cunn  

It doesn't help.
