### ISSUE TITLE
How to discard some last layers of model after training?

### ISSUE THREAD

**Issue by hnanhtuan** [torch/nn#984]
Hi everyone,

May I ask if there is a way to throw away some last layers of the model after finishing training?
Thank you very much.

**Comment by fmassa** [comment]
`model:remove()` can be handy for that.
Also, those questions are best suited for the Google Groups https://groups.google.com/forum/embed/?place=forum%2Ftorch7#!forum/torch7 or the gitter chat https://gitter.im/torch/torch7

**Comment by hnanhtuan** [comment]
Thank you very much.
